### ISSUE TITLE
change PR workflow to prevent merge conflicts

### ISSUE THREAD

**Issue by jed** [brooklynjs/brooklynjs.github.io#141]
currently, merge conflicts for the `index.html` page are really annoying, since speakers will end up vying for the same slot.

we should have a system where instead of editing a five locations in a single file, all new PRs rename an existing file and edit it as needed. this file could even be JSON so that the front page could read it in in the browser without a build process.

**Comment by brianloveswords** [comment]
Thanks for your proposal! Unfortunately we're full this month, but we'd love to hear this talk next month.

**Comment by brianloveswords** [comment]
j/k lol

**Comment by jed** [comment]
You certainly are full... OF SOMETHING.

**Comment by jalcine** [comment]
How about [Gitflow sans the lack of fast forwarding](http://endoflineblog.com/gitflow-considered-harmful)?

**Comment by ericandrewlewis** [comment]
How about a call for speakers via an "issue" in the repo for each month. Speakers can apply by commenting on the issue.

**Comment by RichardLitt** [comment]
I think that @ericandrewlewis has the right idea. We can tag the issues as 'proposals' and then close them following inclusion. This would be much better than the current plan. 

@jed @brianloveswords what can we do to speed this along?

**Comment by jed** [comment]
we're looking to change the workflow in a way that might change the conflict issue, but haven't gotten around to finishing it yet: https://github.com/brooklynjs/brooklynjs.github.io/tree/jekyllize/_talks

**Comment by RichardLitt** [comment]
Couldn't we just use issues and then have them PR with your suggested format if they get accepted? 

What needs to change for that branch to work?

**Comment by modernserf** [comment]
Are y'all still interested in this at all? I've got some spare time to work on it.

**Comment by willmanduffy** [comment]
We just moved over to using Github Issues instead of PRs. Thanks for the input y'all!
