### ISSUE TITLE
I Don't Deserve to Be a Developer

### ISSUE THREAD

**Issue by sarahmeyer** [brooklynjs/brooklynjs.github.io#369]
## BrooklynJS Talk Submission

**Talk Title:** I Don't Deserve to Be a Developer

**Talk Description:** 10x programmer. Ninja. Rock star. These images of what a software developer should be are widely mocked — and widely shared. If coding is your career, we assume that it must also be your passion; our industry is set up to uplift and celebrate people who fit these stereotypes. What do you do if you’re someone who doesn’t? The truth is that the explosion of software as an industry has created unique distortions in our field. Come hear about the history of programming as a career — it may help you make a place for yourself in an industry that insists you must love what you do, or leave.

**Name**: Sarah Saltrick Meyer

**Twitter Handle (optional)**: meyerini

**Website (optional):**

**Months Available to Speak:** March/April/May

**Comment by kosamari** [comment]
🥇
