### ISSUE TITLE
(Mis)adventures with JS Compilers

### ISSUE THREAD

**Issue by NathanEpstein** [brooklynjs/brooklynjs.github.io#370]
## BrooklynJS Talk Submission

**Talk Title:**
(Mis)adventures with JS Compilers

**Talk Description:**
This talk will use a small personal project (a simple AI) to explore the usefulness of different JavaScript compilers in meeting various project requirements. It will include a survey of several popular JavaScript compilers (Babel, Emscripten, and TypeScript in particular) with an analysis of their benefits / tradeoffs.

**Name**:
Nathan Epstein

**Twitter Handle (optional)**:
@epstein_n

**Website (optional):**
nepste.in

**Months Available to Speak:** 
March, April, May

**Comment by kosamari** [comment]
YAY 👍

**Comment by hzoo** [comment]
I can review Babel stuff if you'd like @NathanEpstein

**Comment by NathanEpstein** [comment]
Much appreciated! I'll be sure to reach out if anything comes up!
