### ISSUE TITLE
Visualizing Hamilton

### ISSUE THREAD

**Issue by sxywu** [brooklynjs/brooklynjs.github.io#371]
## BrooklynJS Talk Submission

**Talk Title:** Visualizing Hamilton

**Talk Description:** 
[An Interactive Visualization of Every Line in Hamilton](http://polygraph.cool/hamilton/) is a visual analysis of the relationships between the musical's main characters, and the recurring phrases they're associated with.  The analysis is done via a custom filter tool of every line in the musical, and it's a labor of equal parts blood, sweat, tears, and love.  In this talk, I will talk about the labor that went into it, the mistakes I made, and the insights I found.

**Name**: Shirley Wu

**Twitter Handle (optional)**: [@sxywu](https://twitter.com/sxywu)

**Website (optional):** [sxywu.com](http://sxywu.com/)

**Months Available to Speak:** I will only be in town **April 2017**.

**Comment by kosamari** [comment]
woot ! really looking forward to the talk !

**Comment by sxywu** [comment]
YAYYYYY now to make a 30min talk into a 10min talk!
