### ISSUE TITLE
The Olympic Games, visualized through all 5000 Gold Medal winners

### ISSUE THREAD

**Issue by nbremer** [brooklynjs/brooklynjs.github.io#372]
## BrooklynJS Talk Submission

**Talk Title:** The Olympic Games, visualized through all 5000 Gold Medal winners

**Talk Description:** During the Olympics of Rio 2016 I created a visualization of all 5000 gold medal winners since the very first Olympic Games of 1896, called [Olympic Feathers](http://www.datasketch.es/august/code/nadieh/). In this talk I'd like to take you through the process of data gathering, sketching and coding; the lessons that I learned along the way and how a simple sketch of a feather shape turned into an interactive data visualization.

**Name:** Nadieh Bremer

**Twitter Handle (optional):** [@NadiehBremer](https://twitter.com/NadiehBremer)

**Website (optional):** [VisualCinnamon.com](http://www.visualcinnamon.com/)

**Months Available to Speak:** I'll only be in NY during April

**Comment by kosamari** [comment]
I'm SO excited to have you at BrooklynJS !
