### ISSUE TITLE
"Hacking" Twitch with JavaScript

### ISSUE THREAD

**Issue by noopkat** [brooklynjs/brooklynjs.github.io#373]
## BrooklynJS Talk Submission

**Talk Title:**  
"Hacking" Twitch with JavaScript

**Talk Description:**
[Twitch](https://twitch.tv) is a great place for people to watch others play games, cook food, draw, code, and much more. Some viewers are passive, but most are excited to interact with the person running the channel they're watching. Using the in-channel chat box is a great way to converse with your favourite Twitch creator, however this can sometimes feel limited and the response is often delayed. 

Since Twitch chat is run by IRC, we can use NodeJS to listen in the right room and do some really fun things with just a little bit of imagination. In this talk, I'll share my experiences with creating highly entertaining Twitch chat bots that augment the audience's interactions into something much more fun. Expect some laughter, a little bit of hardware, and some fuzzy feelings abound. You'll walk away inspired to explore beyond the face value of the interfaces you are familiar with.

**Name**:  
Suz Hinton

**Twitter Handle (optional)**:  
[@noopkat](https://twitter.com/noopkat)

**Website (optional):**  
[noopkat.com](http://noopkat.com)

**Months Available to Speak:**  
June, July, August would be lovely if you think my talk would be suitable 🤗

**Comment by willmanduffy** [comment]
You spoke last May so I think we'd start considering this talk in May! (I am so exciteddddd).

**Comment by hzoo** [comment]
👍  really exciting! (I made https://github.com/hzoo/TwitchPlaysX when Twitch Plays Pokemon was popular)

**Comment by noopkat** [comment]
@willmanduffy all the more time for me to squeeze in more experiments, hehe. Thanks for considering me 🙇‍♀️ 

@hzoo omg I am going to check this out thank you for sharing!!

**Comment by hzoo** [comment]
Not to get offtopic too much.. 😛

@noopkat haha it's probably broken/not working right now but it was fun plugging in the TPP data into my own game (how I made the GIF), and also made https://github.com/hzoo/tppstats

**Comment by willmanduffy** [comment]
@noopkat are you no longer available in May? Just saw you edited the PR.

**Comment by noopkat** [comment]
@willmanduffy that's correct, thanks!

**Comment by kosamari** [comment]
💯
