### ISSUE TITLE
I'd like to talk

### ISSUE THREAD

**Issue by ofZach** [brooklynjs/brooklynjs.github.io#374]
## BrooklynJS Talk Submission

**Talk Title:**

poetic computation w/ javascript

**Talk Description:**

I will talk about two recent art projects -- an online experiment for exploring geography (https://lines.chromeexperiments.com/) and an interactive public art installation for seeing your face in new ways -- that use JS under the hood.     I am pretty new to javascript so I will talk about what I learned along the way and share some of the tools I found helpful.   

**Name**:

Zach Lieberman

**Twitter Handle (optional)**:

zachlieberman
https://twitter.com/zachlieberman

**Website (optional):**

http://sfpc.io 
https://www.instagram.com/zach.lieberman/

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!

March is good -- later on (may or later) is OK too!

**Comment by kosamari** [comment]
REALLY EXCITED 🎉
