### ISSUE TITLE
Biohacking, Cyberpunk & You :  The Future is Now

### ISSUE THREAD

**Issue by rachelnicole** [brooklynjs/brooklynjs.github.io#375]
## BrooklynJS Talk Submission

Biohacking, Cyberpunk & You :  The Future is Now

This talk goes over embedded (in you!) hardware, talks about some rad cyberpunk stuff, and then goes over Augmented Reality with JavaScript

Rachel White

ohhoe

http://rachelisaweso.me

MARCH / APRIL

**Comment by kosamari** [comment]
💯
