### ISSUE TITLE
Snapshot Everything

### ISSUE THREAD

**Issue by jasonrhodes** [brooklynjs/brooklynjs.github.io#376]
## BrooklynJS Talk Submission

**Talk Title:**
Snapshot Tests are Your Friend (or something)

**Talk Description:**
Snapshot testing was made recently popular by Jest, the React-friendly test tool. But hey guess what it's not just for React. Let's build a simple snapshotter so I can show you what it is, how it's different than other tests, and why it's PERFECT for functionally testing your API responses, no matter what language you use. 

**Name**:
Jason Rhodes

**Twitter Handle (optional)**:
@rhodesjason

**Website (optional):**

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
April 2017 (best if possible)
May 2017

**Comment by willmanduffy** [comment]
Heyyyy I've been talking to Sparkpost folks about sponsoring April which would disqualify you from talk selection. Any chance May is alright for you? Sorry 😱

**Comment by hzoo** [comment]
👍 Snapshots are cool! We have our own snapshot system to test Babel (by snapshotting the compiled output)

**Comment by jasonrhodes** [comment]
Oh right @willmanduffy yeah I'm basically available for almost any month. :)

**Comment by paladique** [comment]
👋  @jasonrhodes looking forward to hearing your talk! 🎉  Let me know if you're still on for next Thursday and if the email in your GitHub profile is a good spot to send additional info and tickets!

**Comment by jasonrhodes** [comment]
Oh! Ok cool, yeah that email is good, thanks.
