### ISSUE TITLE
All I Really Need to Know About Minimalism I Learned from Tiny House Hunters!

### ISSUE THREAD

**Issue by modernserf** [brooklynjs/brooklynjs.github.io#377]
## BrooklynJS Talk Submission

**Talk Title:**
All I Really Need to Know About Minimalism I Learned from Tiny House Hunters!

**Talk Description:**

Many programmers consider "minimalism" to be a virtue, but few can agree on exactly what it means; should we strive for code that's simple, elegant, or efficient to compute? In this talk I'll discuss my attempts to reconcile these definitions, and how Tiny House Hunters helped me put it all together.

**Name**:
Justin Falcone

**Twitter Handle (optional)**:
@modernserf

**Website (optional):**
https://justinfalcone.com/

**Months Available to Speak:**
Mar / Apr / May

**Comment by willmanduffy** [comment]
Hey @modernserf. Looks like you gave a talk last August and we have a 1 year cool down period on folks giving talks at BrooklynJS to make sure everyone has a fair chance. I'm happy to either keep this open until August or if you think you'd want to talk about something else by then you can always just close this and re-submit when the time comes!

**Comment by modernserf** [comment]
👍 i'll submit something new in the fall
