### ISSUE TITLE
CSS styling with React/Redux

### ISSUE THREAD

**Issue by entcheva** [brooklynjs/brooklynjs.github.io#378]
## BrooklynJS Talk Submission

**Talk Title:**
CSS styling with React/Redux

**Talk Description:**
CSS styling with React is a hot mess. Let’s discuss! OOCSS vs. BEM vs. inline CSS vs. React styled-components etc.

**Name**:
Christina Entcheva

**Twitter Handle (optional)**:
@christinaent

**Website (optional):**
http://christinaentcheva.com/

**Months Available to Speak:** 
March / April / May

**Comment by kosamari** [comment]
👏 really looking forward to the talk!
