### ISSUE TITLE
Hybrid Static: Making Static Websites Dynamic

### ISSUE THREAD

**Issue by jescalan** [brooklynjs/brooklynjs.github.io#379]
## BrooklynJS Talk Submission

**Talk Title:** Hybrid Static: Making Static Websites Dynamic

**Talk Description:**

As javascript gets better, the number of devices we use multiplies, and speed becomes more important, many companies are moving towards splitting their APIs off from their front ends. As a result, a variety of new architecture styles have emerged to attempt to tackle this new pattern, from entirely static pages to heavy client side apps to isomorphic single page app rendering.

I work at an agency and have had the opportunity to experiment with a number of them across different projects, and have landed on a pattern we call "hybrid static" as the most efficient and least confusing. In this pattern, data and templates are shared between compile time and runtime, so you can decide which parts of the app are rendered as static pages or sections, and which parts are rendered dynamically at runtime. For example, if you were building a blog, you might render the first 10 posts on the first page as static html, then dynamically load the next 10 from the same API into the same template using javascript on the client side if the user goes to the next page. Webhooks allow dynamic rebuilds if data changes in the API so that static pages are always up to date.

The talk would discuss this pattern in depth as well as how it can be achieved using [Spike](https://github.com/static-dev/spike), an extension of webpack 2 made specifically for advanced static site generation.

**Name**: Jeff Escalante

**Twitter Handle (optional)**: [@jescalan](https://twitter.com/jescalan)

**Website (optional):** http://jeffescalante.com

**Months Available to Speak:** April, May, June, July

**Comment by kosamari** [comment]
Hey ya @jescalan. We unfortunately filled up all the speaking slots for April 😢 we'll keep this issue up for future month if that's cool with you :)
Let me know if you want 1st dibs on April ticket (talk submitters gets 1st dibs on ticket once) contact email is on my profile :)

**Comment by jescalan** [comment]
Yeah, that's cool! Any month listed works for me 😁

**Comment by kosamari** [comment]
🎉 details of venue and ticket on your way soon via email!

**Comment by jescalan** [comment]
🎉 🌮 🙌
