### ISSUE TITLE
WebAssembly: A New Frontier

### ISSUE THREAD

**Issue by fj** [brooklynjs/brooklynjs.github.io#380]
## BrooklynJS Talk Submission

**Talk Title:**

WebAssembly: A New Frontier

**Talk Description:**

WebAssembly is a way to run code on the web that's not JavaScript, so that your existing and future JavaScript code can be better. For example, maybe you're a bank who has a lot of C# or Java code you've worked hard on to calculate mortgage rates, and you want to make that available to developers who are writing JS. Now you can -- effectively, efficiently, and compactly!

In this talk, we'll discuss what WebAssembly is, how it works, and how it can team up with your JS to make your applications much more powerful.

**Name**: John Feminella

**Twitter Handle (optional)**: [@jxxf](https://twitter.com/jxxf)

**Website (optional):** http://jxf.me

**Months Available to Speak:** 2017-05 (90% certainty), 2017-07 (90% certainty)

**Comment by kosamari** [comment]
Hey ya! thanks for the talk submission :) We just announced our March speakers but would love to keep this open for the future months !

**Comment by fj** [comment]
Of course; thanks for keeping me in mind. Would you mind adding April and removing June? It turns out I'll likely be speaking at another conference then.

**Comment by kosamari** [comment]
👍

**Comment by fj** [comment]
Sorry for another change, but I just accepted an invitation to speak in Portland in April. However, a slot has opened up for May. Could you update the labels accordingly? Thank you!

**Comment by paladique** [comment]
@fj your talk has been accepted for this month! Let me know if you're still available next Thursday, and if the email in your GitHub profile is a good spot to send additional info and tickets!

**Comment by willmanduffy** [comment]
You've been accepted agaaaain! Wowzers. We'll be reaching out with details soon!
