### ISSUE TITLE
How To Win Friends & Influence Javascript Opinions

### ISSUE THREAD

**Issue by patriciarealini** [brooklynjs/brooklynjs.github.io#381]
## BrooklynJS Talk Submission

**Talk Title:**

How To Win Friends & Influence Javascript Opinions

**Talk Description:**

Tabs versus spaces. Engineer versus developer. Emacs versus vim. For an industry that prides itself on rapid innovation, we sure do spend a lot of time talking about the same things over and over again. When it's on twitter it can be muted, but when it happens in the office it blocks us from getting actual work done. If only we had a framework for making decisions based on the science of evidence and argument. Introducing, Speech Forensics! In this talk we will learn communication & debate skills so that the next time someone picks a fight with you over semicolons, you'll be able to have a constructive debate and come to a conclusion based on the mathematics of logic. 

**Name**:

Patricia Realini

**Twitter Handle (optional)**:

[@patriciarealini](twitter.com/patriciarealini)

**Website (optional):**

patriciarealini.com

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!

I would love to speak in May. But if i am not selected to speak at DinosaurJS I can give this talk in June.

**Comment by patriciarealini** [comment]
things have been really hard for me lately and i don't think i can put this together right now.

**Comment by willmanduffy** [comment]
<3

**Comment by paladique** [comment]
@patriciarealini thanks for coming to speak! I'll send over speaker info soon.

**Comment by patriciarealini** [comment]
@paladique 😂 it's all good. issue updated 👍 .
