### ISSUE TITLE
I've got a talk about Streetmix

### ISSUE THREAD

**Issue by louh** [brooklynjs/brooklynjs.github.io#382]
## BrooklynJS Talk Submission

**Talk Title:** Streetmix: the BrooklynJS talk

**Talk Description:** In 2013 an urban designer started a civic tech project that changed the face of urban planning forever. 3.5 years later we are still a scrappy open source project, but we built it in Node.js and JavaScript back when no one believed it could do what we're doing with it. Sure, we might have launched with a single 10,000+ line JS file instead of a module bundler and we're still on MongoDB, but in the past year we've migrated large parts of it to ES2015 and React/Redux, and maybe we will switch to PostgreSQL? Who knows? Despite JavaScript hijinks, it turns out a ton of urban planners and local bike/pedestrian mobility advocates depend on us to create change in their community. And I'm still not being paid to do any of this. Listen to me rant about that for 10 minutes.

**Name**: Lou Huang

**Twitter Handle (optional)**: saikofish

**Website (optional):** https://streetmix.net/

**Months Available to Speak:** April, May(?), June, July, etc

**Comment by kosamari** [comment]
W00t! yay civic tech ! looking forward to having you talk :)

**Comment by louh** [comment]
@kosamari What's the preferred aspect ratio for slides?

**Comment by willmanduffy** [comment]
Hey @louh our screen is 4:3. Due to the layout of the room the bottom 1/3 is hard for anyone outside of the front row to see also
