### ISSUE TITLE
Interventions (internet and otherwise)

### ISSUE THREAD

**Issue by chjno** [brooklynjs/brooklynjs.github.io#383]
## BrooklynJS Talk Submission

**Talk Title:**
Interventions (internet and otherwise)

**Talk Description:**
As someone who can’t stand modern technology and can’t stop using it, I decided to be the change I wanted to see in the world. By creating technology that is flawed/useless/regressive/frustrating/etc, I attempt to create unexpected experiences that resist the homogenization of tech and the hegemony of the screen.

This talk will cover a few of my recent physical and digital interventions and how JavaScript and I came to be.

**Name**:
Chino Kim

**Twitter Handle (optional)**:
@chjno_

**Website (optional):**
http://chino.kim

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
April

**Comment by kosamari** [comment]
Thanks for the submission ! looking forward to having you at BrooklynJS !
