### ISSUE TITLE
Node v. Element

### ISSUE THREAD

**Issue by seejohnrun** [brooklynjs/brooklynjs.github.io#384]
## BrooklynJS Talk Submission

**Talk Title:** Node v. Element

**Talk Description:**

As JS developers, we tend to use the terms "node" and "element" fairly interchangeably.  These are different things though (hint: one is a type of the other) and they both are accessible to you.  I'll dig into why these both exist, the fun (unexpected) ways they differ, and how the things we do in our day to day work can actually be really confusing when we look closer at them!

**Name**: John Crepezzi

**Twitter Handle (optional)**: [@seejohnrun](https://twitter.com/seejohnrun)

**Website (optional):** http://seejohncode.com

**Months Available to Speak:** April (4), May (5), July (7)

**Comment by kosamari** [comment]
@seejohnrun !!! unfortunately we filled up talk slots for April 😢 We'll keep this issue up for future months if that's cool with you !
Let me know if you want 1st dibs on April ticket (talk submitters gets 1st dibs on ticket once) contact email is on my profile :)

**Comment by seejohnrun** [comment]
all good thanks @kosamari !

**Comment by paladique** [comment]
Closing since GitHub is sponsoring for a bit!
