### ISSUE TITLE
React-Charts: Declarative & deterministic data visualizations for React

### ISSUE THREAD

**Issue by tannerlinsley** [brooklynjs/brooklynjs.github.io#385]
## BrooklynJS Talk Submission

**Talk Title:**
React-Charts: Declarative & deterministic data visualizations for React

**Talk Description:**
When I wrote Chart.js v2, I learned a lot of what people expect and need in a charting library.  But when attempting to achieve the same great usability in the React ecosystem, I noticed a massive whole in my heart that Chart.js could no longer completely fill.  I needed a charting library that works as easily as Chart.js (and looks just as great) but lets me take advantage of React's awesome power of composition, performance, and lifecycle. React-Charts is a data visualization library that embodies the spirit of Chart.js in a way that will make react developers swoon and sing praises to the visualization gods.

I plan on releasing the library live on stage, along with presenting its capabilities and how it stacks up to the competition (objectively of course).  I am also the creator/maintainer of Jumpsuit, React-Table, and React-Form, and still help maintain Chart.js, so I would hopefully be able to instill some learned wisdom from the open source realm and what it takes to build/contribute-to an open source library (and how rewarding it can be)

**Name**:
Tanner Linsley

**Twitter Handle (optional)**:
tannerlinsley (also my github handle)

**Website (optional):**
The react-storybook that I'm using to build the library is at react-charts.js.org.  Bear in mind this library is under construction, so let me know if you experience any problems or disappointments :( I will fix them immediately (yes, even your disappointments ;) )

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
I would love to speak at your upcoming BrookThursday, April 20th.

**Comment by tannerlinsley** [comment]
Pending personal scheduling.  Will reopen with more info asap

**Comment by tannerlinsley** [comment]
K, I'm good.  Just needed to make sure I was good to travel.

**Comment by kosamari** [comment]
Hey @tannerlinsley Sorry we filled up April speaking slots 😭. Ping me over email (address on my profile) if you like a 1st dibs tickets.
