### ISSUE TITLE
Envious - run local code in real environments

### ISSUE THREAD

**Issue by justinjmoses** [brooklynjs/brooklynjs.github.io#386]
## BrooklynJS Talk Submission

**Talk Title:**
Envious - run local code in real environments

**Talk Description:**
We have a problem. Data. Reproducing bugs that simulate complex data requirements - such as degraded performance - can take a lot of wasted time. One workaround is `chrome-envious`, a Chrome Extension we wrote to swap out live URL requests in a running site, allowing a developer to run their local assets against a deployed environment. 

**Name**:
Justin J Moses

**Twitter Handle (optional)**:
@justinjmoses

**Website (optional):**

**Months Available to Speak:** 
Apr 2017, May 2017, June 2017

**Comment by kosamari** [comment]
hey ya @justinjmoses  unfortunately we filled up April speaking slots 😭  we'll keep this issue up for May and June if that's cool.

Let me know if you want 1st dibs on April ticket (talk submitters gets 1st dibs on ticket once) contact email is on my profile :)

**Comment by justinjmoses** [comment]
Sure you can keep it open for the next two months.

**Comment by justinjmoses** [comment]
Will you reopen this issue?

**Comment by kosamari** [comment]
oops ! sorry about that !! reopened :)
