### ISSUE TITLE
Web Notifications Are Pretty Cool

### ISSUE THREAD

**Issue by alastaircoote** [brooklynjs/brooklynjs.github.io#387]
## BrooklynJS Talk Submission

**Talk Title:**
Web Notifications Are Pretty Cool

**Talk Description:**
As a web developer, I was always jealous of the fact that native apps could send beautiful, actionable push notifications and I couldn't. But not any more! Chrome (on both desktop and Android) can receive push messages and display notifications, no matter if the original page is open or not.

We'll go through the Push API, the Notifications API, and how we can add interactivity though tags, notification click events and notification action buttons.

**Name**:
Alastair Coote

**Twitter Handle (optional)**:
_alastair

**Website (optional):**

**Months Available to Speak:** April, June, July

**Comment by kosamari** [comment]
👍✨ looooooking forward to the talk !
