### ISSUE TITLE
Programming for Math, Science, and Fun with regl

### ISSUE THREAD

**Issue by rreusser** [brooklynjs/brooklynjs.github.io#388]
## BrooklynJS Talk Submission

**Talk Title:** Programming for Math, Science, and Fun with regl

**Talk Description:** Written by [@mikolalysenko](https://github.com/mikolalysenko), [regl](https://github.com/regl-project/regl) is a functional wrapper for the WebGL API that's effectively rewired the way I think about drawing graphics. I use it for fun and work, so I'll talk about how I've come to realize the scope of the API hits the nail on the head and why removing state makes small experiments enjoyable and large projects maintainable. And of course I'll show off some fancy things people have done with it.

I've never given a programming talk, so I'd love the opportunity to talk briefly about regl and try to pass on some great lessons I've learned from its design! Thanks for your consideration!

**Name**: Ricky Reusser

**Twitter Handle (optional)**: [@rickyreusser](https://mobile.twitter.com/rickyreusser)

**Website (optional):**
- regl: http://regl.party/
- My experiments: https://github.com/rreusser/demos#regl

**Months Available to Speak:** April, June (July not strictly impossible, but not the best)

**Comment by rreusser** [comment]
Edit: I've been discussing with a couple people who have done live coding talks with regl. I'd ruled it out due to the ten minute format, but based on their experience, it sounds like it would be a good fit for the format and has been pretty engaging for technical and non-technical audiences.

So a small amendment to the above would be to shift the focus toward a live demo rather than something heady like lessons learned. 😄

**Comment by kosamari** [comment]
hey ya @rreusser we've filled up April speaking slots 😢 we'll keep this issue up for June if that's cool with ya ! 

Let me know if you want 1st dibs on April ticket (talk submitters gets 1st dibs on ticket once) contact email is on my profile :)

**Comment by rreusser** [comment]
Cool, thanks!

**Comment by kosamari** [comment]
Yay really looking forward to your talk! info about venue and ticket on your way via ✉️

**Comment by rreusser** [comment]
@kosamari So sorry, but I think I'll have to withdraw due to scheduling. It looks like I'll miss the June meetup by one day as we start to move, so I don't think I'll be able to defer it either. Thanks *soo* much and apologies. 😞

**Comment by kosamari** [comment]
@rreusser no worries ! thanks for talk submission ! :)
