### ISSUE TITLE
Scrape It 'Til Ya Make It: Taking UNIQLO Mobile

### ISSUE THREAD

**Issue by jed** [brooklynjs/brooklynjs.github.io#389]
## BrooklynJS Talk Submission

**Talk Title:**

Scrape It 'Til Ya Make It: Taking UNIQLO Mobile

**Talk Description:**

UNIQLO had just spent a ton of cash on its first e-commerce website in the US, but it had one serious flaw: half of its potential sales bounced because it was desktop-only. This is the true story of how two scrappy New York JavaScripters defied the odds to build an app that brought UNIQLO mobile.

**Name**:

Jed Schmidt / Michael Hart

**Twitter Handle (optional)**:

@jedschmidt / @hichaelmart

**Months Available to Speak:**

May

**Comment by willmanduffy** [comment]
We would have been more likely to accept a joint talk on our 4/20 event yesterday.

**Comment by kosamari** [comment]
can you fit in 10 min tho? @jed's track record is not great 😁

**Comment by jed** [comment]
no worries, @kosamari. @mhart will be the one presenting, i'm just interpreting his 🇦🇺 to 🇺🇸.

**Comment by paladique** [comment]
Happy to have y'all here for May. ❤️

**Comment by mhart** [comment]
@jed why you fool them so? I'm gonna be in Australia next week y'all!

Will help him out with the preso though 👍
