### ISSUE TITLE
I said building a bot would be easy ( 🙈 )

### ISSUE THREAD

**Issue by clintonhalpin** [brooklynjs/brooklynjs.github.io#390]
## BrooklynJS Talk Submission

**Talk Title:**
I said building a bot would be easy ( 🙈  )

**Talk Description:**
Everyone is excited about bot's and text based interfaces. As with any new technology the eco-system is changing rapidly and documentation isn't great.

To make matters worse, most providers and libraries give examples of bot's ordering Pizza or telling team members the weather. The point of my talk is to walk through a real use case and how I shipped a Slack bot into production. As well as give some background about the different providers I tested [BotKit](https://github.com/howdyai/botkit), [Api.ai](api.ai).

I had a few weeks of real pain and suffering so hopefully after this talk people can honestly say building a bot is easy!

**Name**:
- Clinton Halpin

**Twitter Handle (optional)**:
- https://twitter.com/clintonhalpin

**Website (optional):**
- Personal - http://clintonhalpin.com/
- Company - https://quotecatalog.com

**Months Available to Speak:** 
- May, June, July ( whenever honestly )

**Comment by kosamari** [comment]
we run out of speaker slot for June 😢 
ping me on email (email in my profile) if you like to get reserved ticket for this months :D

**Comment by willmanduffy** [comment]
You're in! We'll be reaching out to you in the next few days to get some details over to you!

**Comment by clintonhalpin** [comment]
Rad @willmanduffy !
