### ISSUE TITLE
Who needs Javascript? How to Build an Entire App in WebGL

### ISSUE THREAD

**Issue by sethsamuel** [brooklynjs/brooklynjs.github.io#391]
## BrooklynJS Talk Submission

**Talk Title:** Who needs Javascript? How to Build an Entire App in WebGL

**Talk Description:** WebGL is most often used solely as the view layer, especially for 3D visualizations, but with a little magic we can have it handle all of our application logic. You'll learn how to use framebuffers to store and update state, textures to pass in user input, and a traditional WebGL presentation layer to render the result at a smooth 60 frames per second.

**Name**: Seth Samuel

**Twitter Handle (optional)**: sethfsamuel

**Website (optional):** https://github.com/sethsamuel/

**Months Available to Speak:** May, maybe June, July

**Comment by paladique** [comment]
👋 @sethsamuel your talk has been accepted! Let me know if you're still available next Thursday and if the email in your GitHub profile is good for communication (tickets, logistics).

**Comment by sethsamuel** [comment]
🎊 Can definitely come talk next Thursday, and GitHub email's the right one.
