### ISSUE TITLE
CallParty - A civic engagement bot for Facebook Messenger

### ISSUE THREAD

**Issue by jayres** [brooklynjs/brooklynjs.github.io#392]
## BrooklynJS Talk Submission

**Talk Title:**
CallParty - A civic engagement bot for Facebook Messenger

**Talk Description:**
After the past election, a group of developers and designers got together to build a Facebook Messenger app to help connect constituents with their Members of Congress. After a few months of process and development, CallParty was born. 

Using JavaScript on both the client and server, CallParty provides users with their representative's information and a script to help them get their thoughts across.

The talk will cover how we integrated the government data into our platform and then into Facebook Messenger, using their API.

**Name**:
James Ayres

**Twitter Handle (optional)**:
@CallParty

**Website (optional):**
http://www.callparty.org

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
May, July, August...

**Comment by paladique** [comment]
👋 @jayres your talk has been accepted! 🎉 Let me know if you're still available next Thursday and if the email in your GitHub profile is good for communication (tickets, logistics).

**Comment by jayres** [comment]
Awesome! Thursday is great. My github email is fine for communication too.

Looking forward to it.
