### ISSUE TITLE
DIY Element Queries with ResizeObserver

### ISSUE THREAD

**Issue by eeeps** [brooklynjs/brooklynjs.github.io#393]
## BrooklynJS Talk Submission

**Talk Title:** DIY Element Queries with ResizeObserver

**Talk Description:** The concept of “element” or “container” queries has enjoyed universal support among front-end developers for years, but a standard solution hasn’t even been spec’d yet, never mind implemented in browsers. There are good reasons for that, which we’ll explore first-hand by rolling up our sleeves and attempting to be the Extensible Web Manifesto that we want to see in the world – with [ResizeObserver](https://wicg.github.io/ResizeObserver/).

**Name**: Eric Portis

**Twitter Handle (optional)**: @etportis

**Website (optional):** https://ericportis.com

**Months Available to Speak:** I’m going to be in town in June, [talking about Element/Container Queries @ SmashingConf](https://smashingconf.com/schedule). I’d *love* to speak at BrooklynJS a couple of days later!

**Comment by kosamari** [comment]
Hey ya @eeeps we filled all speaker slits for June.
Please shoot me an email (address in my profile) if you like to get reserved ticket for talk submitter :)
