### ISSUE TITLE
Debugging Google-React-Maps for Beginners

### ISSUE THREAD

**Issue by gee2789** [brooklynjs/brooklynjs.github.io#394]
## BrooklynJS Talk Submission

**Talk Title:**
 Debugging Google-React-Maps:  Pitfalls and Struggles from a Beginner Coder

**Talk Description:**
 Coding is hard.  Even harder when you can't just search StackOverflow for an answer.  Here are a few issues that were incredibly small but ate up ridiculous amounts of time while working with the google-react-maps and react-bootstrap.

1. Size Matters:  The div box needs to be greater than 0.  This is great, unless you're using react-bootstrap.  Then you've got flex containers that are 0 because it's waiting on google-react-maps, which is waiting for react-bootstrap, which is waiting for . . . . .

2. Custom Icons and SVG attributes:  google-react-maps is great for more customization.  Unfortunately, there's a large learning curve to get to that point.  Here I figured out how to use custom SVG icons and pass them into the component.  We'll also look at some attributes of SVG that allow you to customize size, offsets, and more.

**Name**:
Gee Li

**Twitter Handle (optional)**:
twitter: @Gee2789

**Website (optional):**

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!

Available May, July, August

**Comment by paladique** [comment]
👋 @gee2789 Thank you for your submission! Your talk didn't make it in this month, but we have a reserved ticket waiting for you!  Email me at jasmine@brooklynjs.com for details

**Comment by kosamari** [comment]
Hey ya @gee2789 Sorry we run out of speaker spot this month. 

Can we ask few more thing about your talk? We tend to accept talks that are about what you did & learned, than how to use [a library/framework/things] or what  [a library/framework/things] is.
Maybe you could spin the talk about what you made with google-react-maps and react-bootstrap ?
 
Happy to discuss on the email if you prefer private channel.

**Comment by gee2789** [comment]
Howdy Mariko,

No problem at all. I'm always open to suggestions about how to contribute to the community. Let me rethink my talk and restructure with your suggestions for the following months. 

I wasn't able to snag a ticket today and wanted to ask if I still qualify for a reserved ticket. No worries if not, I'll try again at the next ticket release. Thanks!

Best
Gee Li

**Comment by kosamari** [comment]
Hey ya - closing this submission for now ! thanks for submitting talk idea!
