### ISSUE TITLE
B-arrow-ed: Hindley-Milner type signatures adapted for JavaScript

### ISSUE THREAD

**Issue by maxhallinan** [brooklynjs/brooklynjs.github.io#396]
## BrooklynJS Talk Submission

**Talk Title:** B-arrow-ed: Hindley-Milner type signatures adapted for JavaScript

**Talk Description:** 

Hindley-Milner type signatures are easy to write and easy to read. Unfortunately, it can be hard to find a simple introduction to the Hindley-Milner system. Much writing on the topic ([1](https://en.wikipedia.org/wiki/Hindley%E2%80%93Milner_type_system), [2](http://stackoverflow.com/questions/399312/what-is-hindley-milner#answer-399392)) invokes academic concepts that obscure the system's essential practicality. 

My talk has three parts. First, I argue that Hindley-Milner is an exceptionally efficient means of documentation by comparing the type signature for the identity function to four different plain English explanations. Then, I introduce the audience to the Hindley-Milner syntax by writing type signatures for familiar functions such as `concat`, `filter`, `map`, `partial` and `reduce`. Finally, I talk about ways in which Hindley-Miner doesn't fit JavaScript perfectly and review some of the [solutions proposed](https://github.com/ramda/ramda/wiki/Type-Signatures#ramda-miscellany) by the [Ramda](http://ramdajs.com/) team. 

I aim to leave the audience able to read Hindley-Milner type signatures and perhaps persuaded that this system provides a lightweight compliment to more comprehensive documentation systems such as JSDoc.

**Name**: Max Hallinan

**~~Twitter~~ Mastodon Handle (optional)**: https://oulipo.social/@maxhallinan

**Website (optional):** https://github.com/maxhallinan

**Months Available to Speak:** June, July 2017

**Comment by kosamari** [comment]
Hey ya - unfortunately all of our June speaker slots are filled 😢 Let me know (email address in my profile) if you like to get reserved ticket for talk submitter this month.

**Comment by kosamari** [comment]
run out of speaker spots again 😭 Thank you very much for your talk submission!
