### ISSUE TITLE
The Sound of Data

### ISSUE THREAD

**Issue by justinjmoses** [brooklynjs/brooklynjs.github.io#397]
## BrooklynJS Talk Submission

**Talk Title:**
The Sound of Data

**Talk Description:**
What does my data sound like? A lighthearted exploration of musical composition through the humble JS object. 

**Name**:
Justin Moses

**Twitter Handle (optional)**:
@justinjmoses

**Months Available to Speak:** 
June, July 2017

**Comment by kosamari** [comment]
Hey ya! thanks for talk submission! looking forward to this very much :)
Info about venue and ticket on your way via ✉️

**Comment by justinjmoses** [comment]
Great thanks. Please send to this username at Gmail. 

Question: can your setup handle USB-C (new Mbps) or should I bring a dongle?

**Comment by brianloveswords** [comment]
@justinjmoses thanks for asking! We just got a USB-C dongle last month so we'll be all set 👍

**Comment by justinjmoses** [comment]
Thanks @brianloveswords. @kosamari are you going to send an email to my gmail? I haven't received anything yet.
