### ISSUE TITLE
The Excitement and Terror of a Successful Side Project

### ISSUE THREAD

**Issue by ejb** [brooklynjs/brooklynjs.github.io#398]
## BrooklynJS Talk Submission

**Talk Title:** The Excitement and Terror of a Successful Side Project

**Talk Description:**

I launched oTranscribe.com in October 2013 while still getting to grips with JavaScript. Almost four years on, it has approximately 90,000 monthly users — and that number is growing every month by word of mouth alone. Meanwhile, I have an unrelated full-time job and still host it on GitHub Pages.

In this talk, I’ll discuss my unsuccessful attempt at rewriting oTranscribe from scratch, what I learnt in a (more successful) refactor, and more generally what it means to have your open-source project blow up beyond your wildest dreams.

**Name**: Elliot Bentley

**Twitter Handle (optional)**: https://twitter.com/elliot_bentley

**Months Available to Speak:** June, August, September 2017

**Comment by ejb** [comment]
Ps. Is this technical enough? My first draft was more focused on the refactor, but I thought emphasising the side project aspect was more interesting!

**Comment by paladique** [comment]
You're good! 👍  Thanks for your proposal, we'll be in touch as the next event draws near!

**Comment by kosamari** [comment]
🎉 thanks for submission :) 
✉️ with details coming to your way soon. Realy looking forward to it !
