### ISSUE TITLE
Using Serverless technologies to solve a first world problem

### ISSUE THREAD

**Issue by bdougie** [brooklynjs/brooklynjs.github.io#399]
## BrooklynJS Talk Submission

**Talk Title:**
Using Serverless technologies to solve first world problems

**Talk Description:**
With a modern web development approach is there even a need for servers? I answer that question by exploring the implementation of into my front end web app that lets me know if there is a baseball game and when to avoid public transit. I explain the benefits of my server-less project, which includes speed, cost, and security. By the end of this talk, you will have a good understanding to build a fast, secure front-end that talks to a low-cost server-less architecture. You will also find out if there is a baseball game the night of the talk as well 😉

**Name**:
Brian Douglas

**Twitter Handle (optional)**:
bdougieYO

**Website (optional):**
https://briandouglas.com

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
August or September

**Comment by kosamari** [comment]
we are out of space for this month 😭 
Ping me on email (address in my profile) if you like to get reserved ticket for talk submitter :)

**Comment by bdougie** [comment]
I was unavailable last minute to attend in June, I also updated my availability - I have a vacation in July and it will fall around the anticipated July date and don't get back until August 10th @kosamari. Any chance there is availability August or September :)

**Comment by willmanduffy** [comment]
Updated the labels!

**Comment by willmanduffy** [comment]
Thanks for submitting! Happy to say we've got a spot for you this month! @kosamari will be reaching out with details on speaking and getting your ticket soon!

**Comment by bdougie** [comment]
Sounds good
