### ISSUE TITLE
Approaching web standards scientifically

### ISSUE THREAD

**Issue by jakearchibald** [brooklynjs/brooklynjs.github.io#400]
## BrooklynJS Talk Submission

**Talk Title:** Approaching web standards scientifically

**Talk Description:** Looking at where science has gone wrong in the past, and how to avoid making the same mistakes on the web.

**Name**: Jake Archibald

**Twitter Handle (optional)**: jaffathecake

**Website (optional):** https://jakearchibald.com

**Months Available to Speak:** June

**Comment by kosamari** [comment]
🎉 info about venue/ticket etc on your way :)
