### ISSUE TITLE
Full CRUD Fast: Build APIs in Node in just 73 seconds!

### ISSUE THREAD

**Issue by joesepi** [brooklynjs/brooklynjs.github.io#402]
## BrooklynJS Talk Submission

**Talk Title:**
Full CRUD Fast: Build APIs in Node in just 73 seconds!

**Talk Description:**
Let's blast through some live coding and build out CRUD APIs in Node.js together. In moments, based on our data model, we can quickly have RESTful endpoints with all the verbs one could possibly need. That willman literally take me 73 seconds, as you'll see in the 1920s video below before they had audio. The rest of the time, we could hook up a legit datasource, slap in some ACLs, maybe even develop some relationships between our models. If there be hecklers, we'll _develop_ some relationships there too. It'll be fun!

[![Rapid APIs in LoopBack](https://raw.githubusercontent.com/StrongLoop-Evangelists/workshop-band-app/master/workshop/assets/video.png)](https://youtu.be/iOMD27DjuO4 "Rapid APIs in LoopBack")

**Name**:
Joe Sepi

**Twitter Handle (optional)**:
joe_sepi

**Website (optional):**
leastbestbeast.com

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
June. It's got to be June. It could probably be July or August or any other month, but I'd really really like for it to be June. June is great. June is good.

**Comment by kosamari** [comment]
We are out of speaker slots 😢 
Let me know via DM or email if you like to get firsties ticket 👍

**Comment by joesepi** [comment]
Hi @kosamari - I am interested in a ticket, please! Also, feel free to open this puppy back up and slap a July and/or August label on there. I'm around! Thank you!
