### ISSUE TITLE
Adventures with TypeScript

### ISSUE THREAD

**Issue by danvk** [brooklynjs/brooklynjs.github.io#403]
## BrooklynJS Talk Submission

**Talk Title:** Adventures with TypeScript

**Talk Description:** TypeScript is a typed superset of JavaScript maintained by Microsoft. It's gained hugely in popularity over the past 2-3 years, largely because Microsoft has taken a "Switzerland" approach to JS: they try to support all the frameworks and all the workflows. I'll talk about why you might want to use TypeScript, how to migrate a JavaScript project to TypeScript, and some exciting new features that have been added in the past year which help TS faithfully model JS code that was previously hard to statically type.

These posts I've written about TypeScript are along the lines of what I'll talk about:

- [A Typed pluck: exploring TypeScript 2.1’s mapped types][1] (Medium)
- [A typed chain: exploring the limits of TypeScript][2] (Medium)
- [Why and when to use TypeScript][3] (StackOverflow Documentation)

Seeing TypeScript in action is the most compelling argument for using it, so I hope to show lots of examples in vscode during my talk.

**Name**: Dan Vanderkam

**Twitter Handle (optional)**: [@danvdk](https://twitter.com/danvdk)

**Website (optional):** [danvk.org](http://www.danvk.org/)

**Months Available to Speak:** June, July or August

[1]: https://medium.com/@danvdk/a-typed-pluck-exploring-typescript-2-1s-mapped-types-c15f72bf4ca8
[2]: https://medium.com/@danvdk/a-typed-chain-exploring-the-limits-of-typescript-b50153be53d8
[3]: https://stackoverflow.com/documentation/typescript/9073/why-and-when-to-use-typescript#t=201705300307297446437

**Comment by kosamari** [comment]
Hey hey- we filled all of our speaker slots for this months 😭 
Shoot me an email (address in my profile) if you like to get reserved ticket for talk submitter :D

**Comment by danvk** [comment]
Hi @kosamari, I sent a message about the ticket but haven't heard back. Is it still possible to get one? Thanks.

**Comment by kosamari** [comment]
hey ya just sent you a link!  apologies for the delay 🙏

**Comment by willmanduffy** [comment]
You're in! Super excited for this as I'm just starting my own adventures in TypeScript! We'll be reaching out with details soon!
