### ISSUE TITLE
JavaScript and the Rise of The New Virtual Machine

### ISSUE THREAD

**Issue by shanselman** [brooklynjs/brooklynjs.github.io#404]
## BrooklynJS Talk Submission

**Talk Title:** JavaScript and the Rise of The New Virtual Machine

**Talk Description:** One day we woke up and things were different. Artificial Intelligence and Machine Learning powering swarms of cloud containers talking to browsers running apps originally written in C++, now compiled to JS. Augmented and Virtual Reality are happening in your browser! Join Scott Hanselman as he explores the relationship between the Cloud and the Browser, many Languages and one Language, how it might all fit together and what might come next in this upbeat and edutaining talk. How many animated gifs of Neil Patrick Harris can one man use in one technical talk? Let's find out!"

**Name**: Scott Hanselman

**Twitter Handle**: [@shanselman](https://twitter.com/shanselman)

**Website:** http://hanselman.com

**Months Available to Speak:** November 15th/16th

**Comment by paladique** [comment]
@shanselman Looking forward to having you in our lineup this month! Will be emailing speaker details+logistics soon.
