### ISSUE TITLE
Deploying your own application with modern container tools

### ISSUE THREAD

**Issue by GrantSeltzer** [brooklynjs/brooklynjs.github.io#407]
## BrooklynJS Talk Submission

**Talk Title:** Deploying your own application with modern container tools.

**Talk Description:** Deploying applications has never been easier and as a result more and more developers are doing it themselves. The rise of [containers](https://www.docker.com/what-container) have allowed developers of all stacks and skill levels to develop, ship, and deploy their apps without any worries about dependencies or environment specific requirements. In addition, container orchestration tools like [Kubernetes](https://kubernetes.io/) (the biggest buzzword in tech) have made it simple to scale and manage entire ecosystems. We'll go over what a container is and how to completely package your node application into one. After that i'll be doing a demonstration on running that container using Kubernetes! 

**Name**: Grant Seltzer

**Twitter Handle (optional)**: [@grantseltzer](https://twitter.com/grantseltzer)

**Months Available to Speak:** ~~July,~~ August

**Comment by GrantSeltzer** [comment]
@willmanduffy I think August would be a lot better for me, Can you remove the July label? Thanks!

**Comment by kosamari** [comment]
Hey ya - sorry we run out of slot for August 😢 
Please email me (email on my profile) if you like to get reserved ticket !

**Comment by GrantSeltzer** [comment]
@kosamari Can I do this in September instead then?
