### ISSUE TITLE
Flying the Feature Flag

### ISSUE THREAD

**Issue by dcousineau** [brooklynjs/brooklynjs.github.io#408]
## BrooklynJS Talk Submission

**Talk Title:** Flying the Feature Flag

**Talk Description:**
GONNA TALK ABOUT HOW I WAS WRONG TO HATE FEATURE FLAGS BACK IN THE DAY AND HOW THEY CAN DECOUPLE ROLLOUT FROM DEPLOYMENT.

**Name**: Daniel Cousineau

**Twitter Handle (optional)**: @dcousineau

**Website (optional):** http://dcousineau.sexy/

**Months Available to Speak:** July, August, September

**Comment by kosamari** [comment]
WE TEASE

**Comment by paladique** [comment]
👋 you've got any additional months coming up that you'd like to speak, @dcousineau?

**Comment by dcousineau** [comment]
I'm flexible! I'll get back about it though

**Comment by paladique** [comment]
Woo finally! Sending you a speaker email soon!
