### ISSUE TITLE
The cost of unmoderated collaboration

### ISSUE THREAD

**Issue by MylesBorins** [brooklynjs/brooklynjs.github.io#409]
## BrooklynJS Talk Submission

**Talk Title:**
The cost of unmoderated collaboration

**Talk Description:**

Hot off the tails of a successful presentation at dinosaur js this abridged version of "The cost of unmoderated collaboration" gets into the nitty gritty of why it is so important to have clear moderation rules in your community. It presents hard learned lessons from Node.js as well as some best practices for you to take home.

**Name**:

Myles Borins

**Twitter Handle (optional)**:

@mylesborins

**Website (optional):**

MylesBorins.com

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
July please!

**Comment by willmanduffy** [comment]
Unfortunately due to our "once a year" policy for speakers we wouldn't be able to accept this talk until December. As discussed I'll close this for now and we can see what's up then!
