### ISSUE TITLE
Disrupting the Developer Experience

### ISSUE THREAD

**Issue by thescientist13** [brooklynjs/brooklynjs.github.io#410]
## BrooklynJS Talk Submission

**Talk Title:**
Disrupting the Developer Experience

**Talk Description:**
Building applications in the "modern age" requires acknowledgement and acceptance of paradigm shifts in many facets of a company's operations, and while resources are focused on tooling and technology, one critical component — the developer experience —  is often overlooked. Failure to see digital transformation as organizational and cultural change often means the transformation itself fails, not to mention the impact it has on developer morale, engagement, productivity and ultimately retention. In this talk I will talk about cultivating a developer experience that values training, knowledge transfer, educational support and professional development to fuel digital transformation, yield better products and build stronger technical teams. 

**Name**:
Owen Buckley

**Twitter Handle (optional)**:
@kenzanmedia
@thegreenhouseio

**Website (optional):**
www.kenzan.com
www.thegreenhouseio.blog

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
August / September / October

**Comment by kosamari** [comment]
Hey ya - sorry we run out of spot for August ! 
Ping me if you can attend the event though ! (email on my profile) we have reserved ticket block for talk submitter :)

**Comment by paladique** [comment]
@thescientist13 Your talk has been accepted 🎉 Is the email on your profile a good spot to reach out to you for speaker specifics?

**Comment by thescientist13** [comment]
Hi @paladique !

Yes it is!  And thanks so much for being selected!  ☺️
