### ISSUE TITLE
The next wave of front-end frameworks

### ISSUE THREAD

**Issue by Rich-Harris** [brooklynjs/brooklynjs.github.io#411]
## BrooklynJS Talk Submission

**Talk Title:** The next wave of front-end frameworks

**Talk Description:** 🚨  NEW PROJECT KLAXON 🚨 I've been working for the last few months on a project called [Svelte](https://svelte.technology) ( <sub>adj</sub> /svɛlt/ — *lithe, urbane, suave, from the Italian 'svelto' meaning fast, agile, light*), which is an attempt to rethink how we approach the problem of building user interfaces.

We've gone from a world where people manually manipulate the DOM (imperative) to one where we describe the intended output (declarative), and our tool of choice translates that into a series of DOM updates. That's great for developer happiness but there are some significant trade-offs. Svelte changes all that by compiling your declarative components into JavaScript that resembles the targeted DOM manipulation code you'd write yourself — in other words, doing the hard work once at build time instead of *n* times at run time.

There's loads of different aspects I could focus on:

* your app gets much smaller, because you no longer need to ship a virtual DOM differ/data binding system/virtual machine/whatever
* your app gets much *faster*, because the compiler can aggressively optimize — no need to do complex diffing operations etc
* your app is easier on the garbage collector, because you're not generating a new copy of your entire view on every state change. Svelte uses less memory than any other framework, which is great for mobile
* your codebase is regret-proof — because there's no real runtime framework to speak of, you never have to worry about shipping two frameworks simultaneously if you decide to adopt a new tool in future
* because components are self-contained, it completely changes the game when it comes to interoperability. Web components finally make sense!
* SSR is a crazy amount faster — you just tell the compiler to output a string-generating function instead of a DOM-generating one
* the developer experience is beautiful. For example you can write normal CSS and it will be encapsulated/statically analysed etc
* simplicity/minimalism versus power/features is revealed to be a false dichotomy

**Name**: Rich Harris

**Twitter Handle (optional)**: [@rich_harris](https://twitter.com/rich_harris)

**Website (optional):** [svelte.technology](https://svelte.technology)

**Months Available to Speak:** July, August, September

**Comment by hzoo** [comment]
nice I should apply to speak when you go 😄

**Comment by willmanduffy** [comment]
Hey Rich! Welcome back! You're in! We'll be reaching out with details soon.

**Comment by Rich-Harris** [comment]
wooo! thanks @willmanduffy
