### ISSUE TITLE
50 Shades of React

### ISSUE THREAD

**Issue by danrouse** [brooklynjs/brooklynjs.github.io#412]
**Talk Title:** 50 Shades of React

**Talk Description:** In Javascript, especially the land of React, there are plenty of wrong ways to do, well, anything. But many times, there's not one "right way" to go about doing it... it's all shades of gray. I'll talk about a few common cases of analysis paralysis and how to get over it.

**Name**: Dan Rouse

**Months Available to Speak:** august september october november whenember  🤷‍♂️

**Comment by kosamari** [comment]
we run out of speaker slot for this month 😢
Please message me (email on my profile) if you like to attend the event. we have reserved ticket for talk submitters.

**Comment by paladique** [comment]
Hi @danrouse 👋  this proposal hasn't been selected for the proposed months' lineups, so this issue will be closed. Feel free to submit a new proposal. We're available at organizers@brooklynjs.com for questions and feedback. Thank you so much for your submission!
