### ISSUE TITLE
Talk Submission: SPREADSHEETS ZOMG

### ISSUE THREAD

**Issue by jlord** [brooklynjs/brooklynjs.github.io#413]
## BrooklynJS Talk Submission

**Talk Title:** SPREADSHEETS ZOMG

**Talk Description:** Remember spreadsheets? They're awesome! In this talk we'll go over tools and ways to use spreadsheets for good and for giggles.

**Name**: Jessica Lord

**Twitter Handle (optional)**: jllord

**Website (optional):** http://jlord.us

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time! July, August, September

**Comment by willmanduffy** [comment]
Oh sheet! You're in! We'll be reaching out to you in the next few days to get some details over to you!
