### ISSUE TITLE
how what I learned study-hacking college helps me overcome javascript fatigue

### ISSUE THREAD

**Issue by greg-samek** [brooklynjs/brooklynjs.github.io#414]
## BrooklynJS Talk Submission

**Talk Title:** how what I learned study-hacking college helps me overcome javascript fatigue: tools and techniques to learn smarter

**Talk Description:** This past December, I decided to take my remaining vacation days (5) and see if I could learn enough react native to be reasonably productive in that time. Since then, using what I learned, I've been able to give two talks on React Native and to be pretty productive on a React Native side project. In this talk, I want to talk about learning, and how to learn, by demonstrating some of the techniques I used. I've used the same ones for almost every new framework I've come across in JS. These include:

- deep work (how do you change your environment and your habits to maximize for success)
- mind map (use this tool to test what you know to begin with, and make your learning easier by starting at the edges of your current understanding -- includes graphical diagrams)
- finding the best resources
- take better notes and organize your thoughts when you discover these resources
- using spaced repetition and koans to practice concepts
- picking a sample project
- ??
- profit

**Name**: Greg Samek

**Twitter Handle (optional)**: https://twitter.com/spacemanmd. 2 points if you can spot the 30 Rock reference.

**Website (optional):** 

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time! 

August, September, October

**Comment by kosamari** [comment]
Hey ya- sorry we are out of space for August !
Please massage me if you'd like to attend :) we have reserved ticket for talk submitter !

**Comment by greg-samek** [comment]
I'd love one! My email is gregory.samek@gmail.com

**Comment by paladique** [comment]
Hi @greg-samek 👋  this proposal hasn't been selected for the proposed months' lineups, so this issue will be closed. Feel free to submit a new proposal. We're available at organizers@brooklynjs.com for questions and feedback. Thank you so much for your submission!
