### ISSUE TITLE
Talk Submission: Vimsical - Process to the People

### ISSUE THREAD

**Issue by den1k** [brooklynjs/brooklynjs.github.io#415]
## BrooklynJS Talk Submission

**Talk Title:**
Vimsical - Process to the People

**Talk Description:**
We asked _What if everything was a tutorial?_ How much more could we learn if the knowledge of how we make things was just a click away? That's Vimsical. A highly granular process control system that integrates with your tools and automatically records your process, and a platform to share not just the result of your work, but the journey that led up to it.

We wrote the entire app in 3 months, as a team of 2 people, in Clojure(-Script).

**Name**: Dennis Heihoff

**Twitter Handle (optional)**: @denik

**Website (optional):** vimsical.com

**Months Available to Speak:**
July (preferred), August, September

**Comment by kosamari** [comment]
Hey ya @den1k we tend to prefer talks that are about what you [did/made/learnt] over what X is type talk.  Can you maybe share what you plan to talk about Vimsical ? Thanks :)

If you like to get reserved ticket,  (talk submitter gets link to 1st dibs on ticket) ping me on the email !

**Comment by den1k** [comment]
@kosamari Sure, actually most of my talk is about showing what we made and how it changes the way tutorials are made. It will be 70% demo. Would you like me to change the description?

**Comment by den1k** [comment]
^ @kosamari

**Comment by paladique** [comment]
Hey @den1k Sorry for the delay here. Would you like to extend your proposal submission to the end of the year?

**Comment by den1k** [comment]
@paladique Absolutely. October would be great because I have some travel plans. I've been giving the talk a few times and received very good feedback. I think people will like it. :)

**Comment by den1k** [comment]
@paladique I'd still love to talk. Available later in Q1 2018.

**Comment by paladique** [comment]
Sure, I'll reopen it!

**Comment by den1k** [comment]
@paladique is there are way to find out when I get to talk?

**Comment by paladique** [comment]
@den1k unfortunately there's no talk/speaker queue, it's done by organizer vote based on topic and month. If you'd like to increase your chances, feel free to propose another talk topic in a separate issue!

**Comment by den1k** [comment]
Got it @paladique. I think the wording here was off. A lot happened since opening this issue. I made a new one with a different description and links to articles about Vimsical as well as an interactive demo. Hope that will make things clearer.
