### ISSUE TITLE
Thoughts on handling adversity

### ISSUE THREAD

**Issue by rossta** [brooklynjs/brooklynjs.github.io#416]
## BrooklynJS Talk Submission

**Talk Title:**

Scars: On handling adversity

**Talk Description:**

We all encounter setbacks. Whether we are victims of circumstance or unintentionally cause ourselves harm, facing consequences is something common to us all. Sometimes we're able to bounce back. Sometimes, our setbacks our permanent and what was once certain is no longer.

Last year, I suffered a deeply personal loss for which I was completely unprepared. In the aftermath, I almost left the tech industry altogether. But I got help and now I've returned; I'm coding again and I've learned a great deal about carrying on with the scars I've suffered. I'd like to talk about my loss and share three of things I've learned in a way I hope will be beneficial to all.

This is not a technical talk; it is accessible and applicable to all skill levels as I wish to connect with the audience on a more personal level. This talk is not even about JavaScript. However, it a story of a developer's mental health, a topic relevant to everyone in the JS community, and I hope may serve as a thought-provoking departure from the norm.

**Name**:

Ross Kaffenberger

**Twitter Handle (optional)**:

@rossta

**Website (optional):**

https://rossta.net

**Months Available to Speak:** 

September, October, November

**Comment by kosamari** [comment]
woot ! just sent you an email with detail of the event & tickets etc.
Looking forward to your talk on 10/19 !
