### ISSUE TITLE
JavaScript and Self-Deception: Why TypeScript is Not Enough

### ISSUE THREAD

**Issue by hoodunit** [brooklynjs/brooklynjs.github.io#417]
## BrooklynJS Talk Submission

**Talk Title:** JavaScript and Self-Deception: Why TypeScript is Not Enough

**Talk Description:**

JavaScript is often derided for callback hell and for quirks around equality, number handling, type coercions and the "this" keyword. This is largely a straw man argument. Developers work around these shortcomings through conventions, tools, and libraries and the problems caused by these kinds of quirks come up infrequently. This talk instead aims to explore the best ways that I know how to write JavaScript- using good conventions, using functional libraries, using types, using promises and immutable data- and motivate PureScript as a way of pushing the limits and bringing development in the JavaScript ecosystem to the next level.

**Name**: Nicholas Kariniemi

**Twitter Handle (optional)**: [@nkariniemi](https://twitter.com/nkariniemi)

**Website (optional):** http://blog.ndk.io

**Months Available to Speak:** July, August, September

**Comment by kosamari** [comment]
thanks for submission ! we run out of speaker slots for August 😢 
Message me (Email on my profile) if you like to get reserved ticket for talk submitter !

**Comment by hoodunit** [comment]
Closing this one out as it looks like it's not going to happen :).

**Comment by paladique** [comment]
@hoodunit We can extend this to Dec if your schedule permits, if not feel free to make a new issue when the time is right :)

**Comment by hoodunit** [comment]
Thanks, I'll make a new issue if it comes to it as it would likely be a somewhat different talk at that point.
