### ISSUE TITLE
Machine Learning, JavaScript, and Art

### ISSUE THREAD

**Issue by amycheng** [brooklynjs/brooklynjs.github.io#419]
## BrooklynJS Talk Submission

**Talk Title:**
Machine Learning, JavaScript, and Art

**Talk Description:**
My talk is about making an art with machine learning. I'll talk about the some concepts discussed in machine learning code implementations (like perceptrons!), as well as how and WHY we would do this in JavaScript. I'll end my talk with a demo of a JavaScript app that looks at a photo and tries to recreate it *creatively*.

Note: This talk is modified from the last section of my Nordic.Js and JSConf Iceland talk, [Create Art With Javascript](https://github.com/amycheng/create-art-with-js)
**Name**:
Amy Cheng

**Twitter Handle (optional)**:
@am3thyst

**Website (optional):**
amycheng.info

**Months Available to Speak:** 
- August, September, October, whenever

**Comment by willmanduffy** [comment]
Thanks for submitting! Happy to say we've got a spot for you this month! @kosamari will be reaching out with details on speaking and getting your ticket soon!
