### ISSUE TITLE
Gerrymandering: a High-Stakes Geometry Problem

### ISSUE THREAD

**Issue by mapmeld** [brooklynjs/brooklynjs.github.io#420]
## BrooklynJS Talk Submission

**Talk Title:**

Gerrymandering: a High-Stakes Geometry Problem

**Talk Description:**

Every ten years, everyone in the US is counted by the Census, and our congressional districts get redrawn. In 2020 it will be different: manipulating the district maps, known as gerrymandering, is now done with algorithms and "big data" collected on every voter.  [A recent study](https://www.brookings.edu/blog/fixgov/2017/07/19/supreme-court-to-scrutinize-partisan-gerrymandering/) concluded that “the severity of today’s gerrymandering is…unprecedented in modern times.”

This month I went to "[Gerrymandering Summer School](https://sites.tufts.edu/gerrymandr/)" by the MGGG (Metric Geometry and Gerrymandering Group) to help make web maps / GIS tools.

This talk will (in a tech-focused and almost-politics-free way) cover :
- what is "gerrymandering" even
- why we probably can't draw districts with one, unbiased algorithm
- open source maps and metrics that MGGG is making to challenge unconstitutional districts
- (with LeafletJS / D3.JS visualizations, of course)

**Name**:

Nick Doiron

**Twitter Handle**:

mapmeld

**Months Available to Speak:**

August 2017, or postpone to 2018 I think

**Comment by willmanduffy** [comment]
Thanks for submitting! Happy to say we've got a spot for you this month! @kosamari will be reaching out with details on speaking and getting your ticket soon!
