### ISSUE TITLE
From C to Not-So-Shining PHP: How The New York Times Story Team grew up on the Web

### ISSUE THREAD

**Issue by mbeswetherick** [brooklynjs/brooklynjs.github.io#421]
## BrooklynJS Talk Submission

**Talk Title:**
From C to Not-So-Shining PHP: How The New York Times Story Team grew up on the Web

**Talk Description:**
I will detail how The New York Times emerged from the ashes of PHP, built a new and beautiful CMS, found itself in a sea of React components, crafted a weird AF responsive grid in scss and JavaScript (that works in IE11), and built a system that allows designers and programmers to work on something once and reuse it wherever and whenever the hell they want to! :^)

**Name**:
Michael Beswetherick

**Twitter Handle (optional)**:
@challuniverse

**Website (optional):**
http://michaelbeswetherick.com/

**Months Available to Speak:**
August, September, October

**Comment by kosamari** [comment]
Heeey thanks for the talk submission! Unfortunately we are full for speaker slots for this month.
We have reserved ticket for talk submitters, so please email me if you like to get one (address on my profile).

**Comment by kosamari** [comment]
Hey hey just sent you email with detail about event & tickets. please check your inbox. Very much looking forward to see you at the event !
