### ISSUE TITLE
ContractPatch: Employment Advocacy for the Digital Laborer

### ISSUE THREAD

**Issue by F-Jennings** [brooklynjs/brooklynjs.github.io#422]
## BrooklynJS Talk Submission

**Talk Title:**
ContractPatch: Employment Advocacy for the Digital Laborer

**Talk Description:**
Many developers and tech workers sign employment agreements with their employers that include broad restrictions on their ability to contribute to FOSS projects — whether as part of their employment, after hours, or both. ContractPatch is an initiative to give digital laborers the words they need to make sure they can continue the work that’s important to them and to our community. Whether those words are negotiation tactics in the hiring process, or language to suggest for a prospective employment agreement, ContractPatch aims to help developers defend their own interests and property rights.

Negotiating a contract is a skill like any other. ContractPatch aims to give developers access to the soft skills and hard contract clause language necessary for effectively asserting your rights as a digital laborer.

**Name**:
Fred Jennings

**Twitter Handle (optional)**:
[@Esquiring](https://www.twitter.com/esquiring/)

**Website (optional):**
[Software Freedom Conservancy's ContractPatch page](https://sfconservancy.org/blog/?tag=ContractPatch)

[Fred's outdated lawyerly bio](http://torekeland.com/attorneys/fred-jennings)

**Months Available to Speak:**
August 2017, November 2017, December 2017

**Comment by willmanduffy** [comment]
Thanks for submitting! Happy to say we've got a spot for you this month! @kosamari will be reaching out with details on speaking and getting your ticket soon!
