### ISSUE TITLE
Choosing GraphQL for your API

### ISSUE THREAD

**Issue by WesleydeSouza** [brooklynjs/brooklynjs.github.io#424]
## BrooklynJS Talk Submission

**Talk Title:**
Choosing GraphQL for your API

**Talk Description:**
GraphQL is an interesting way of implementing API endpoints. In this talk, I will introduce GraphQL, show what does and what it does not do, with lots of live examples.

**Name**:
Wesley de Souza

**Twitter Handle (optional)**:
[@WesleydeSouza](https://twitter.com/WesleydeSouza)

**Website (optional):**
[wesley.so](https://wesley.so)

**Months Available to Speak:**
September, October, November

**Comment by paladique** [comment]
@WesleydeSouza Hello! This talk has been accepted! I'll close the other proposal, feel free to revisit it in a year, as speakers generally are allowed to speak once a year. Is the email on your GitHub profile a good place to reach you?

**Comment by WesleydeSouza** [comment]
@paladique Yes, you can reach me there.
