### ISSUE TITLE
SpeakerSubmission: The (re)Acts over, Vue to the Rescue!

### ISSUE THREAD

**Issue by jmichaliga** [brooklynjs/brooklynjs.github.io#425]
## BrooklynJS Talk Submission

**Talk Title:** The (re)Acts over, Vue to the Rescue!

**Talk Description:** After it's time in the sun, React has been more of a fatigue with 16+ versions. We discuss the similarities, differences and benefits of this lightweight framework and why it deserves the praise. Justin is an UI Engineer who's worked with javascript in his tool belt since the early 2000's.  

**Name**: Justin Michaliga

**Twitter Handle (optional)**: @jmichaliga

**Website (optional):** http://smartnode.codes

**Months Available to Speak:** October, November, December

**Comment by paladique** [comment]
Hi @jmichaliga! Just noticed you never received firsties ticket for submitting a proposal. Unfortunately your talk is not in this month's lineup, so email organizers@brooklynjs.com to grab your ticket!

**Comment by sw-yx** [comment]
would love to see this!
