### ISSUE TITLE
`gcloud create-todo-app` and other such magic

### ISSUE THREAD

**Issue by TychosDrunkElk** [brooklynjs/brooklynjs.github.io#426]
## BrooklynJS Talk Submission

**Talk Title:**  
`gcloud create-todo-app` and other such magic

**Talk Description:**
Google Cloud Platform is an amazing tool chalk-full of features, but can be a bit intimidating at first glance. This talk will walk through some of the tools provided by GCP with the time tested strategy employed by the coolest frameworks: the TODO list app.   
Will cover:
  
- deploying a node app to app-engine, versioning and debugging
- persisting data with DataStore and how to manage it
- using DataStore in your node app
- helpful `gcloud` commands (create-todo-app is not one of them, I made that up)

**Name**:
Phoebe Stierhoff  

**Twitter Handle (optional)**:
@tychosdrunkelk  

**Website (optional):**

**Months Available to Speak:** September, October, November

**Comment by paladique** [comment]
Hi @TychosDrunkElk! Just noticed you never received a firsties ticket for submitting a proposal. Unfortunately your talk is not in this month's lineup, so email organizers@brooklynjs.com to grab your ticket!
