### ISSUE TITLE
Learning from History: 🏠 Architecture & Universal Design

### ISSUE THREAD

**Issue by emily-plummer** [brooklynjs/brooklynjs.github.io#427]
## BrooklynJS Talk Submission

**Talk Title:**
Learning from History: Architecture & Universal Design

**Talk Description:**
What can we learn from history to help us become better developers? The Universal Design movement, popular in 🏠 architecture 🏠  in the late 60's and early 70's, continues to inform some of the best designs across industries to this day. I'll go over how we can borrow from the Universal Design movement to write clean code that works for everyone. I'll also go over some basic concepts of accessibility and why every application should keep accessibility in mind!

**Name**:
Emily Plummer

**Twitter Handle (optional)**:
@emplums (on & off twitter rn)

**Website (optional):**

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!

September!

**Comment by paladique** [comment]
@emily-plummer your talk has been accepted for this month! Is your email on your GitHub profile a good place to reach you for speaker info?

**Comment by emily-plummer** [comment]
YAY! Yeah eplummer26@gmail.com is perfect! :)
