### ISSUE TITLE
Building the Image Grid from Google Photos

### ISSUE THREAD

**Issue by schlosser** [brooklynjs/brooklynjs.github.io#428]
## BrooklynJS Talk Submission

**Talk Title:** Building the Image Grid from Google Photos

**Talk Description:**

In 2015, I decided to take a picture of everything I ate. Every sandwich, every chip, and every square of chocolate. For 365 days, if I ate it, I took a picture of it. When December rolled around, I had over 1,800 pictures with nowhere to put them. I couldn’t upload that many photos to Facebook or Instagram, and I hadn’t found a photo service that I liked enough to put my food photos on.

[So I built a website.](https://feeding.schlosser.io/)

It turns out, in the course of making a website for viewing 1,800 photos I ran into a bunch of interesting technical challenges, and walked away from the whole thing with a JavaScript library called [pig.js](https://github.com/schlosser/pig.js), an image grid that is faster, more responsive, and easier to use than any other solution I could find. It's heavily influenced by the Google Photos image grid, and this talk explains how it works.

**Name**:

Dan Schlosser

**Twitter Handle (optional)**:

[@danrschlosser](https://twitter.com/danrschlosser/)

**Website (optional):**

https://schlosser.io

**Months Available to Speak:** 

September, November, December

**Comment by paladique** [comment]
Hi @schlosser! Just noticed you never received a firsties ticket for submitting a proposal. Unfortunately your talk is not in this month's lineup, so email organizers@brooklynjs.com to grab your ticket!
