### ISSUE TITLE
From Barely Ready to Total Betty: How JS Picked Out My Outfit

### ISSUE THREAD

**Issue by modernserf** [brooklynjs/brooklynjs.github.io#429]
## BrooklynJS Talk Submission

**Talk Title:**
From Barely Ready to Total Betty: How JS Picked Out My Outfit

**Talk Description:**
Star Trek's communicators and tricorders are often cited as the inspirations for the modern smartphone, but no science fiction has inspired me as deeply as [Cher's closet in Clueless](https://www.youtube.com/watch?v=XNDubWJU0aU). In this talk, we'll build a web app to put together cute, coordinated outfits, and along the way we'll learn a little bit about constraint solvers, relational databases, and the history of artificial intelligence.

**Name**:
Justin Falcone

**Twitter Handle (optional)**:
@modernserf

**Website (optional):**
https://justinfalcone.com/

**Months Available to Speak:**
Sept / Oct / Nov

**Comment by paladique** [comment]
@modernserf welcome back to the speaker lineup! Is the email on your website a good place to reach out to you?

**Comment by modernserf** [comment]
👍
