### ISSUE TITLE
Synth-ier Things

### ISSUE THREAD

**Issue by eric-wood** [brooklynjs/brooklynjs.github.io#430]
## BrooklynJS Talk Submission

**Talk Title:**

Synth-ier Things

**Talk Description:**

A crash course on subtractive synthesis with the goal of creating a web-based synthesizer that can only play the Stranger Things theme song repeatedly. We'll explore the fundamentals of sound and dive deep into what those cool vintage synthesizers are actually up to behind the scenes, all with some neat visualizations and cool noises.

**Name**:

Eric Wood

**Twitter Handle (optional)**:

[@eric_b_wood](https://twitter.com/eric_b_wood)

**Website (optional):**

[http://ericwood.org](ericwood.org)

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!

Sept / Oct / Nov

(october is preferred because it'll be right before the new season of stranger things gets released 😬 )

**Comment by kosamari** [comment]
Yaaay very much looking forward to your talk. Just sent you an email with details. 
You've been our musical guest of you know what we have at the venue, but let me know if you need anything special AV-wise for your talk!
