### ISSUE TITLE
Bringing components to legacy code

### ISSUE THREAD

**Issue by WesleydeSouza** [brooklynjs/brooklynjs.github.io#431]
## BrooklynJS Talk Submission

**Talk Title:**
Bringing components to legacy code

**Talk Description:**
Not all systems allow the code to take over the entire rendering of your app. Sometimes you want to modernize and scale your code using libraries such as React on systems that already have a lot of legacy interactive code, or a CMS that must controls what is rendered in the page.

This talk shows techniques to adapt an existing environment so modern libraries can coexist with existing environments, where the DOM dictates the components it needs.

**Name**:
Wesley de Souza

**Twitter Handle (optional)**:
[@WesleydeSouza](https://twitter.com/WesleydeSouza)

**Website (optional):**
[wesley.so](https://wesley.so)

**Months Available to Speak:**
September, October, November

**Comment by paladique** [comment]
Closed in favor of #424
