### ISSUE TITLE
Mindful Communication in Code Reviews

### ISSUE THREAD

**Issue by imightbeamy** [brooklynjs/brooklynjs.github.io#433]
## BrooklynJS Talk Submission

**Talk Title:** Mindful Communication in Code Reviews

**Talk Description:** Mindful communication means to listen and speak with compassion, kindness and awareness. This is easier said than done, so this talk provides examples of how to apply mindful communication to reviewing code.

**Name**: Amy Ciavolino

**Twitter Handle (optional)**: @imightbeamy

**Website (optional):** [amy.tech](http://amy.tech)

**Months Available to Speak:** Any upcoming month! Sept, Oct, Nov.

**Comment by paladique** [comment]
@imightbeamy  Hello there! Your talk has been accepted 🎉  I have some info to pass along to you, is the email in your GitHub profile a good way to reach you?

**Comment by imightbeamy** [comment]
🎉 Hooray! Yes that email is good :)

**Comment by kosamari** [comment]
yay yay just sent you email with all the details about event & tickets. looking forward to meeting you at the event !
