### ISSUE TITLE
Skin and Bones - Skeletal Animation in your Browser via WebGL

### ISSUE THREAD

**Issue by chinedufn** [brooklynjs/brooklynjs.github.io#435]
## BrooklynJS Talk Submission

**Talk Title:**

Skin and Bones - Skeletal Animation in your Browser via WebGL

**Talk Description:**

If you've ever watched a movie or played a video game where there were 3D characters that moved around, you've seen skeletal animation!

But.. how does it work?

A lack of beginner resources on the web will have you thinking that it's black magic, but it turns out that there are only two key concepts at play:

A skin and some bones.

In this talk we'll learn how skeletal animation works by talking through some WebGL and JavaScript powered interactive slides that I'll make for BrooklynJS. 

We'll render a skeletally animated character and some other helper visuals and dive into what's going on (explained at a beginner level).

**You'll walk away with**:

- A better understand of how it all works because you've gotten a combo of interactive visuals and me describing said visuals with no background knowledge assumed.

- A GitHub link to the source code powering the interactive slides / the skeletal animation implementation & visuals

- A sense of where to find more resources to keep the ball rolling after this 10 minute introduction of skeletal animation

**Name**:

Chinedu Francis Nwafili

**Twitter Handle (optional)**:

[@chinedufn](http://twitter.com/chinedufn)

**Website (optional):**

http://chinedufn.com

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!

January 2018 | February 2018 | March 2018 in no particular order

---

Thanks for reading!

**Comment by paladique** [comment]
@chinedufn thanks for your submission, your talk wasn't selected this month but you get firsties on tickets! email organizers@brooklynjs.com for details.

**Comment by paladique** [comment]
@chinedufn We're looking forward to your talk this month! Congrats! An email with speaker details is coming soon.
