### ISSUE TITLE
Mentorship + Sponsorship

### ISSUE THREAD

**Issue by larahogan** [brooklynjs/brooklynjs.github.io#436]
## BrooklynJS Talk Submission

**Talk Title:** 

Mentorship + Sponsorship

**Talk Description:**

To grow our technical leadership skills, it’s critical to lean on one’s network of support. We often find mentors: people who can give us helpful advice. But what can be even more valuable is finding “sponsors”, who help us find new opportunities and improve the visibility of our work. As sponsorship is especially important for members of underrepresented groups in tech, we’ll walk through tactics you can employ today to be a sponsor for those around you, too.

**Name**:

Lara Hogan

**Twitter Handle (optional)**:

@lara_hogan

**Website (optional):**

http://larahogan.me

**Months Available to Speak:**

October, November, and 2018!

**Comment by paladique** [comment]
@larahogan excited to have you in this month's lineup! Could you please email organizers@brooklynjs.com? - we've got some speaker details+logistics to send to you. Thanks!
