### ISSUE TITLE
More Than Music with MIDI, JavaScript & Tiny Computers

### ISSUE THREAD

**Issue by georgemandis** [brooklynjs/brooklynjs.github.io#437]
## BrooklynJS Talk Submission

**Talk Title:** More Than Music with MIDI, JavaScript & Tiny Computers

**Talk Description:** We're living the halcyon days of tiny computers and JavaScript, but MIDI is a technology that's been around for much longer. In this talk we'll explore why it's implementation and prevalence in hardware makes for a uniquely intriguing and accessible platform for creative coding.

Tiny computers such as the [RaspberryPi](https://www.raspberrypi.org), [Arduino](https://www.arduino.cc/) and [C.H.I.P.](https://getchip.com/) have finally reached a level of  performance and affordability that makes hardware experimentation accessible to everyone. At the same time, JavaScript has emerged as the lingua franca of web programming and can be found in many places beyond just the browser. 

What if I told you there was a mature protocol that's been around since 1983 and was uniquely poised to take advantage of this development?

Well, wonder no more and [meet MIDI](https://en.wikipedia.org/wiki/MIDI)! 

Sitting at convergence of these two things is MIDI — a niche protocol that's been around since 1983 and was originally designed for musical instruments to communicate with one another. It's event-oriented approach to messaging feels right at home in the asynchronous world of JavaScript & Node, and the prevalence of MIDI support in older musical equipment means you can find unique, hackable and affordable hardware at your local pawnshop or Craig's List.

This unlikely tech stack — Tiny Computers + JavaScript + MIDI — can lend itself to creative programming beyond music. George's Talk will explain how to get started, walk through several examples and elaborate on the future of this stack, not only as a platform for experimentation but for education as well.

**Name**: George Mandis

**Twitter Handle (optional)**: georgeMandis
 
**Website (optional):** [george.mand.is](https://george.mand.is)

**Months Available to Speak:** November 2017, January & February 2018.

**Comment by paladique** [comment]
Thanks for your proposal! You're selected for this month's speaker lineup! We will be sending an email with speaker details soon.
