### ISSUE TITLE
Promises are a monad, and why you don't need to care

### ISSUE THREAD

**Issue by courajs** [brooklynjs/brooklynjs.github.io#438]
## BrooklynJS Talk Submission

**Talk Title:** Promises are a monad, and why you don't need to care (but can if you want)

**Talk Description:** What are monads? Are they useful? And most interestingly, why do some people care so much, and other people care so little? We'll answer these questions by comparing monads to another everyday concept, the brapple.

**Name**: Aaron Sikes

**Twitter Handle (optional)**: @courajs

**Website (optional):**

**Months Available to Speak:** Anytime! Let's say October, November, December

**Comment by kosamari** [comment]
@courajs Hey hey, okay I need to understand both promises & monad! looking forward your talk :) Dpeaker details on your way via email !

**Comment by courajs** [comment]
Hey - I'll be giving this talk at QueensJS in February, so I'm withdrawing it here.
