### ISSUE TITLE
Building a dog-themed file uploader that can survive browser crashes

### ISSUE THREAD

**Issue by arturi** [brooklynjs/brooklynjs.github.io#439]
## BrooklynJS Talk Submission

**Talk Title:** Building a dog-themed file uploader that can survive browser crashes

**Talk Description:** Recently I’ve been working on a cool file uploading widget for the browser called [Uppy](https://uppy.io). It’s modular (everything is a plugin), supports resumable uploads, picking files from external sources, and yes, uploads can even survive browser crashes. My talk plan:

* Choosing `yo-yo` (which later inspired `Choo`) as a lightweight view library for our user interface. What else is out there? Briefly on: `Hyperx` vs `JSX`, `Preact` and `Hyperapp`;
* The Golden Retriever plugin — how we are using `Service Worker` and `IndexedDB` to make uploads survive browser crashes;
* Redux without Redux;
* Building the user interface with plugins and extensibility in mind;
* Open source early on: bonuses and challenges that come with it;

**Name**: Artur Paikin

**Twitter Handle (optional)**: arturi

**Website (optional):** http://arturpaikin.com

**Months Available to Speak:** October, November, December

**Comment by paladique** [comment]
Hi @arturi! Unfortunately your talk was not selected for this month's lineup, but we have a ticket for you! Email organizers@brooklynjs.com to grab a ticket to this month's event!
