### ISSUE TITLE
Hivemind - Using AWS Lambda as a distributed system

### ISSUE THREAD

**Issue by madelinecameron** [brooklynjs/brooklynjs.github.io#440]
## BrooklynJS Talk Submission

**Talk Title:** Leveraging AWS Lambda as a distributed system

**Talk Description:** Using AWS Lambda functions as the backend for distributed jobs. Hivemind is a library that leverages AWS Lambda functions so you can process or gather data quicker than you can locally at an incredibly low cost.

**Name**: Madeline Cameron

**Twitter Handle (optional)**: Madamelic

**Website (optional):** https://github.com/littlstar/hivemind

**Months Available to Speak:** Oct / Nov / Dec

**Comment by vipyne** [comment]
+1 to hearing this talk

**Comment by paladique** [comment]
Hi @madelinecameron! Unfortunately your talk is was not selected for this month's lineup, but we have a ticket for you! Email organizers@brooklynjs.com to grab a ticket to this month's event!

**Comment by kosamari** [comment]
@madelinecameron Heya ! Looking forward to hearing your talk next week ! Details about the event on your way via email!
