### ISSUE TITLE
Mobius – Frontend vs Backend and the Artificial Boundaries We've Constructed

### ISSUE THREAD

**Issue by rpetrich** [brooklynjs/brooklynjs.github.io#441]
## BrooklynJS Talk Submission

**Talk Title:** Frontend vs Backend and the Artificial Boundaries We've Constructed

**Talk Description:** Introduction of an alternate approach to building web applications that seamlessly blend client and server-side development. By introducing asynchronous abstractions over browser APIs and node modules, Mobius is able to execute code in lock-step across multiple machines and simplify the process of building complex applications. We'll take a brief tour through compilers, determinism, network protocols, server-side rendering, security and reactive programming as we tear down the client/server wall. 

**Name**: Ryan Petrich

**Twitter Handle (optional)**: @rpetrich

**Website (optional):** 

**Months Available to Speak:** Oct / Nov / Dec

**Comment by paladique** [comment]
Hi @rpetrich! Unfortunately your talk is was not selected for this month's lineup, but we have a ticket for you! Email organizers@brooklynjs.com to grab a ticket to this month's event!
