### ISSUE TITLE
"Why can't we just use /usr/bin/node?!" --- An introduction to Javascript in Debian

### ISSUE THREAD

**Issue by ehashman** [brooklynjs/brooklynjs.github.io#442]
## BrooklynJS Talk Submission

**Talk Title:** "Why can't we just use /usr/bin/node?!" --- An introduction to Javascript in Debian

**Talk Description:** What is the Debian project? Why does it matter? How does Debian package and distribute Javascript code? And why are its policies so seemingly outdated and opaque? In this talk, I'll introduce the audience to Debian and the Debian Javascript team, share some of the history and challenges of the team, and invite community members to get involved with the project.

**Name**: Elana Hashman

**Twitter Handle (optional)**: @ehashdn

**Website (optional):** https://hashman.ca/talks

**Months Available to Speak:** November, but I'm happy to try to figure out other availability if that doesn't work

**Comment by paladique** [comment]
We're excited to have you in our talk lineup this month! 🎉 We'll be sending you an email with speaker logistics soon.
