### ISSUE TITLE
 How to use dongles to migrate your codebase

### ISSUE THREAD

**Issue by hmillison** [brooklynjs/brooklynjs.github.io#443]
## BrooklynJS Talk Submission

**Talk Title:** How to use dongles to migrate your codebase

**Talk Description:** We have all dealt with bad code written in a library or framework that doesn't suit our needs. It's hard to have the time to do a full rewrite. So how do we migrate to better libraries like Redux or React? :confetti_ball: **Dongles** :confetti_ball: ! I'll share strategies for writing code to inter-operate between your legacy code and new code. After this talk, you'll be ready to build more dongles than Apple would know what to do with.
 
**Name**: Henry Millson

**Twitter Handle (optional)**: @hmillison

**Website (optional):** henrymillison.com

**Months Available to Speak:** October, November, December

**Comment by paladique** [comment]
Hi @hmillison! Unfortunately your talk is was not selected for this month's lineup, but we have a ticket for you! Email organizers@brooklynjs.com to grab a ticket to this month's event!
