### ISSUE TITLE
Talk: From "Hello, world" to The World's Best Crossword Maker in 8 weeks

### ISSUE THREAD

**Issue by keiranking** [brooklynjs/brooklynjs.github.io#445]
## BrooklynJS Talk Submission

**Talk Title:** From "Hello, world" to The World's Best Crossword Maker in 8 weeks

**Talk Description:** I write crosswords for the New York Times. But crossword software sucks. It's clumsy, slow, and expensive. So I taught myself JS and built Phil, the World's Best Crossword Maker, in 8 weeks. It's fast, fun and free. This is how I did it. 

(Topics: JavaScript, WebAssembly, Python, Google, web scraping, data analysis, SAT solvers, logic)

**Name**: Keiran King

**Twitter Handle (optional)**: keiranwking

**Website (optional):** keiranking.com/phil

**Months Available to Speak:** November (best), December

**Comment by ewlin** [comment]
This talk looks awesome! +1

**Comment by paladique** [comment]
Hi @keiranking! Unfortunately your talk is was not selected for this month's lineup, but we have a ticket for you! Email organizers@brooklynjs.com to grab a ticket to this month's event!

**Comment by kosamari** [comment]
Tada ! @keiranking we'd love to hear you talk about crosswords at the event next week! Speaker details on your way via email!
