### ISSUE TITLE
Computational Furniture

### ISSUE THREAD

**Issue by amitlzkpa** [brooklynjs/brooklynjs.github.io#446]
## BrooklynJS Talk Submission

**Talk Title:** Computational Furniture
**Talk Description:**
Using code to design and fabricate furniture.
https://medium.com/@olapdesign/design-for-a-rocking-chair-8a1a1e109d7f
**Name**: Amit Nambiar

**Twitter Handle (optional)**:

**Website (optional):**

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
Nov Dec Jan

**Comment by paladique** [comment]
@amitlzkpa Your talk has been selected for November! 🎉 I couldn't find your email address, so could you email organizers@brooklynjs.com so we can send you speaker information? Thanks!
