### ISSUE TITLE
Great ideas React brought to UI development

### ISSUE THREAD

**Issue by rafaelrinaldi** [brooklynjs/brooklynjs.github.io#447]
## BrooklynJS Talk Submission

**Talk Title:** Great ideas React brought to UI development

**Talk Description:** The idea of this talk is to briefly discuss the best ideas React has brought to the table in my opinion. I've seen quite a few talks on the technical aspects of different features the library offers but I want to analyze the outcome of the ideas and how we can benefit from them while working on user interfaces. The component API, the virtual DOM, great abstraction to favor composition over inheritance, great first contact with functional programming and so forth.

**Name**: Rafael Rinaldi

**Twitter Handle (optional)**: [rafaelrinaldi](https://twitter.com/rafaelrinaldi)

**Website (optional):** [rinaldi.io](https://rinaldi.io)

**Months Available to Speak:** November, December, January

**Comment by paladique** [comment]
Hi @rafaelrinaldi! Unfortunately your talk is was not selected for this month's lineup, but we have a ticket for you! Email organizers@brooklynjs.com to grab a ticket to this month's event!

**Comment by kosamari** [comment]
Hey ya @rafaelrinaldi :) looking forward to having you at BooklynJS ! I'll send you details via email!

**Comment by rafaelrinaldi** [comment]
@kosamari Thanks! Looking forward to it.
