### ISSUE TITLE
Origami Software from Scratch

### ISSUE THREAD

**Issue by robbykraft** [brooklynjs/brooklynjs.github.io#448]
## BrooklynJS Talk Submission

Origami Software from Scratch

I've been doing origami since I was young and recently as a hobby project I've been building origami software to discover novel approaches to origami design. I'll bring some origami that was designed using code and we can chat about 2D planar graph geometry and why software tools can be useful to origami artists.

Robby Kraft

twitter.com/robbykraft

http://origami.pw

Sure! I'll be in town Nov, Dec, January, all 3 of those are good!

**Comment by paladique** [comment]
@robbykraft your talk has been accepted for this month's lineup! 🎉  You'll receive an email soon with details.
