### ISSUE TITLE
Talk Submission: The Technical Interview, Why is it so awful?

### ISSUE THREAD

**Issue by ghinks** [brooklynjs/brooklynjs.github.io#449]
## BrooklynJS Talk Submission

**Talk Title:**
Talk Submission: The Technical Interview, Why is it so awful?
**Talk Description:**
After all this time we still have not made this particular aspect of our profession much better than when I got started. Why is this?
**Name**:
Glenn Hinks
**Twitter Handle (optional)**:
@2roses2
**Website (optional):**
Glennhinks.com
**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!

**Comment by paladique** [comment]
Hi @ghinks! Thanks for your submission. Do you have any specific months that you're available?

**Comment by ghinks** [comment]
I’m pretty much available all months. I am submitting this talk as an individual. But I work at American Express and would say ‘not my employers views’  at the start of the talk. I gave this talk at CodeCampNYC last month at that Microsoft hosted.

Thanks

Glenn

**Comment by paladique** [comment]
Hi @ghinks! Unfortunately your talk is was not selected for this month's lineup, but we have a ticket for you! Email organizers@brooklynjs.com to grab a ticket to this month's event!
