### ISSUE TITLE
WebComponents for regular developers.

### ISSUE THREAD

**Issue by mikeal** [brooklynjs/brooklynjs.github.io#450]
## BrooklynJS Talk Submission

**Talk Title:** WebComponents for regular developers.

**Talk Description:** This talk is about building reusable libraries and UI components that are distributed as custom elements. This talk isn't about the various standards under the "WebComponents" umbrella but instead is about what you can use today to build and distribute isolated framework independent code.

**Name**: Mikeal Rogers

**Twitter Handle (optional)**: mikeal

**Months Available to Speak:** January.

**Comment by paladique** [comment]
@mikeal we're looking forward to having you in this month's lineup! You'll receive an email with speaker info (ticket, logistics) soon.
