### ISSUE TITLE
Testing React Applications with Enzyme 

### ISSUE THREAD

**Issue by Mary-Snow** [brooklynjs/brooklynjs.github.io#451]
## BrooklynJS Talk Submission

**Talk Title:** Testing React Applications with Enzyme 

**Talk Description:**
React continues to grow in popularity, especially with the release of React 16. Developers who love using React may be at a loss of how to test their React applications. In this talk we will explore how to use Enzyme to test your modern React applications. We will dive into Enzyme testing and explore how to test both the DOM and virtual DOM by using Enzyme's core methods: shallow, render and mount. 

**Name**: Mary Snow 

**Twitter Handle (optional)**:

**Website (optional):**

**Months Available to Speak:** November, December, January, February

**Comment by paladique** [comment]
@Mary-Snow thanks for your submission, we're excited to have you in this month's lineup! 🎉  Could you email organizers@brooklynjs.com? We'll pass along some additional speaker information for you there. Thanks!
