### ISSUE TITLE
Talk submission: Introducing wsk: a straightforward and maintainable build system from the Bloomberg Graphics Team.

### ISSUE THREAD

**Issue by mhkeller** [brooklynjs/brooklynjs.github.io#454]
## BrooklynJS Talk Submission

**Talk Title:** Introducing wsk: a straightforward and maintainable build system from the [Bloomberg Graphics team](https://twitter.com/bbgvisualdata).

**Talk Description:** Two years ago, we revamped our project scaffold system and, in the process, designed and built a new, lightweight build system. We've been using it for the last eighteen months and since it's proven stable and adaptive in that time, we just open sourced it this week (https://github.com/bloomberg/wsk). The system emphasizes maintainability and transparency to the user. 

This talk will walk through our process in assessing other build systems (Gulp, Webpack, npm scripts, etc.), discuss how we thought through the design process and go over some of its features that have helped us in our projects.

**Name**: Michael Keller

**Twitter Handle (optional)**: @mhkeller

**Website (optional):** 
Library: https://bloomberg.github.io/wsk
Starter scaffold: https://github.com/bloomberg/wsk.example
Notification library: https://bloomberg.github.io/wsk-notify

**Months Available to Speak:** December, January, February

**Comment by paladique** [comment]
@mhkeller thanks for your submission! Your talk wasn't selected this month, but you get firsties on tickets! Email organizers@brooklynjs.com for details.

**Comment by paladique** [comment]
@mhkeller Thanks again for your proposal! Your talk was not selected for the months you provided, but feel free to submit a new proposal or let us know your availability for the following months and we'll reopen this one for future consideration.

**Comment by mhkeller** [comment]
Thanks @paladique. I've updated the issue with the next few months. I also edited it slightly to make clear that I'll be talking about this library as an example of how we approached a general problem.
