### ISSUE TITLE
NPM & Lockfiles: A Love Story

### ISSUE THREAD

**Issue by danielleadams** [brooklynjs/brooklynjs.github.io#455]
## BrooklynJS Talk Submission

**Talk Title:** NPM & Lockfiles: A Love Story

**Talk Description:** Anyone that's developed with open source has probably been burned by a dependency issue of some sort. The time spent (minutes? hours? years?) debugging dependency-related code adds up- but it doesn't have to be like this! I'd like to discuss the ins and outs of dependency management, and how `lockfile`s give us our valuable development time back.

**Name**: Danielle Adams

**Twitter Handle (optional)**: [@adamzdanielle](https://twitter.com/adamzdanielle)

**Website (optional):** [Medium](https://medium.com/@adamzdanielle)

**Months Available to Speak:** December and/or 2018!

**Comment by paladique** [comment]
👋 @danielleadams excited to have you in our January lineup! An email with details is on the way!
