### ISSUE TITLE
A Flock of Functions (Condensed): Lambda Calculus Way Too Fast

### ISSUE THREAD

**Issue by glebec** [brooklynjs/brooklynjs.github.io#456]
## BrooklynJS Talk Submission

**Talk Title:** A Flock of Functions (Condensed): Lambda Calculus Way Too Fast

**Talk Description:** Lambda calculus means that all computation can be done with functions. No booleans, numbers, control flow or data structures – just functions! The foundation of functional programming languages can be explained in just a couple hours… but forget that, we'll demo it live in ten minutes instead.

**Name**: Gabriel Lebec

**Twitter Handle (optional)**: g_lebec

**Website (optional):** https://github.com/glebec/lambda-talk

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!

January, February, March

---

*Note for submission reviewers: this talk will be more for entertainment than clarity. It's based on a [2-hour talk](https://github.com/glebec/lambda-talk) I give, but cut massively down until it's basically a rapid-fire reconstruction of some programming concepts from scratch, done live in a Node REPL. I hope this sounds appealing, but if it is a little too flippant then no worries.* :-)

**Comment by paladique** [comment]
@glebec thanks for your submission! Your talk wasn't selected this month, but you get firsties on tickets! Email organizers@brooklynjs.com for details.

**Comment by paladique** [comment]
Hi @glebec! The months you submitted for were not selected for the speaker lineup, but please submit again in the future. Thanks for your submission!
