### ISSUE TITLE
Vimsical!

### ISSUE THREAD

**Issue by den1k** [brooklynjs/brooklynjs.github.io#458]
## BrooklynJS Talk Submission

**Talk Title:**
Vimsical!

**Talk Description:**
Today a minority of educators creates the majority of educational content. That makes education narrow and specific. What if we could learn from *everything*? Vimsical is a tool that turns regular coding session into interactive tutorials. Under the hood it's a full-fledged version control system.

Try it [here](https://vimsical.com/vims/5969777d-8dae-48a6-8b6c-838928b59382)
And read the hackernoon article [here](https://hackernoon.com/running-and-debugging-aws-lambda-functions-locally-with-the-serverless-framework-and-vs-code-a254e2011010)

**Name**: Dennis Heihoff

**Twitter Handle (optional)**: @denik

**Website (optional):** vimsical.com

**Months Available to Speak:**
Jan, Feb, March

**Comment by paladique** [comment]
@den1k do you have an email we can reach out to you to? We have a few additional questions. Thanks!

**Comment by den1k** [comment]
@paladique dennis@vimsical.com
