### ISSUE TITLE
Cutting-Edge Retro

### ISSUE THREAD

**Issue by jozanza** [brooklynjs/brooklynjs.github.io#459]
## BrooklynJS Talk Submission

**Talk Title:**

Cutting-Edge Retro

**Talk Description:**

This talk will demonstrate how to use TypedArrays and the Canvas API to create pixel art and games. It covers TypedArray basics, drawing shapes and sprites, animating them, and using a collision map to facilitate user interactions. The talk will conclude by discussing how to combine the aforementioned techniques with WebWorkers using `SharedArrayBuffer`.

If that’s all too much for 10mins, I can just go over my journey creating [pixel8](https://github.com/jozanza/pixel8) (<- latest fork), which relies on all the stuff mentioned above :space_invader: 

**Name**:

Josiah Savary

**Twitter Handle (optional)**:

@jozanza

**Website (optional):**

pixel8.vsmode.org

**Months Available to Speak:** 

Jan / Feb / ~~Mar~~ Apr

**Comment by paladique** [comment]
@jozanza thanks for your submission, your talk wasn't selected this month but you get firsties on tickets! email organizers@brooklynjs.com for details.

**Comment by jozanza** [comment]
@paladique awesome thanks! How should I follow up about future months?

**Comment by paladique** [comment]
@jozanza your work is done! Your talk is still up for selection for the upcoming labeled months.

**Comment by jozanza** [comment]
It looks like I may be doing a bit of traveling in March. Would it be okay to switch that label to April?

**Comment by willmanduffy** [comment]
@jozanza done!

**Comment by jozanza** [comment]
Thanks! I'm also quite open to any feedback or suggestions about this presentation. Please let me know if there are any ways I can refine this proposal (or create a new one) to improve my chances of selection 👍

**Comment by paladique** [comment]
@jozanza  Your talk has been accepted for this month's lineup! 🎉  You should have received an email with details. Please email organizers@brooklynjs.com if you haven't
