### ISSUE TITLE
Empathy Driven Development: Making the Web Accessible to All

### ISSUE THREAD

**Issue by thoughtbyte** [brooklynjs/brooklynjs.github.io#461]
## BrooklynJS Talk Submission

**Talk Title:** Empathy Driven Development: Making the Web Accessible to All

**Talk Description:** Can a blind user use your web app? How about a keyboard only user, or someone with color blindness or a slow 3G connection? This talk will offer practical advice for how, as developers, we can share the experiences of our users, thus allowing us to empathize with them during the development process.

**Name**: Vincent Abruzzo

**Twitter Handle (optional)**: thoughtbyte

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!

February, March, April

**Comment by thoughtbyte** [comment]
Hi,

I'll be giving this talk this month at ManhattanJS so I'd like to remove it from consideration here. Thank you for organizing! I look forward to submitting another talk int he future :)

Best,
Vincent

**Comment by kosamari** [comment]
Awesome, thanks for letting us know Vincent! and Looking forward to your ManhattanJS talk !
