### ISSUE TITLE
Talk Submission: Experiences on creating an Arabic programming language (in JavaScript)

### ISSUE THREAD

**Issue by SimplyAhmazing** [brooklynjs/brooklynjs.github.io#462]
## BrooklynJS Talk Submission

**Talk Title:**

Experiences on creating an Arabic programming language

**Talk Description:**

In the Summer of 2015, while at the [Recurse Center](https://recurse.com), I started working on creating an Arabic programming language that could potentially be used by Arabic speaking people to learn programming. For this talk I want to go over,

* My inspirations for wanting to build an Arabic programming language
* My (failed) attempts at converting existing English programming languages to use arabic
* Awesome JavaScript tooling I used for creating a programming language (PEG.js)
* Things I expected to learn and things I didn't expect to learn but still learned
* Small demo of my programming language [Noor](https://github.com/SimplyAhmazing/noor)
* Next steps, my plans for version 2 (and the more awesome JS tooling I came across)

**Name**:

Ahmed Abdalla

**Twitter Handle (optional)**:

[@simplyahmaz1ng](https://twitter.com/SimplyAhmaz1ng)

**Website (optional):**

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!

February, March, April

**Comment by paladique** [comment]
@SimplyAhmazing Your talk has been accepted for this month! Congrats! We'll be sending you speaker details soon.
