### ISSUE TITLE
Homograph Attacks, a History

### ISSUE THREAD

**Issue by loganmeetsworld** [brooklynjs/brooklynjs.github.io#464]
## BrooklynJS Talk Submission

**Talk Title:** 

Homograph Attacks, a History

**Talk Description:**

[Homograph Attacks](https://en.wikipedia.org/wiki/IDN_homograph_attack) on the internet date back the 1996, so why are they still relevant today? We'll dive into some internet governance terminology, review a decades-long debate about the worldwide nature of the internet, and take a look at the ways ICANN, browsers, and app developers continue to combat this attack. 

Layout:

I. Definition of terms and players: ICANN, punycode, homograph, scripts, gTLDs,  and ccNSO
II. Short History 1996 - 2017
III.  Where ICANN stands with dealing with the attack
IV. What major browsers do to combat the attack (cool demo!)
V. What YOU (an app developer) can do with UI to prevent the attack (cooler demo!) 

**Name**:

Logan McDonald

**Twitter Handle (optional)**:

@loganmeetsworld

**Website (optional):**

https://loganmeetsworld.com

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!

February, March, April

**Comment by paladique** [comment]
@loganmeetsworld Thanks for your submission, your talk has been accepted for this month's lineup! We'll be emailing you soon with speaker details!
