### ISSUE TITLE
Hello Smol Maps

### ISSUE THREAD

**Issue by dphiffer** [brooklynjs/brooklynjs.github.io#465]
## BrooklynJS Talk Submission

**Talk Title:**
Hello Smol Maps

**Talk Description:**
Do you like maps? I like maps, and I also like to make my own maps. I am writing software that helps more people make maps and I would love to share my progress with BrooklynJS!

**Name**:
Dan Phiffer

**Twitter Handle (optional)**:
@dphiffer (I am also on Mastodon: @dphiffer@social.coop)

**Website (optional):**
https://phiffer.org/

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
I'm actually pretty sure I couldn't make the Feb 15 one, but Mar 15 and Apr 19 are looking good. This is all assuming it happens on the third Thursday, please correct me if that's not right.

**Comment by dphiffer** [comment]
Update: I might be more inclined for April, since I just learned about an event I really should attend on March 15th.

**Comment by paladique** [comment]
👌  Updated your availability. Thanks for the update!

**Comment by paladique** [comment]
@dphiffer Your talk has been accepted for this month's lineup! 🎉 You should have received an email with details. Please email organizers@brooklynjs.com if you haven't

**Comment by dphiffer** [comment]
Hooray, thanks @paladique! I got the email. Looking forward to April 19th!
