### ISSUE TITLE
BKJS talk submission (Propel)

### ISSUE THREAD

**Issue by ry** [brooklynjs/brooklynjs.github.io#467]
## BrooklynJS Talk Submission

**Talk Title:**  Differential Programming in JavaScript

**Talk Description:** I will present a new mathematics library called Propel. Propel provides a GPU-backed numpy-like infrastructure for scientific computing in JavaScript. JavaScript is a fast, dynamic language which, we think, could act as an ideal workflow for scientific programmers of all sorts.

**Name**: Ryan Dahl

**Website:** http://propelml.org/

**Months Available to Speak:** February, March

**Comment by paladique** [comment]
@ry Congrats! Your talk has been accepted! We'll be emailing you speaker details very soon.

**Comment by ry** [comment]
\o/
