### ISSUE TITLE
Building a Modern CMS with Apollo, Emotion, Draft and Redraft

### ISSUE THREAD

**Issue by staylor** [brooklynjs/brooklynjs.github.io#468]
## BrooklynJS Talk Submission

**Talk Title:**

Building a Modern CMS with Apollo, Emotion, Draft and Redraft

**Talk Description:**

Building UIs has never been easier - and with tools like React, Apollo, and GraphQL, interacting with data has never been more pleasant for front end devs. DraftJS and Redraft make managing and rendering content painless across your web and native apps, and in the editing experience within your CMS. This talk will walk you through this data flow, and show you how to share components and styles using a modern CSS-in-JS toolkit like Emotion.

**Name**:

Scott Taylor

**Twitter Handle (optional)**:

@wonderboymusic

**Website (optional):**

https://nytimes.com
https://highforthis.com

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!

All

**Comment by paladique** [comment]
Hi @staylor, thank you for your submission! Your talk wasn't selected for the months you mentioned, so I'm going to close this for now, but please feel free to submit a new one.  I also noticed that you never received a firsties ticket. Please reach out to organizers@brooklynjs.com if you'd like one for May.
