### ISSUE TITLE
SaaS: Shitposting as a Service

### ISSUE THREAD

**Issue by goldsamantha** [brooklynjs/brooklynjs.github.io#469]
## BrooklynJS Talk Submission

**Talk Title:**
SaaS: Shitposting as a Service

**Talk Description:**
This is a talk about shitposting, programming, and love! I'll show you how to transform your images and gifs with glitter crowns and laser eyes by using some geometry and a few handy APIs. You'll leave being able to show your friends you care with artisanal pics of their faces in a ham (or other vegan options)!
![brianjbrennan](https://user-images.githubusercontent.com/2334514/35655871-2eb7bd22-06c2-11e8-8562-239b46aac7fd.gif)

**Name**: Samantha Goldstein

**Twitter Handle (optional)**:
@samantha_gold

**Website (optional):**
http://samanthagoldste.in

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
Feb/March!

**Comment by paladique** [comment]
Your talk has been accepted for this month 🎉 We'll be emailing you soon with speaker details!
