### ISSUE TITLE
Unlock the Power of JavaScript Decorators

### ISSUE THREAD

**Issue by nirkaufman** [brooklynjs/brooklynjs.github.io#471]
## BrooklynJS Talk Submission

**Talk Title:**
Unlock the Power of JavaScript Decorators

**Talk Description:**
Decorators are powerful but sometimes misunderstood language features of JavaScript. 
In this session you will learn what decorators are, why they are used, and how take advantage of them in practice. We will explore the use of decorators in libraries, and how to create our own decorators.

**Name**:
Nir kaufman

**Twitter Handle (optional)**:
@nirkaufman

**Website (optional):**

**Months Available to Speak:** 
February, March, April

**Comment by paladique** [comment]
@nirkaufman your talk has been accepted for this month's lineup! 🎉 You should have received an email with details. Please email organizers@brooklynjs.com if you haven't

**Comment by nirkaufman** [comment]
Unfortunately, this is the only Month that i can't make it :(

*Nir Kaufman*
*Principal Frontend Consultant** • **Google Developer Expert
<https://developers.google.com/experts/people/nir-kaufman>*

On Fri, Apr 6, 2018 at 12:48 AM, Jasmine Greenaway <notifications@github.com
