### ISSUE TITLE
UI Design for engineers who are scared of design, but have to do it anyway

### ISSUE THREAD

**Issue by gckwan** [brooklynjs/brooklynjs.github.io#473]
## BrooklynJS Talk Submission

**Talk Title:** UI Design for engineers who are scared of design, but have to do it anyway

**Talk Description:**
Most of us have found ourselves, at some point in time, building a UI without the help of a designer. Maybe you're short-staffed at work, or you're spinning up your own personal project. Never fear! Your friendly neighborhood UX Engineer is here with some practical advice for how to leverage established patterns and libraries to build effective UIs on the web. I'll also touch on some common traps that engineers fall into when designing UIs and how to avoid them.

**Name**: Grace Kwan

**Website (optional):** https://medium.com/@gckwan

**Months Available to Speak:** August

**Comment by paladique** [comment]
@gckwan Your talk has been accepted for this month's lineup! 🎉 You should have received an email with details. Please email organizers@brooklynjs.com if you haven't

**Comment by paladique** [comment]
@gckwan Your talk has been accepted for this month's lineup! You should be receiving an email with details, please grab your speaker ticket to confirm your spot in the lineup. Reach out to us at organizers@brooklynjs.com if you haven't received it.

**Comment by kosamari** [comment]
@gckwan you talk is IN for July eddition ! you should recieve email soon with ticket info etc. See you in two weeks !

**Comment by kosamari** [comment]
Will email you about details for August event!
