### ISSUE TITLE
Scaling Visualization for Large Data Sets with WebGL

### ISSUE THREAD

**Issue by mhintz** [brooklynjs/brooklynjs.github.io#475]
## BrooklynJS Talk Submission

**Talk Title:**

Scaling Visualization for Large Data Sets with WebGL

**Talk Description:**

Creating legible, effective, and performant visualizations of large datasets is notoriously difficult in both design and implementation. Yet in an increasingly data-driven world, visualization practitioners frequently need to tackle this challenge. As the data scales, designers and developers must find novel methods to reduce visual complexity and optimize rendering.

Recently at Datadog we were faced with the challenge of scaling our visualization of customers’ deployed infrastructure, a component of our mission-critical monitoring product. Some customers have tens of thousands of hosts reporting data, and there’s no perfect way to aggregate them in an overview. Furthermore, browser rendering technologies start to degrade when rendering tens of thousands of elements. We needed to find a solution that would scale with our customers, especially as we added support for containerized infrastructure.

In this talk, I’ll recount our journey of leveraging WebGL to scale beyond what d3 and SVG could handle. The talk will be partly technical and partly design-oriented, with enough real-world lessons learned to engage any audience member. I’ll explain how to decide if WebGL rendering makes sense for your visualization, describe the pitfalls we encountered and how to overcome them, and how we ultimately found success incorporating this new and challenging technology into our large, rapidly-evolving frontend codebase.

**Name**:

Mark Hintz

**Twitter Handle (optional)**:

`@MarkHintz`

**Months Available to Speak:**

March, April, May

**Comment by paladique** [comment]
@mhintz 👋 I noticed that you never received a firsties ticket for the months that you were not selected for the speaker lineup. Please reach out to organizers@brooklynjs.com if you'd like one for May.

**Comment by paladique** [comment]
@mhintz  Your talk has been accepted for this month's lineup! You should be have received an email with details. Please grab your speaker ticket to confirm your spot in the lineup. Reach out to us at organizers@brooklynjs.com if you haven't received it.

**Comment by mhintz** [comment]
Awesome! Looking forward to it :D
