### ISSUE TITLE
Building Fictional Worlds in Javascript: How I built a text adventure game in React

### ISSUE THREAD

**Issue by nickbytes** [brooklynjs/brooklynjs.github.io#476]
## BrooklynJS Talk Submission

**Talk Title:** Building Fictional Worlds in Javascript: How I built a text adventure game in React.

**Talk Description:**  When I set out to build a game in JavaScript, I expected that I might learn a few new things about browser APIs. Instead I learned how to create my own game engine in React and develop a framework for choosing new libraries, all while having fun creating an immersive game.

**Name**:  Nick Beattie

**Twitter Handle (optional)**:  nicktweattie

**Website (optional):**  nickbytes.com

**Months Available to Speak:** April, May, June

**Comment by paladique** [comment]
@nickbytes 👋 I noticed that you never received a firsties ticket for the month that you were not selected for the speaker lineup. Please reach out to organizers@brooklynjs.com if you'd like one for May.

**Comment by paladique** [comment]
@nickbytes Your talk has been accepted for this month's lineup! You should be have received an email with details. Please grab your speaker ticket to confirm your spot in the lineup. Reach out to us at organizers@brooklynjs.com if you haven't received it.
