### ISSUE TITLE
Building components that style themselves

### ISSUE THREAD

**Issue by rbalicki2** [brooklynjs/brooklynjs.github.io#477]
## BrooklynJS Talk Submission

**Never write styles again - Building components that style themselves**

**Talk Description:**
If I move a `<Headline />` into a `<Panel />`, I expect it's font size to adjust. If I move a `<CallToAction />` into a different section on a marketing site, I expect it's colors to adjust. That's always been cumbersome in React, requiring the developer to thread through styles.

No more! Chameleon JS is a set of tools that allows you to build components that style themselves. Components are styled with the help of a style context, and that style context is updated using a style reducer. The result: when you move a `<Button />` into a `<Panel />`, the context it receives changes, and it knows to style itself differently. You can focus on only writing business logic - never write styles again.

I'd love to share this library that I'm working on :)

**Name**: Robert Balicki

**Twitter Handle (optional)**: statisticsftw

**Website (optional):** https://www.chameleonjs.com/

**Months Available to Speak:** All of them, in general

**Comment by rbalicki2** [comment]
@paladique how do I get scheduled? I would be happy to do May or June

**Comment by paladique** [comment]
@rbalicki2 👋 I noticed that you never received a firsties ticket for the months that you were not selected for the speaker lineup. Please reach out to organizers@brooklynjs.com if you'd like one for May.

**Comment by paladique** [comment]
@rbalicki2 Your talk has been accepted for June! 🎉 Can you email organizers@brooklynjs.com to recieve additional speaker info + speaker ticket? Thanks!
