### ISSUE TITLE
WebGL2: World Beyond the Triangle

### ISSUE THREAD

**Issue by mrspeaker** [brooklynjs/brooklynjs.github.io#478]
## BrooklynJS Talk Submission

**Talk Title:** WebGL2: World Beyond the Triangle 

**Talk Description:** This roller-coaster ride through the WebGL pipeline teaches you everything you'll need to know to venture beyond the boring "hello, world" of points and triangles, into bountiful and beautifully illuminated worlds. Along the way you'll discover the wondrous new features of WebGL2 that will likely unlock your secret desires to explore... the *third* dimension.

**Name**: Earle Castledine

**Twitter Handle (optional)**: @mrspeaker

**Website (optional):** https://www.mrspeaker.net/

**Months Available to Speak:** April... but maybe whatever the month after that is too.

**Comment by paladique** [comment]
@mrspeaker 👋 I noticed that you never received a firsties ticket for the month that you were not selected for the speaker lineup. Please reach out to organizers@brooklynjs.com if you'd like one for May.

**Comment by paladique** [comment]
@mrspeaker Your talk has been accepted for June! 🎉 You will receive an email soon with additional details, when you receive it, confirm your spot in the lineup by grabbing your speaker ticket! See you on the 21st!
