### ISSUE TITLE
From "Hello, world" to The World's Best Crossword Maker in 8 weeks

### ISSUE THREAD

**Issue by keiranking** [brooklynjs/brooklynjs.github.io#479]
Talk Title: From "Hello, world" to The World's Best Crossword Maker in 8 weeks

Talk Description: I write crosswords for the New York Times. But crossword software sucks. It's clumsy, slow, and expensive. So I taught myself JS and built Phil, the World's Best Crossword Maker, in 8 weeks. It's fast, fun and free. This is how I did it.

(Topics: JavaScript, WebAssembly, Python, Google, web scraping, data analysis, SAT solvers, logic)

Name: Keiran King

Twitter Handle (optional): keiranwking

Website (optional): keiranking.com/phil

Months Available to Speak: May, June, July 2018

**Comment by keiranking** [comment]
@paladique You asked me to let you know when I'd be available for this talk. I really appreciate your patience. I will 100% be in NYC in May, June and July. Thanks again.

**Comment by paladique** [comment]
@keiranking  Your talk has been accepted for this month's lineup! You should be have received an email with details. Please grab your speaker ticket to confirm your spot in the lineup. Reach out to us at organizers@brooklynjs.com if you haven't received it.
