### ISSUE TITLE
End to End Testing With Cypress vs. Selenium

### ISSUE THREAD

**Issue by haroldtreen** [brooklynjs/brooklynjs.github.io#480]
## BrooklynJS Talk Submission

**Talk Title:** 

End to End Testing With Cypress vs. Selenium

**Talk Description:**

Ever written an end-to-end test for a website? 
It’s hard! 

The current go-to tool for these tests is Selenium. It lets you issue commands to your browser to automate any actions a user might take - which is awesome! Unfortunately, it’s not the most robust system. Selenium tests can be extremely flakey, slow, and hard to debug. 

But now there’s a new kid on the block: Cypress! It’s an open source tool that takes a different approach in hopes of making end-to-end testing faster, friendlier, and more reliable. 

In this talk, I’ll dive deeper into the differences between Cypress and Selenium, such as time travel debugging, live reloading, and automatic waiting. Through this exploration, I hope to show off how fun and easy end to end testing can be! 😍

**Name**: Harold Treen

**Twitter Handle (optional)**: @haroldtreen

**Website (optional):** https://haroldtreen.com

**Months Available to Speak:** May, June, July

**Comment by kosamari** [comment]
@haroldtreen your talk didn't make it to July edition 😢Closing this issue for now but please submit new ideas in the future !
