### ISSUE TITLE
Building Layr: A p2p decentralized file storage system designed for retrievability, with a smart contract powered payment system

### ISSUE THREAD

**Issue by WilfredTA** [brooklynjs/brooklynjs.github.io#481]
## BrooklynJS Talk Submission

**Talk Title:**
Building Layr: A p2p decentralized file storage system designed for retrievability, with a cryptocurrency-based incentive scheme

**Talk Description:**
"Decentralized file storage systems solve multiple problems inherent in a centralized storage service. Namely, a decentralized system does not take for granted that a data host is inherently trustworthy, available, or resistant to failure.

With great interest in p2p decentralized systems such as Storj, IPFS, and Sia, a team of three developers took a month and a half to build Layr: a decentralized file storage system built atop the Kademlia DHT that enforces data retrievability and provides a cryptocurrency-based incentive.

In the course of building Layr, we encountered many technical and system-design challenges. For example, how does a decentralized system logically distribute and locate files? How does a decentralized system decouple file retrievability from failures on the part of the node hosting that file? How does a decentralized system detect and respond to data loss or corruption to maintain the file's retrievability? How do we provide incentive to encourage ethical behavior of all parties involved? How do we do all of this in a no-trust environment? In this presentation you will learn how we used techniques such as file sharding, proofs of retrievability, cryptocurrency-based transactions and contracts, and extending the Kademlia protocol to solve some of those problems.

**Name**:
Wilfred Tannr Allard
**Twitter Handle (optional)**:
TannrAllard
**Website (optional):**
www.tannrallard.tech
**Months Available to Speak:** 

All of May
All of June

**Comment by paladique** [comment]
@WilfredTA Thank you for your submission! Your talk wasn't included in this month's lineup, but contact organizers@brooklynjs.com for your reserved ticket. I'll be closing this, as the months you've requested have passed. Reach out to us if you have any questions, and we hope to see you submit again!
