### ISSUE TITLE
(WebUSB) I'm afraid your browser has been talking to the robots again

### ISSUE THREAD

**Issue by noopkat** [brooklynjs/brooklynjs.github.io#482]
## BrooklynJS Talk Submission

**Talk Title:**
I'm afraid your browser has been talking to the robots again

**Talk Description:**

The browser’s capabilities have snuck up on us over the years, and it’s turned into a full blown operating system! "But wait," I hear you protest, "it’s not like the browser can talk to stuff I have plugged in to my USB ports!". Ah! But it can!

The new WebUSB spec has arrived, and is already supported in at least one browser today. The previous hacks of connecting browsers to robots and other hardware will soon be a thing of the past. WebUSB as a first class API citizen opens up some great opportunities to create new and delightful experiences with robotics.

I’ll introduce you to the WebUSB API, its history, and compare it to previous ’hacks’ to demonstrate why this is such a big deal for you, as a web developer. There will be hardware shown ~IRL~ ready to inspire you to think outside of the box of what browsers are really meant to be used for.

**Name**:
Suz Hinton

**Twitter Handle (optional)**:
@noopkat

**Website (optional):**
noopkat.com

**Months Available to Speak:** 
May 🌷

**Comment by paladique** [comment]
@noopkat Welcome back! Your talk has been accepted for this month's lineup! You should be have received an email with details. Please grab your speaker ticket to confirm your spot in the lineup. Reach out to us at organizers@brooklynjs.com if you haven't received it.

**Comment by noopkat** [comment]
@paladique thank you so much 🎉
