### ISSUE TITLE
CSS Custom Properties: What Do They Know? Do They Know Things?? Let's Find Out!

### ISSUE THREAD

**Issue by tylergaw** [brooklynjs/brooklynjs.github.io#484]
## BrooklynJS Talk Submission

**Talk Title:** 
CSS Custom Properties: What Do They Know? Do They Know Things?? Let's Find Out!

**Talk Description:** 
This is one of those CSS features that always seemed like it would be great to have in the year 3000. Turns out the year 3000 is now. CSS Custom Properties are available now and have been for some time. They aren't variables as you're used to, they're their own thing. And they're somethin' else. In this talk we'll look at what they are, what they aren't, day-to-day usage examples, how to feature detect for them, and wrap up with a future-facing, super neato example. This talk will be light on JS, but heavy on way cool CSS.

**Name**: 
Tyler Gaw

**Twitter Handle**: 
[@tylergaw](https://twitter.com/tylergaw)

**Website:** 
https://tylergaw.com

**Months Available to Speak:** 
May, June, July

**Comment by paladique** [comment]
👋  @tylergaw  Thank you for your submission! Your talk wasn't included in this month's lineup, but contact organizers@brooklynjs.com for your reserved ticket :)

**Comment by kosamari** [comment]
@tylergaw  Your talk has been accepted for July! 🎉 You will receive an email soon with additional details & ticket info! see you in two weeks !
