### ISSUE TITLE
Going from Designer to CTO in less than two months!

### ISSUE THREAD

**Issue by milesalex** [brooklynjs/brooklynjs.github.io#486]
## BrooklynJS Talk Submission

**Talk Title:**
Designer to CTO in less than two months!

**Talk Description:**
I founded a company called @TokenTax being a product designer and wound up being the most technical one of the founders (I'm okay but meh). I'll walk the audience through going from 0 to building a tech company in two months or less. I'll talk about how we managed to stay afloat, how we managed to hire great people, and how we managed to scale to meet the demand.

**Name**:
Alex Miles

**Twitter Handle (optional)**:
@milesalex

**Website (optional):**
https://tokentax.us

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
June-July-August!

**Comment by milesalex** [comment]
@paladique I can no longer present in june :(

**Comment by kosamari** [comment]
hey ya @milesalex  👋 your talk didn't make it into this month's lineup, but we have a ticket set aside for you for proposing a talk! Please reach out to organizers@brooklynjs.com for details.

**Comment by milesalex** [comment]
@kosamari Thank you!!!

**Comment by milesalex** [comment]
Hey! I don’t think anyone reached out about this ticket.

Best,
Alex

**Comment by paladique** [comment]
@milesalex sorry about that, will send you a link for August's
