### ISSUE TITLE
Creating an effective and inclusive technical interview process

### ISSUE THREAD

**Issue by arshiamufti** [brooklynjs/brooklynjs.github.io#487]
## BrooklynJS Talk Submission

**Talk Title:** Creating an effective and inclusive technical interview process

**Talk Description:**

An empathetic and effective interview process impacts not only the growth of an organization, but also its health, diversity, and the values that its members come to adopt as their operating principles. Yet the industry is rife with interview practices that are remnants of an older time--frameworks that are seldom effective, usually exclusionary to minorities (or those with a non-traditional background), but have somehow become the norm.

In this talk, I'll first explore some common technical interview practices that are ineffective and exclusionary. Then, by stepping through the interview process, I'll give you actionable advice on how to adapt and improve your technical interviews at each stage.

**Name**: Arshia

**Twitter Handle (optional)**: [@arshia__](https://twitter.com/arshia__)

**Website (optional):** [arshiamufti.com/about](https://arshiamufti.com/about)

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!

June, July

**Comment by paladique** [comment]
@arshiamufti Your talk has been accepted for June! 🎉 You will receive an email soon with additional details. When you receive it, confirm your spot in the lineup by grabbing your speaker ticket! See you on the 21st!
