### ISSUE TITLE
A Map of the JavaScript Ecosystem

### ISSUE THREAD

**Issue by slohmes** [brooklynjs/brooklynjs.github.io#488]
## BrooklynJS Talk Submission

**Talk Title:**
A Map of the JavaScript Ecosystem

**Talk Description:**
Module bundlers! Package managers! Superscripts! Polyfills! Frameworks galore! A multitude of JavaScript-based frameworks and tools make up the “JavaScript ecosystem”. This talk groups the tools into a taxonomy, based on what problem each tool is trying to solve and the tool's approach to solving the problem. Armed with this map of the JS ecosystem, front-end enthusiasts of all levels should be less overwhelmed by the ever-expanding landscape of modern front-end development.

**Name**:
Sarah Lohmeier

**Twitter Handle (optional)**:
@slohmes

**Website (optional):**
https://slohmes.wordpress.com/

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
June

**Comment by slohmes** [comment]
Preview of the map: https://pbs.twimg.com/media/DYhzJu9UMAAk9fv.jpg:large

**Comment by paladique** [comment]
@slohmes Your talk has been accepted for June! 🎉 You will receive an email soon with additional details, when you receive it, confirm your spot in the lineup by grabbing your speaker ticket! See you on the 21st!
