### ISSUE TITLE
Mind-controlling the Web

### ISSUE THREAD

**Issue by alexcastillo** [brooklynjs/brooklynjs.github.io#489]
## BrooklynJS Talk Submission

**Talk Title:**
Mind-controlling the Web

**Talk Description:**
What comes after the keyboard and the mouse? More advanced interfaces that allow more effective communication between human and machines, specifically those that tap into the brain. So, let's plug in the human brain to the browser and build a better web. 

The human body is an ocean of electricity. Billions of neurons are constantly engaging as our thoughts go from one state to the next. Come see how we can tap into this data generated by human cells in JavaScript, and how to get started in the NeuroTech community. 

**Name**:
Alex Castillo

**Twitter Handle (optional)**:
castillo__io

**Website (optional):**
https://castillo.io

**Months Available to Speak:** September, October, November

**Comment by paladique** [comment]
@alexcastillo  your talk has been selected for this month! 🎉 Email with details coming soon!
