### ISSUE TITLE
Babel: Beyond the Repository

### ISSUE THREAD

**Issue by hzoo** [brooklynjs/brooklynjs.github.io#490]
## BrooklynJS Talk Submission

**Talk Title:** Babel: Beyond the Repository

**Talk Description:**

There might come a point where you look (back) and you realize you are a maintainer.
There might also be a point where you look beyond the project to understand it's place within the ecosystem.
Let's explore viewing a project not just as infrastructure for a specific app or company but it's role in the language, ecosystem, and open source itself.

**Name**: Henry Zhu

**Twitter Handle (optional)**: [@left_pad](https://twitter.com/left_pad)

**Website (optional):** https://www.henryzoo.com/

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!

June, Sept, not sure

> Looks like it's been 2 years since my meetup first talk!

**Comment by paladique** [comment]
👋  Welcome back @hzoo! Your talk wasn't included in this month's lineup, but contact organizers@brooklynjs.com for your reserved ticket :)

**Comment by paladique** [comment]
@hzoo Your talk wasn't included in any of the months you've requested, and we skipped September. Will close this for now, let us know when your schedule clears up.
