### ISSUE TITLE
SMAAAASH!! Generating Earthbound's SNES data from JavaScript

### ISSUE THREAD

**Issue by gjtorikian** [brooklynjs/brooklynjs.github.io#491]
## BrooklynJS Talk Submission

**Talk Title:** 
SMAAAASH!! Generating Earthbound's SNES data from JavaScript

**Talk Description:**
The Super Nintendo is humanity's greatest video game console, an accomplishment achieved by being the only system worthy of playing the greatest video game of all time, Earthbound. 

In this talk, I'd like to go over a project I've been working on for a couple of years, [Earthbound-Battle-Backgrounds-JS](https://github.com/gjtorikian/Earthbound-Battle-Backgrounds-JS), which reads SNES cartridge data and generates content in a `canvas`. 

**Name**:
Garen Torikian

**Twitter Handle (optional)**:
@gjtorikian

**Website (optional):**

**Months Available to Speak:** July, August, September

**Comment by kosamari** [comment]
@gjtorikian Your talk has been accepted for July! 🎉 You will receive an email soon with additional details, when you receive it, confirm your spot in the lineup by grabbing your speaker ticket! See you in 2 weeks!
