### ISSUE TITLE
Making Self-Generating Hip Hop using JavaScript

### ISSUE THREAD

**Issue by omardelarosa** [brooklynjs/brooklynjs.github.io#492]
## BrooklynJS Talk Submission

**Talk Title:**
Making Self-Generating Hip Hop using JavaScript

**Talk Description:**
Ready to take your hip hop career to the next level and simultaneously apply some of those JavaScript skills at the same time?  Using a little mixture of markov chains, basic music theory and JavaScript you can let your computer generate some beats and grooves for all of your sick verses.

In this talk, I'd like to bring some of the concepts I've written [a few blog posts about](https://www.omardelarosa.com/posts/markov-chain-rhythms.html) into JavaScript and expand on how they can be done perhaps in even a live coding context without too many lines of code required.

**Name**: 
Omar Delarosa

**Twitter Handle (optional)**: 
@omardelarosa

**Website (optional):** 
https://http://omardelarosa.com/

**Months Available to Speak:** 
July, August, September

**Comment by kosamari** [comment]
Your talk has been accepted for July! 🎉 You will receive an email soon with additional details, please look out for that and see in in 2 weeks!

**Comment by omardelarosa** [comment]
Woohoo! 🎉
