### ISSUE TITLE
Details on details

### ISSUE THREAD

**Issue by muan** [brooklynjs/brooklynjs.github.io#494]
## BrooklynJS Talk Submission

**Talk Title:** Details on details

**Talk Description:** 
In GitHub our JavaScript team thinks about "what more can we do without JavaScript" a lot. We strive to use as little JavaScript as possible so we can make sure the JavaScript we do _need_ performs the best. 

This is where `<details>` comes in. In this talk I'll cover how we came to start using `<details>` from HTML 5.1, what we use `<details>` for, and how with just a few tricks `<details>` can be very powerful.

**Name**: Mu-An Chiou

**Twitter Handle (optional)**: @muanchiou

**Website (optional):** https://muan.co

**Months Available to Speak:** July/August/September

**Comment by kosamari** [comment]
🎉 we would love to hear you speak at BrooklynJS in July edition !
Will receive email with speaker ticket shortly :) looking forward to seeing ya !
