### ISSUE TITLE
What We're Doing When We're In a Daily Standup

### ISSUE THREAD

**Issue by dubilla** [brooklynjs/brooklynjs.github.io#500]
## BrooklynJS Talk Submission

**Talk Title:**
What We're Doing When We're In a Daily Standup

**Talk Description:**
Every day, many of us get together with our teammates and talk about what we did yesterday and what we're doing today. If you're in a standup, there's a good chance, you're waiting on your turn to talk, tuning out other people, and trying to actually remember what you did yesterday. These 10 minutes can make or break your day. And with a few added techniques, you can start looking forward to your standup as much as you look forward to your first cup of coffee of the day.

This talk will cover the intention behind the daily standup, ways to ensure you're communicating well with your teammates, and wacky ideas to get the rest of your team connecting better in your standup.

**Name**:
Dan Ubilla

**Twitter Handle (optional)**:
dubilla

**Website (optional):**
www.danubilla.com

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
August, September, December

**Comment by kosamari** [comment]
Yay, thanks for the talk proposal! your talk is IN for the August event! sending you details of the event now!
