### ISSUE TITLE
BrooklynJS Talk Submission: Ask your dumb question

### ISSUE THREAD

**Issue by zeeberry** [brooklynjs/brooklynjs.github.io#501]
## BrooklynJS Talk Submission

**Talk Title:**
Ask your dumb question

**Talk Description:**
Have you ever been in a situation where you didn’t ask a tech question at work because you were scared people would think it was dumb? 
In this talk we’ll examine how many of us may hold an unhealthy idea of what the perfect developer is and how this ideas can cause us to devalue ourselves and hinder our abilities to perform our jobs. We’ll explore together how we can foster a culture of psychological safety that can lead to healthier team dynamics and more productivity.

**Name**:
Zainab Ebrahimi

**Twitter Handle (optional)**:
zainab3brahimi

**Months Available to Speak:** 
August 2018
September 2018
October 2018

**Comment by paladique** [comment]
@zeeberry your talk has been selected for this month! 🎉 Email with details coming soon!
