### ISSUE TITLE
Organizing Code for Cross-Platform Web and Mobile Development

### ISSUE THREAD

**Issue by bscarano** [brooklynjs/brooklynjs.github.io#502]
## BrooklynJS Talk Submission

**Talk Title:**
Organizing Code for Cross-Platform Web and Mobile Development

**Talk Description:**
For teams that deliver code for the web, android, and iOS, we want to avoid writing all of our logic three times, in three different languages, across three different platforms. We will share how our team was successful in developing features of our platform that realized 70% business logic code re-use between web and mobile and even more re-use between Android and iOS. We will discuss the motivations for when it is right to code-share, how to organize your React and React-Native code and build configurations to accomplish code sharing, and how we approach integrating React components into native Android and iOS app.

**Name**:
Robert (Bob) Scarano

**Twitter Handle (optional)**:
@scarano

**Website (optional):**
squarespace.com

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
August, September, October

**Comment by bscarano** [comment]
Hi I just realized this is 2 days away. Has the August event already filled up or are you still deciding the schedule? Just planning my travel and schedule (I live in CT and work in NYC).

**Comment by paladique** [comment]
@bscarano 👋 could you send us an email organizers@brookylnjs.com as soon as you get a second?
