### ISSUE TITLE
Creating an In-Browser Database with JavaScript

### ISSUE THREAD

**Issue by houstonfloyd** [brooklynjs/brooklynjs.github.io#505]
## BrooklynJS Talk Submission

**Talk Title:** 
Creating an In-Browser Database with JavaScript

**Talk Description:**
For most web applications, Internet access is taken for granted. Of course, this means that when applications lose their connection, they lose almost all functionality and user experience.

"Offline-first" or "offline-ready" is a paradigm that seeks to maintain functionality for applications, even when clients are offline for extended periods.

The primary challenge is storing data on clients, particularly for applications that feature lots of data and collaboration between users. Data changes have to be synchronized between clients and a remote server, and conflicts have to be resolved.

More specifically, this talk will cover:
- In-browser options for persistent data storage
- Writing a Promise-based wrapper to work with the asynchronous IndexedDB API
- Tracking JSON document changes in a tree data structure
- Synchronizing database changes to a MongoDB backend over HTTP
- How to handle conflicting changes between users
- Using existing libraries to make your applications offline-first

Throughout the talk, I will draw on my experience working on [turtleDB](https://turtle-db.github.io/), an offline-first framework written in JS, to discuss these challenges.

I have a slide presentation ready and can email on request.

**Name**:
Andrew Houston-Floyd

**Website (optional):**
https://www.linkedin.com/in/andrew-houston-floyd/
https://turtle-db.github.io/ (project website)

**Months Available to Speak:** 
September, October, November

**Comment by paladique** [comment]
@houstonfloyd your talk has been selected for this month! 🎉 Email with details coming soon!
