### ISSUE TITLE
The Goldmine of thi.ng/umbrella

### ISSUE THREAD

**Issue by den1k** [brooklynjs/brooklynjs.github.io#506]
my second talk at Brooklyn JS. I'm excited! :D 

## BrooklynJS Talk Submission

**Talk Title:**
The Goldmine of thi.ng/umbrella

**Talk Description:**
With [thi.ng/umbrella](https://github.com/thi-ng/umbrella) [Karsten Schmidt](https://twitter.com/toxi) single-handedly implemented most of the functional ecosystem in Typescript with mouthwatering code quality and documentation. Go read some of the [code](https://github.com/thi-ng/umbrella/blob/master/examples/crypto-chart/src/index.ts#L13), it's as beautiful as it is terse and functional. In this talk we'll compare a few example apps with current approaches in frontend development. We'll talk about hiccup vs jsx, async await & resolving promises.

Side-note: I'm not some promoter, just a fan of his amazing work.

**Name**: Dennis Heihoff

**Twitter Handle (optional)**: https://twitter.com/denik

**Website (optional):** https://duct.cloud

**Months Available to Speak:** 
September (preferred), October, maybe November

**Comment by paladique** [comment]
👋 @den1k Thank you for your submission! Our policy for return speakers is they can return 1 year after their last talk. We're gonna close this for now, hope you'll come back after January to propose this or something new!

**Comment by den1k** [comment]
👍🏼
