### ISSUE TITLE
The Federation Needs You (or Web 3.1)

### ISSUE THREAD

**Issue by jalcine** [brooklynjs/brooklynjs.github.io#510]
## BrooklynJS Talk Submission

**Talk Title:** The Federation Needs You

**Talk Description:** Some social commentary on the potential benefits we (as developers, designers and users) can bring to the [federated Web](https://indieweb.org/federation) and why for those more aligned to social communication issues may want to step in _now_.

**Name**: I go by Jacky.

**Twitter Handle (optional)**: https://twitter.com/jackyalcine but I use [Mastodon](http://playvicious.social/@jalcine) more often.

**Website (optional):** https://jacky.wtf

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!

- October 2018
- March 2019
- April 2019

**Comment by jalcine** [comment]
On Sunday, September 30, 2018 3:26:00 PM PDT Will Duffy wrote:


> We’ll send a letter. We have a lot of sway with the Oakland 
Commisioners Office


-- 
Jacky Alcine

Work: https://black.af
Blog: https://jacky.wtf/weblog/

**Comment by paladique** [comment]
@jalcine 👋 your talk wasn't selected this month, but please reach out to organizers@brooklynjs.com for a reserved ticket if you're in town 😄
