### ISSUE TITLE
BrooklynJS Talk Submission: CRDT

### ISSUE THREAD

**Issue by ai** [brooklynjs/brooklynjs.github.io#511]
## BrooklynJS Talk Submission

**Talk Title:**

CRDT: conflict-free data types for collaborative editing and offline-first

**Talk Description:**

What technologies could replace GraphQL in the future? How can we mix ideas from Redux and long-standing ideas from the 80s to make the better user experience for our web applications?

I will show how forgotten ideas from the 80s can improve UX of simple ToDo app right now and make the Internet more accessible for next billion users.

**Name**:

Andrey Sitnik

**Twitter Handle (optional)**:

[@sitnikcode](http://twitter.com/sitnikcode)

**Months Available to Speak:**

* October
* November
* December

**Comment by ai** [comment]
I had this talk on recent EmpireJS

**Comment by paladique** [comment]
@ai 👋 Thank you for you proposal! Your talk was not included in this month's lineup, but we have a reserved ticket for your proposal. Email organizers@brooklynjs.com for details.

**Comment by ai** [comment]
@paladique wow, 😍 I sent an email.

Yeap, I understand that it was better to take more time-sensitive talks on this month.
