### ISSUE TITLE
Beyond "animation: fadeIn .2s": Building Non-Trivial Layout Transitions for the Web

### ISSUE THREAD

**Issue by aholachek** [brooklynjs/brooklynjs.github.io#513]
## BrooklynJS Talk Submission

**Talk Title:**
Beyond `animation: fadeIn .2s`: Building Non-Trivial Layout Transitions for the Web

**Talk Description:**
Thoughtful UI transitions can be surprisingly difficult to implement once you want to augment or move beyond the capabilities of CSS. JavaScript libraries that seem like they might help you implement complex animations can end up revealing limitations in real-world situations.

I'll focus on two React libraries that I think do a good job of lowering the barrier to entry by simplifying the process of creating advanced transitions: [React-Pose](https://popmotion.io/pose/) and my own project [React-Flip-Toolkit](https://github.com/aholachek/react-flip-toolkit). While my focus will be on React, the challenges posed and solutions discussed should be somewhat relevant irrespective of framework.

The final part of my talk will walk through implementing a practical example using `React-Flip-Toolkit`, probably using a condensed version of [this presentation](https://alex.holachek.com/rft-tutorial).

**Name**:
Alex Holachek

**Website (optional):**
https://alex.holachek.com/

**Months Available to Speak:** 
November
December
January

**Comment by paladique** [comment]
@aholachek your talk has been accepted in this month's lineup! 🎉 Please email organizers@brooklynjs.com for details and your speaker ticket!
