### ISSUE TITLE
Spook your friends with Electron 👻 

### ISSUE THREAD

**Issue by pixelyunicorn** [brooklynjs/brooklynjs.github.io#514]
## BrooklynJS Talk Submission

**Talk Title:**

Spook your friends with Electron 👻 

**Talk Description:**

In the spirit of halloween, I'll be showing the wild learning/exploring process of building an electron app that simulates a cracked screen. It involves finding out how to make a fullscreen always-on-top electron app running in the background (and its limitations), attempting to figure out how to generate cracked LCD patterns (if that fails or I give up have image fallpacks), and then setting a timer so that it isn't obvious.

To be clear, I haven't built it yet, I am just typing up a talk idea on the subway, but since I have a bit of free time between job interviews, I can work on this over the next week. The end result will be open source on GitHub. 

(PS if accepted, this is my first time I have spoken at any BoroJS meetup in NYC, and fun fact, also the first tech talk I've given outside of a _cough_ my little pony convention this year! I also live in Philly, so travel assistance would be nice.)

**Name**:

Melody Starling

**Twitter Handle (optional)**:

https://mobile.twitter.com/pixelyunicorn

**Website (optional):**

https://melody.cool/

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!

It makes the most sense to do it in October

- October 2018
- November 2018

**Comment by paladique** [comment]
@pixelyunicorn your talk has been selected for this month! 🎉  Could you please email organizers@brooklynjs.com for details? Thanks!!
