### ISSUE TITLE
Proposed talk: Sure, Buy a Drill Press

### ISSUE THREAD

**Issue by pnc** [brooklynjs/brooklynjs.github.io#516]
## BrooklynJS Talk Submission

**Talk Title:** Sure, Buy a Drill Press

**Talk Description:** A look at drilling 55 holes in my MacBook Pro just to fix the keyboard, what I learned about the global supply chain, and why you should consider metalwork as a hobby.

**Name**: Phil Calvin

**Preferred Pronouns**: he/him/his

**Twitter Handle (optional)**: pnc

**Website (optional):** https://philcalvin.com

**Months Available to Speak:** November, January, February

**Comment by paladique** [comment]
@pnc Your talk has been accepted for this month's lineup 🎉. We'll be emailing you details soon!
