### ISSUE TITLE
Building Open Source Communities

### ISSUE THREAD

**Issue by bnb** [brooklynjs/brooklynjs.github.io#517]
## BrooklynJS Talk Submission

**Talk Title:** Building Open Source Communities

**Talk Description:**

```
We talk about community a lot in open source. Communities can make or break any open source project.

There are some common traits–universal lessons that can be taken from working with open source communities–that any open source community can benefit from understanding and approaching thoughtfully.

So what are common traits amongst successful–and not so successful–communities? How can you begin to apply the lessons others have learned, instead of re-inventing the wheel? Most importantly, how can you help ensure _your_ community is successful?
```

**Name**: Tierney Cyren

**Preferred Pronouns**: He/Him

**Twitter Handle (optional)**: @bitandbang

**Months Available to Speak:** November, December, January, Feburary

**Comment by paladique** [comment]
@bnb thank you for your submission! Your talk was not included in this month's lineup, but we have a firsties ticket for you! Email organizers@brooklynjs.com for details

**Comment by paladique** [comment]
@bnb Disregard that last comment, your talk was accepted for this month! Email detail coming soon!

> @bnb thank you for your submission! Your talk was not included in this month's lineup, but we have a firsties ticket for you! Email [organizers@brooklynjs.com](mailto:organizers@brooklynjs.com) for details
