### ISSUE TITLE
Software Evolution and Other People's Ideas

### ISSUE THREAD

**Issue by Johnicholas** [brooklynjs/brooklynjs.github.io#518]
## BrooklynJS Talk Submission

**Talk Title:** Software Evolution and Other People's Ideas

**Talk Description:** How to make changes to a running (model of) a microservices-based architecture without breaking it (probably) and how taking care of other people's ideas is crucial to software evolution.

**Name**: Johnicholas Hines

**Preferred Pronouns**: he/him

**Twitter Handle (optional)**: @johnicholas

**Website (optional):** www.johnicholas.com

**Months Available to Speak:** November, December, January

**Comment by paladique** [comment]
@Johnicholas thank you for your submission! Your talk was not included in this month's lineup, but we have a firsties ticket for you! Email organizers@brooklynjs.com for details

**Comment by modernserf** [comment]
👋 @Johnicholas your talk has been accepted this month! You'll receive an email with details shortly.

**Comment by Johnicholas** [comment]
Great, thanks!
