### ISSUE TITLE
[Talk Proposal] Single source of truth: How I tried to write docs and built a compiler instead

### ISSUE THREAD

**Issue by kilmc** [brooklynjs/brooklynjs.github.io#519]
## BrooklynJS Talk Submission

**Talk Title:**
Single source of truth: How I tried to write docs and built a compiler instead

**Talk Description:**
It all started out so innocently. I just wanted a way to easily document our new Atomic CSS library at work. But the more I thought about the docs, the more I realized I could do if I was just able to capture that naming convention in code. Over the course of two years I slowly worked on building an ecosystem of tools powered by a single config that could do everything from generating docs, to generating CSS, to filtering out old unused code and way more.

This talk is about the power of naming conventions, the delightful wonder that are config files and my journey from barely knowing how to write a console.log() to kinda building a compiler, all because this idea was so juicy and so exciting that I couldn't let it go.

**Name**: Kilian McMahon

**Preferred Pronouns**: He/Him

**Twitter Handle (optional)**: [kilmc](https://twitter.com/kilmc)

**Website (optional):** [kilmc.com](http://kilmc.com)

**Months Available to Speak:** November, January, February

**Comment by paladique** [comment]
👋  @kilmc Thank you for your submission! Your talk is in this month's lineup! You'll get an email with details soon!
