### ISSUE TITLE
DevTools just got a DVR!

### ISSUE THREAD

**Issue by jasonLaster** [brooklynjs/brooklynjs.github.io#521]
## BrooklynJS Talk Submission

**Talk Title:**  DevTools just got a DVR!

**Talk Description:**

The year is 1999 and DVR, a magical device that gives you the power to pause and rewind live TV, was just released. You can now get a snack, rewind, and not miss a thing. 

This past summer, Firefox landed the ability to record and replay tabs in Nightly, which lets you rewind in real-time and jump to console messages. I can’t wait to share it with you!

**Name**: Jason Laster

**Preferred Pronouns**:  He/Him

**Twitter Handle (optional)**: jasonlaster11

**Months Available to Speak:** November, December, January. We're trying to figure out our MVP and it'd be great to get feedback.

**Comment by paladique** [comment]
@jasonLaster your talk has been accepted for this month's lineup! 🎉 you'll get an email from us with details soon

**Comment by jasonLaster** [comment]
would it be possible to pass on january?

**Comment by paladique** [comment]
@jasonLaster your talk was selected for this month's lineup, an email with details will be in your inbox soon!
