### ISSUE TITLE
Community Building as Self Care

### ISSUE THREAD

**Issue by gwengrid** [brooklynjs/brooklynjs.github.io#522]
## BrooklynJS Talk Submission

**Talk Title:**
Community Building as Self Care 

**Talk Description:**
How can we take better care of our communities and ourselves?  Everyday, we participate in so many communities, whether it be work, family life, social circles, shared interest groups, or even just the local neighborhood coffee shop.  Our needs are filled by these interdependent bonds, and as such, taking care of ourselves and our communities is one and the same question.  This talk goes into how we can build a greater sense of belonging and ownership in our communities as a means for self-care, and what that specifically can look like in our tech communities.

**Name**: 
Gwendolyn Weston

**Preferred Pronouns**:
 she/her

**Twitter Handle (optional)**: 
purpleyay

**Website (optional):** 
gwendolyn.io

**Months Available to Speak:** ~November, December, January~ April, May, June

**Comment by paladique** [comment]
👋 @gwengrid your talk has been accepted this month! 🎉 You'll receive an email with details shortly.

**Comment by modernserf** [comment]
hi @gwengrid! if you're available this month, we'd love to have you speak. We'll send you updated information shortly.

**Comment by paladique** [comment]
Closing this for a future date.
