### ISSUE TITLE
Budget hasn't been updated since June

### ISSUE THREAD

**Issue by jed** [brooklynjs/brooklynjs.github.io#523]
we really should get this up-to-date for BrooklynJS's birthday this THU. @brianloveswords, can you take an hour to get this in order by THU so we can go through it a boroughgramming?

**Comment by brianloveswords** [comment]
@jed done

**Comment by jed** [comment]
awesome, thanks @brianloveswords. and the total donated over five years is...

.
.
.

```82635.75000000001```

**Comment by brianloveswords** [comment]
that `.00000000001` is really what makes all the difference, that's the the real change-maker

**Comment by willmanduffy** [comment]
decimaul'd
