### ISSUE TITLE
How To Open Source Your Body

### ISSUE THREAD

**Issue by mannynotfound** [brooklynjs/brooklynjs.github.io#526]
## BrooklynJS Talk Submission

**Talk Title:**
How To Open Source Your Body

**Talk Description:**
An educational tutorial / post mortem of sorts describing the process of 3d scanning my body, turning that into a web accessible format, and then distributing myself through the npm ecosystem as the package "manny". I will also probably touch on my background in web based art and how developer tools can be used creatively.

**Name**:
Manny404

**Preferred Pronouns**:
He/Him

**Twitter Handle (optional)**:
@mannynotfound

**Website (optional):**
http://art404.com
http://mannynotfound.github.io/

**Months Available to Speak:** Maybe December depending on date but definitely January, February, March

**Comment by modernserf** [comment]
👋 @mannynotfound Thank you for your submission! Your talk has been accepted this month, and we'll send you the details shortly.
