### ISSUE TITLE
How to (Mostly) Maintain your Sanity as a Front-end Engineer

### ISSUE THREAD

**Issue by saimonsharif** [brooklynjs/brooklynjs.github.io#528]
## BrooklynJS Talk Submission

**Talk Title:** How to (Mostly) Maintain your Sanity as a Front-end Engineer

**Talk Description:**
The JavaScript ecosystem, _e.g._ the language itself, libraries, packages, frameworks, etc, seem to evolve at a lightning pace. It’s practically impossible to stay up to date on every single new feature, and it seems like there’s a new hot framework or library every few months, _e.g._ TypeScript, MobX, Next.js, Prisma, Hooks, Suspense, etc. This talk’s thesis is that you don’t actually have to stay up to date. On the other hand, the goal isn’t to become front-end ostriches, _i.e._ bury our heads in the sand and ignore every new feature. Rather, we can try to cultivate a balanced approach to continuously learning about the ecosystem, and thoughtfully adopting specific features.

I'll share the system I’ve developed to determine what’s worth learning at a surface level, and what is worth learning deeply; resources to actually learn a topic; and how to play catch up when needed. I’ll also talk briefly about strategies for adopting newer features in production codebases at work.

**Name**: Saimon Sharif

**Preferred Pronouns**: He / Him

**Twitter Handle (optional)**: saimonsharif

**Website (optional):**

**Months Available to Speak:** December 2018, January 2019, February 2019

**Comment by paladique** [comment]
👋 @saimonsharif your talk has been accepted this month! You'll receive an email with details shortly.

**Comment by paladique** [comment]
@saimonsharif turns out we don't have your email! Could you email organizers@brooklynjs.com so we can get details sent to you? Thanks!

**Comment by saimonsharif** [comment]
@paladique Thank you! Sure thing - I just sent an email :)
