### ISSUE TITLE
Solved With Pseudo Elements

### ISSUE THREAD

**Issue by coryetzkorn** [brooklynjs/brooklynjs.github.io#529]
## BrooklynJS Talk Submission

**Talk Title:** Solved With Pseudo Elements

**Talk Description:** Unleash the power of pseudo elements to build complex UI without relying on images or JavaScript. Content will be similar to this CSS Tricks post, but updated for 2018: https://css-tricks.com/pseudo-element-roundup/

**Name**: Cory Etzkorn

**Preferred Pronouns**: He / Him

**Twitter Handle (optional)**: coryetzkorn

**Website (optional):** https://www.coryetzkorn.com/

**Months Available to Speak:** Dec 2018, Jan 2019, Feb 2019

**Comment by paladique** [comment]
👋 @coryetzkorn Thank you for your submission! Your talk has been accepted this month! You'll receive an email with details shortly.
