### ISSUE TITLE
Deno Talk for January? 

### ISSUE THREAD

**Issue by ry** [brooklynjs/brooklynjs.github.io#531]
## BrooklynJS Talk Submission

**Talk Title:** Deno a new JavaScript runtime

**Talk Description:** I will give an introduction to Deno: https://deno.land/

**Name**: Ryan Dahl

**Preferred Pronouns**: He

**Twitter Handle (optional)**:

**Website (optional):** https://tinyclouds.org

**Months Available to Speak:** January 17

**Comment by ry** [comment]
Oops - never mind - i can't make it! I'll try again next year.

**Comment by brianloveswords** [comment]
Looking forward to it! If you know whether you can make it on Jan 17th, Feb 21st or March 21st feel free to leave this open and change your “Months Available to Speak” to any/all of those.

**Comment by modernserf** [comment]
👋 welcome back, @ry! we'll email you with the details shortly.
