### ISSUE TITLE
Return of the Script Tag

### ISSUE THREAD

**Issue by phdesign** [brooklynjs/brooklynjs.github.io#533]
## BrooklynJS Talk Submission

**Talk Title:**
Return of the Script Tag

**Talk Description:**
For the last decade we've been fighting the use of script tags, bundling our code to reduce the number of assets we need to download from the server, hoping all the while to avoid the dreaded limit of 6 simultaneous downloads from a single domain. But times have changed and with the widespread adoption of HTTP/2 and native ES6 browser modules it's time we re-embraced our script tags, load all our source files individually giving us the freedom to cast off those fragile front end build systems and really leverage browser caching to it's fullest.

**Name**:
Paul Heasley / @phdesign

**Preferred Pronouns**:
He / Him

**Twitter Handle (optional)**:
[@pheasley](https://twitter.com/@pheasley)

**Website (optional):**
http://phdesign.com.au

**Months Available to Speak:** 
January, February, March and onwards...

**Comment by modernserf** [comment]
👋 @phdesign your talk has been accepted this month! can you email us at organizers@brooklynjs.com so we can send you the details?
