### ISSUE TITLE
Santa Tracker showcase 🎅🎯

### ISSUE THREAD

**Issue by samthor** [brooklynjs/brooklynjs.github.io#536]
## BrooklynJS Talk Submission

**Talk Title:**
Santa Tracker showcase 🎅🎯

**Talk Description:**
Every year, Google's Web DevRel team builds and releases Santa Tracker, a holiday-themed experience for all of Dec, and which primarily features tracking Santa on the 24th. This talk will showcase some history, how we build it, interesting learnings, and where Santa is going in the future (maybe... to your house to deliver presents!).

Santa is a huge single-page application built with Web Components, with heaps of historic HTML/JS, served to millions+ of users, and is going through [a tricky rewrite](https://dev.to/chromiumdev/the-gift-of-giving-up-1lgl). 

**Name**:
Sam Thorogoood

**Pronouns**:
He / Him

**Twitter Handle (optional)**:
@samthor

**Website (optional):**
https://whistlr.info

**Months Available to Speak:**
Jan 17th only

**Comment by modernserf** [comment]
@samthor Thank you for your submission! Your talk has been accepted this month, and we'll send you the details shortly.
