### ISSUE TITLE
The Weekender: Unofficial HD Remaster

### ISSUE THREAD

**Issue by louh** [brooklynjs/brooklynjs.github.io#537]
## BrooklynJS Talk Submission

**Talk Title:** : The Weekender: Unofficial HD Remaster

**Talk Description:**  Originally released in 2011, the Weekender website is one of the MTA's few official works using the iconic Massimo Vignelli map from the 1970s, and a brilliant digital adaptation of the subway system's classic wayfinding sign system, but it's now showing its age as technologies have evolved quickly and users' expectations of digital experiences become ever more sophisticated. In this unofficial "HD remaster," civic technologist Lou Huang shows how a digital product can stay relevant, useful, and beautiful with steady refinement and upgrades to adapt to changing requirements over long periods of time.

**Name**: Lou Huang

**Pronouns**: he/him

**Twitter Handle (optional)**: saikofish (optional)

**Website (optional):** https://weekender.netlify.com/

**Months Available to Speak:** February but also possibly flexible

**Comment by paladique** [comment]
@louh 👋  you've been selected for this month's lineup 🎉! We'll be sending you details via email soon!
