### ISSUE TITLE
Data Visualization in React that doesn't require D3.js (React-Vis and Chart.js)

### ISSUE THREAD

**Issue by JBhagat841** [brooklynjs/brooklynjs.github.io#538]
## BrooklynJS Talk Submission

**Talk Title:**
Data Visualization in React that doesn't require D3.js (React-Vis and Chart.js)

**Talk Description:**

It's no secret that React and D3.js don't play well together when you're looking for user interaction and animation in your data visualization. I want to give a talk about how to easily do your first data visualization based on using React-Vis and Chart.js.

I understand that Tanner stopped by last year to give a talk on Chart.js based on the suggested PR that popped up when I wrote this. I would be giving more of a practitioner perspective of issues I faced rendering charts using 3rd party API's, building a full stack application and alternatives to using React lifecycle methods to re-render charts if you're working with real-time data or want users to change charts inside of a single-page app.

**Name**:

Jay Bhagat

**Pronouns**:

He/Him

**Twitter Handle (optional)**:

@JayBhagat24

**Website (optional):**

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!

February and March

**Comment by paladique** [comment]
@JBhagat841 Your talk has been selected for this month's lineup! 🎉 Could you please email organizers@brooklynjs.com so we can pass along some additional speaker info? Thank you!
