### ISSUE TITLE
Will the IDE of the future be in your browser?

### ISSUE THREAD

**Issue by wylieconlon** [brooklynjs/brooklynjs.github.io#539]
## BrooklynJS Talk Submission

**Talk Title:** Will you be writing code in your browser in the future?

**Talk Description:**

A new generation of online developer tools aims to replace your IDE with a web app. Are they succeeding? Will these tools be "VSCode in your browser," or will a more diverse set of tools emerge? We will compare specialized and general-purpose development environments in the browser for use today, and look at upcoming libraries and browser technology that might make these tools better in the future. I will also preview some of my work to build a more diverse set of coding tools in the browser.

**Name**: Wylie Conlon

**Pronouns**: He/Him

**Twitter Handle (optional)**: wylieconlon

**Website (optional):** [wylie.su](http://wylie.su)

**Months Available to Speak:** February/March/April

**Comment by paladique** [comment]
Hi @wylieconlon! your talk wasn't selected for this month, but please reach out to organizers@brooklynjs.com if you'd like to receive your firsties ticket!

**Comment by paladique** [comment]
Hi @wylieconlon! Your talk was accepted this month! An email will be on its way soon!
