### ISSUE TITLE
React Hooks for React Users

### ISSUE THREAD

**Issue by jsocol** [brooklynjs/brooklynjs.github.io#540]
## BrooklynJS Talk Submission

**Talk Title:** React Hooks for React Users

**Talk Description:**

React Hooks, which have generated a ton of excitement and conversation on Twitter the past few weeks/months, are here, in 16.8, out today! So I guess it's time I went out and learned what they are, and started understanding how to use them.

I plan to cover an introduction to Hooks, particularly from the point of view of someone who's familiar with existing react paradigms, and how you might start using them, replace existing tools, or what potentially new things they'd enable that existing options for things like lifecycle and state management didn't.

**Name**: James Socol

**Pronouns**: he/him

**Twitter Handle (optional)**: [@jamessocol](https://twitter.com/jamessocol)

**Website (optional):** https://jamessocol.com

**Months Available to Speak:** February, March, April

**Comment by paladique** [comment]
Hi @jsocol!  your talk wasn't selected for this month, but reach out to [organizers@brooklynjs.com](mailto:organizers@brooklynjs.com) if you'd like to receive your firsties ticket!

**Comment by jsocol** [comment]
Oh good 😅. Will do!

**Comment by paladique** [comment]
@jsocol your talk has been accepted this month! 🎉 An email with details is on its way.
