### ISSUE TITLE
GraphQL: To Apollo or Not

### ISSUE THREAD

**Issue by kvohra3** [brooklynjs/brooklynjs.github.io#541]
## BrooklynJS Talk Submission

**Talk Title:**
GraphQL: To Apollo or Not

**Talk Description:**
The basic advantages of using GraphQL are plain to see. But how do you move an existing application across and what decisions are made?

Our company builds a widely used customer facing website. We have made the decision to migrate to a GraphQL interface. We shall present a case study of our initial migration, the decisions, the discoveries and arguments for and against GraphQL. When you have an existing revenue generating product you have to justify technology change. We will present our case and describe what technologies we choose and why.

**Name**:
Karan Vohra
Glenn Hinks

**Months Available to Speak:** 
All

**Comment by paladique** [comment]
Hi @kvohra3! your talk wasn't selected for this month, but please reach out to [organizers@brooklynjs.com](mailto:organizers@brooklynjs.com) if you'd like to receive your firsties ticket!

**Comment by paladique** [comment]
👋 Thank you for your submission, your talk was not included this month, but if you would like to be considered for any additional available months let us know. If you'd like to propose a new talk, feel free to submit another issue.
