### ISSUE TITLE
Speaker Opportunity

### ISSUE THREAD

**Issue by troutman21** [brooklynjs/brooklynjs.github.io#542]
## BrooklynJS Talk Submission

**Talk Title:**
Getting Hooked on React

**Talk Description:**
In this talk we will get a quick look at one of React's newest feature React Hooks! 

**Name**:
Philllip Troutman
**Pronouns**:
he 
**Twitter Handle (optional)**:
_Troutman_
**Website (optional):**

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
-February (following months are TBD)

**Comment by paladique** [comment]
Hi @troutman21! Your talk wasn't selected for this month, and your future months are TBD so I will close this issue for now. Let us know when your availability clears up for upcoming months, or feel free to submit a new issue.  

Reach out to [organizers@brooklynjs.com](mailto:organizers@brooklynjs.com) if you'd like a firsties ticket!
