### ISSUE TITLE
Keeping 100% Lighthouse score around the world

### ISSUE THREAD

**Issue by Zizzamia** [brooklynjs/brooklynjs.github.io#543]
## BrooklynJS Talk Submission

**Talk Title:**
Keeping 100% Lighthouse score around the world

**Talk Description:**
Performance is crucial to designing a delightful user experience. Yet even products with a 100% Lighthouse score often fall short in some regions of the world. You can determine your performance worldwide by measuring field data with Real User Monitoring (RUM) via Perfume.js. In this talk we’ll study how we use Perfume.js at Coinbase to maximize our performance around the globe.  

**Name**:
Leonardo Zizzamia

**Pronouns**:
He/Him

**Twitter Handle (optional)**:
https://twitter.com/zizzamia

**Website (optional):**
https://medium.com/@zizzamia

**Months Available to Speak:**
I'll be visiting NYC in April between the 14th and 18th :-)

**Comment by Zizzamia** [comment]
Ops, I wrote the wrong month 😅. I meant to say April instead of May.

**Comment by paladique** [comment]
Thank you for letting us know 😃

**Comment by paladique** [comment]
@Zizzamia your talk has been accepted for this month's lineup 🎉! You'll get an email soon with speaker details and ticket.
