### ISSUE TITLE
2FA, TOTP, WTF?!

### ISSUE THREAD

**Issue by robinske** [brooklynjs/brooklynjs.github.io#544]
## BrooklynJS Talk Submission

**Talk Title:**
2FA, TOTP, WTF?!

**Talk Description:**
You may recognize Two-factor Authentication (2FA) as an additional safeguard for protecting accounts, but do you really know how it works? This talk will show you how to implement Time-based One Time Passwords (TOTP) and explain what's happening under the hood of those expiring tokens. You'll learn the different approaches to implementing 2FA and have a better understanding of what's right for your application.

**Name**:
Kelley Robinson

**Pronouns**:
she/her/hers

**Twitter Handle (optional)**:
[@kelleyrobinson](https://twitter.com/kelleyrobinson)

**Website (optional):**
https://www.krobinson.me/

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
March, April

**Comment by paladique** [comment]
@robinske your talk has been accepted for this month's lineup! 🎉 could you please email organizers@brooklynjs.com for details? Thanks!
