### ISSUE TITLE
Dreaming To Doing: How to Level up  in Life & Tech 

### ISSUE THREAD

**Issue by copasetickid** [brooklynjs/brooklynjs.github.io#545]
## BrooklynJS Talk Submission

**Talk Title:**  Dreaming To Doing: How to Level up  in Life & Tech 

**Talk Description:**   From S.M.A.R.T. Goals to productive hacks.
The same way we build systems at work is how we should think about achieving the goals we have in or hobbies we have.   The process is more important than the goal and we should look at how building good habits will make you 1% better each day. In this talk I'll talk about how creating better systems for ourselves will allow you to focus on improving skills that result in you becoming who you want in life and tech. 

**Name**: Rushaine McBean

**Twitter Handle (optional)**: @copasetickid  

**Months Available to Speak:** March, May

_We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!_

**Comment by paladique** [comment]
Hi @copasetickid  Your talk has been accepted for this month's lineup! An email with details is on the way
