### ISSUE TITLE
This Is Your Code On Concerns

### ISSUE THREAD

**Issue by phyllisstein** [brooklynjs/brooklynjs.github.io#547]
## BrooklynJS Talk Submission

**Talk Title:**
This Is Your Code On Concerns :fried_egg:

**Talk Description:**
Microservices architectures are ridiculous until they're not. Teams grow; repos expand; dependencies multiply; contracts blur---at a certain point, the need to do one thing in several places becomes both too valuable and too expensive for copy-paste coding. What's worse, the evolution of tooling beyond `npm link` keeps bringing that point closer and closer to `git init`.

Through a discussion of two React/Redux codebases and a live coding example, I'd like to talk about the messiest part of adopting microservices: making judgment calls about the boundaries between concerns. I'd like to describe the product-oriented approach my team evolved for divvying up the responsibilities of our libraries and services, and how componentization with React and modularization with Webpack and Node made it possible to move past concerning ourselves with the stack.

Rachael Leigh Cook's fabulous 1997 _This Is Your Brain On Drugs_ PSA furnishes a title and a framing device. If accepted, you have my solemn promise that my talk will not involve wreckin' up the joint.

**Name**:
Daniel P. Shannon

**Pronouns**:
He/Him

**Twitter Handle (optional)**:
[`@phyllisstein`](https://twitter.com/phyllisstein)

**Website (optional):**
TK

**Months Available to Speak:**
April/May/June

**Comment by paladique** [comment]
@phyllisstein 👋 Thank you for your submission, your talk was not included this month, but we have a ticket set aside for you for your submission! Email organizers@brooklynjs.com if you'd like one for this Thursday.

**Comment by paladique** [comment]
@phyllisstein Thanks so much for your submission! Your talk has been accepted 🎉 speaker details will be coming soon via email!

**Comment by phyllisstein** [comment]
![poisson](https://user-images.githubusercontent.com/2207980/57262780-a67b7180-703b-11e9-86ac-f91afbb6ff8c.gif)


Thank you so much, I'm excited and terrified!
