### ISSUE TITLE
Building your own Snapshot Testing Suite

### ISSUE THREAD

**Issue by sbernheim4** [brooklynjs/brooklynjs.github.io#548]
## BrooklynJS Talk Submission

**Talk Title:**
Building your own Snapshot Testing Suite

**Talk Description:**
Snapshot testing is one of the best ways to ensure that your UI doesn't change unexpectedly but is often considered only as an afterthought. Complaints of its difficultly to implement, manage, and maintain abound, despite its usefulness in ensuring that unrelated updates don't inadvertently change the UI. Despite its benefits, most people ignore snapshot testing completely and the few who don't simply outsource it. In this talk I'll go over how to build your own snapshot testing suite that can easily be integrated into your CI/CD pipeline.

**Name**:
Samuel Bernheim 

**Pronouns**:
He/Him

**Twitter Handle (optional)**:
N/A

**Website (optional):**
[sambernheim.tech](sambernheim.tech)

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
April, May

**Comment by sbernheim4** [comment]
Hello, just wanted to know if my talk has been accepted for this month. Thanks, Sam

**Comment by paladique** [comment]
@sbernheim4 sorry for the delay, happy to have you in this month's lineup 🎉 can you please email organizers@brooklynjs.com for more details?
