### ISSUE TITLE
Let's code a Virtual DOM library from scratch!!

### ISSUE THREAD

**Issue by nirkaufman** [brooklynjs/brooklynjs.github.io#549]
## BrooklynJS Talk Submission

**Talk Title:**
Let's code a Virtual DOM library from scratch!!

**Talk Description:**
The virtual DOM is the beating heart of many modern frontend frameworks today. While the concept of how it works is straightforward, the only way to understand it is to build one! During this talk, I will live code a tiny lightweight VDOM library from scratch and explore the idea and concepts behind is.

**Name**:
Nir Kaufman

**Pronouns**:

**Twitter Handle (optional)**:
@nirkaufman

**Website (optional):**

**Months Available to Speak:** 
March, April, Most of June

**Comment by maximforever** [comment]
Just wanted to chime in to say this sounds awesome!

**Comment by paladique** [comment]
@nirkaufman 👋  your talk has been accepted for this month. Details coming soon via email!

**Comment by nirkaufman** [comment]
Cool!
Which date?
Didn't receive any email...
*Nir Kaufman*
*Google Developer Expert
<https://developers.google.com/experts/people/nir-kaufman> for web
technologies.*
*Principal consultant at 500Tech.com <http://500tech.com/>*

**Comment by paladique** [comment]
Hi! I used the same email that we chatted with a few months ago on Monday. The one on your profile. I'll resend it
