### ISSUE TITLE
Talk Proposal: Property Testing

### ISSUE THREAD

**Issue by glebec** [brooklynjs/brooklynjs.github.io#551]
## BrooklynJS Talk Submission

**Talk Title:** TBD (ideas below)

- The Magic of Generative Testing
- Let The System Write The Tests: Property Testing Basics

**Talk Description:** Property testing, aka generative testing, is an alternative to unit testing. Instead of manually specifying input and output cases, the developer specifies laws (aka properties) that should hold for _all_ expected input types. The system then **generates** many random inputs, **verifies** if the property holds in all cases, and **simplifies** failing inputs to find error boundaries. This talk will demonstrate the power, ease, and flexibility of property testing in JS.

**Name**: Gabriel Lebec

**Pronouns**: he/him

**Twitter Handle (optional)**: g_lebec

**Website (optional):** https://github.com/glebec

**Months Available to Speak:** April, May, June (or later)

**Comment by paladique** [comment]
@glebec 👋 Thank you for your submission, your talk was not included this month, but we have a ticket set aside for you for your submission! Email organizers@brooklynjs.com if you'd like one for this Thursday.

**Comment by paladique** [comment]
@glebec your talk has been accepted for this month! Could you please email organizers@brooklynjs.com for more details? Thanks!

**Comment by glebec** [comment]
@paladique I emailed that address on June 10 and June 11 with no response to date. Will email again now but I figured I should reach out here too.

**Comment by paladique** [comment]
So sorry! I didn't see this email somehow! I will send you details now.
