### ISSUE TITLE
Using audio for making habitats

### ISSUE THREAD

**Issue by amitlzkpa** [brooklynjs/brooklynjs.github.io#552]
## BrooklynJS Talk Submission

**Talk Title:**
Using audio for making habitats

**Talk Description:**
Architecture has often been used as a background for creating and experiencing music. This project looks to invert that relationship by using audio to create virtual 3D environments. Using VR these environments can be experienced as if one was inhabiting the environment.
The process of going from audio signals to a 3D environment involves deconstructing the audio into numbers which can be used as an input into parametric algorithms for creating 3D forms. Often the inspiration for such designs has been to express a relationship between an environment and other abstract concepts, supported by engineering and design to make the environments habitable and functional.
The ephermal medium of virtual environments remove the shackles of real world and allow for more experimental habitats and enjoyable experiences. The demo application explores a few such concepts by exposing parametric relationships established in architectural design but augmenting them to react to music in real time creating a dynamic music driven world.
Demo: [http://lotusaudio.herokuapp.com/](http://lotusaudio.herokuapp.com/)

**Name**:
Amit Nambiar

**Pronouns**:
He/Him

**Twitter Handle (optional)**:

**Website (optional):**
[https://amitnambiar.com](https://amitnambiar.com)
[http://lotusaudio.herokuapp.com/](http://lotusaudio.herokuapp.com/)

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
April/May

**Comment by paladique** [comment]
@amitlzkpa 👋 Thank you for your submission, your talk was not included this month, but we have a ticket set aside for you for your submission! Email organizers@brooklynjs.com if you'd like one for this Thursday.

**Comment by maximforever** [comment]
Just wanted to say that this is really cool!

**Comment by amitlzkpa** [comment]
Thanks! :)

**Comment by paladique** [comment]
@amitlzkpa  👋 Thanks so much for your submission, your talk has been accepted 🎉 Could you please email organizers@brooklynjs.com for more speaker details? Thanks!
