### ISSUE TITLE
Game Development with Phaser

### ISSUE THREAD

**Issue by mattConn** [brooklynjs/brooklynjs.github.io#553]
## BrooklynJS Talk Submission

**Talk Title:**
Game Development with Phaser

**Talk Description:**
My experience with simple game development using the JavaScript framework Phaser: implementing simple physics and a level/room rendering and design system.
Here's the basic game prototype I made a while ago which I would soup up for the talk if I was chosen: https://mattconn.dev/phaser-js-game/

**Name**:
Matthew Connelly

**Pronouns**:
He/Him

**Twitter Handle (optional)**:
mattconndev

**Website (optional):**
https://mattconn.dev/

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
April, May, June

**Comment by paladique** [comment]
@mattConn 👋 Thank you for your submission, your talk was not included this month, but we have a ticket set aside for you for your submission! Email organizers@brooklynjs.com if you'd like one for this Thursday.

**Comment by mattConn** [comment]
@paladique I can't make it tomorrow but thank you. Fingers crossed for my submission for next month!

**Comment by paladique** [comment]
@mattConn Thanks so much for your submission, your talk has been accepted 🎉 We will be emailing you soon with speaker details!
