### ISSUE TITLE
Painless End To End Testing with Cypress

### ISSUE THREAD

**Issue by YuanyuanMaggie** [brooklynjs/brooklynjs.github.io#554]
## BrooklynJS Talk Submission

**Talk Title:**
Painless End To End Testing with Cypress

**Talk Description:**
Testing is hard! But it could be fun! 
End to end testing could help us to test applications with the way users will interact. But there are challenges making it's hard to implement in practical development cycle:  1) it's complicated to setup, configure and integrate to CI/CD 2) Tests are flaky and painful to debug or maintain. 3) it takes long time to run all tests, etc. Fortunately, we now have Cypress, a faster, easier and reliable testing framework. By using Cypress, E2E testing can reduce time from 1 hour to 4 minutes and it's easy to integrated into CI/CD. 
In this talk, I will talk about good features/ limitations of Cypress and some tricks to make it faster and robust. 

**Name**: 
Yuanyuan Li

**Pronouns**:
She/Her

**Twitter Handle (optional)**:
@yl2577

**Website (optional):**
https://yuanyuanli.net/

**Months Available to Speak:**
May/July/Aug

**Comment by paladique** [comment]
@YuanyuanMaggie thanks for your submission! Your talk wasn't included in this month's lineup, but we have a ticket set aside for you. Please email organizers@brooklynjs.com for details.

**Comment by paladique** [comment]
@YuanyuanMaggie 👋 please let us know if you'd be interested in reopening this for future months!
