### ISSUE TITLE
Songmap: exploring a star map of songs with the Spotify API & three.js

### ISSUE THREAD

**Issue by maximforever** [brooklynjs/brooklynjs.github.io#555]
## BrooklynJS Talk Submission

**Talk Title:** 
Songmap: exploring a star map of songs

**Talk Description:** 
What would it be like to traverse a star map of songs? Clusters of stars could signify genres, or similar artists or albums. Directions could beckon you towards  more energetic, danceable music, or slower, calmer tracks; depth could take you across genre. This is a problem that inspired me to start coding years ago, and I've recently returned to it and [built a prototype](http://thesongmap.herokuapp.com) using the **Spotify API** and **three.js**. 

In this talk, I will demo the songmap, and introduce attendees to three.js, working with the Spotify API, and designing a creative UX to visualize and explore music listening preferences. I'll also emphasize the journey and failures in building this, and the iterative steps that took me from a wanna-be coder to the final product.

**Name**: 
Max Pekarsky

**Pronouns**: 
he/him

**Twitter Handle (optional)**: 
maxverse

**Website (optional):**
https://www.maximpekarsky.com
You can see a prototype at http://thesongmap.herokuapp.com/ (**NOTE:** _you'll need a premium Spotify subscription to access this. First, open your Spotify desktop app and play any track. Then, Songmap will be able to play songs through your app_ )

**Months Available to Speak:** May, June, July '19

**Comment by amitlzkpa** [comment]
Wasn't able to see the prototype. No errors in console either. Would love to check it out.

**Comment by maximforever** [comment]
@amitlzkpa thanks for checking out! weird, just tested on another computer and everything works. Are you getting any errors at all? a blank screen?

**Comment by amitlzkpa** [comment]
After trying once again I realized it worked after I liked the first song. Would be fun to fly around the nodes in 3D.

**Comment by maximforever** [comment]
@amitlzkpa thanks! I have some (kinda wonky) controls in place. I just added a `?` instructions modal to help others navigate the project. I also _love_ the simple mouse controls in your project, so I'll work to implement something similar here.

**Comment by amitlzkpa** [comment]
@maximforever They are simple [Orbit Controls](https://threejs.org/docs/#examples/controls/OrbitControls). Made something similar a little while ago for [exploring graphs](http://g3d.pythonanywhere.com/) (it takes a few seconds to update after you search).

**Comment by maximforever** [comment]
Hey @paladique! Just wondering when you generally announce the speakers for the upcoming BrooklynJS? It looks like the speakers for this round have been selected - would I still be considered for future months?

**Comment by paladique** [comment]
@maximforever That's correct: your talk wasn't included in this month's lineup, but we will consider the future months you've selected. We have a ticket set aside for in case you haven't gotten on yet. Please email organizers@brooklynjs.com for details. Thanks for your submission!

**Comment by maximforever** [comment]
Thanks, @paladique ! Just wanted to say, I won't be able to do July anymore, unfortunately, but would still love to speak in June!

**Comment by paladique** [comment]
@maximforever Gotcha! Thanks for the heads up! 🙏

**Comment by paladique** [comment]
@maximforever your talk has been accepted! 🎉 Speaker details coming soon via email!
