### ISSUE TITLE
Writing Javascript in Haskell!

### ISSUE THREAD

**Issue by vaibhavsagar** [brooklynjs/brooklynjs.github.io#556]
## BrooklynJS Talk Submission

**Talk Title:**
Writing Javascript in Haskell!

**Talk Description:**
Haskellers can be pretty smug about our language of choice, but this quickly stops when you ask us how we write applications for a web browser. In fact, there's a page on the Haskell wiki imaginatively titled [The JavaScript Problem](https://wiki.haskell.org/The_JavaScript_Problem) that catalogues different approaches. Ideally we would be able to write Haskell, magic would happen, and it would run on the browser with no further effort from us.

In this talk I'll discuss the good (and bad) reasons we have for wanting this, some of the progress we've made towards this goal, and what we have to look forward to!

**Name**:
Vaibhav Sagar

**Pronouns**:
he/him

**Twitter Handle (optional)**:
vbhvsgr

**Website (optional):**
https://vaibhavsagar.com

**Months Available to Speak:**
June, July, August, onwards :smile:

**Comment by paladique** [comment]
@vaibhavsagar thank you for your submission! Your talk wasn't accepted in this month's lineup, but we have a ticket set aside for you! Please email organizers@brooklynjs.com for details.

**Comment by paladique** [comment]
Thanks so much for your submission and stepping in to come speak on such short notice!
