### ISSUE TITLE
The Future of Open Source

### ISSUE THREAD

**Issue by ehashman** [brooklynjs/brooklynjs.github.io#557]
## BrooklynJS Talk Submission

**Talk Title:** The Future of Open Source

**Talk Description:** Just 20 years ago, the term "open source" didn't even exist. The majority of industry software was sold in binary form, and the idea of building a business by giving away source code for free was inconceivable when the richest man in the world, Bill Gates, had built his business, Microsoft, on selling proprietary software. But 20 years later, "[open][1] [source][2] [has][3] [won][4]": the majority of the tech industry runs on open source software, and even Microsoft has joined the movement, [acquiring][5] and contributing to the largest open source development platform in the world!

[1]: https://www.wired.com/2016/08/open-source-won-now/
[2]: https://www.computerworld.com/article/3144063/open-source-has-won-and-microsoft-has-surrendered.html
[3]: https://www.zdnet.com/article/linux-and-open-source-have-won-get-over-it/
[4]: https://osjournal.com/open-source-has-won-now-it-needs-to-remain-vigilant-299/
[5]: https://blogs.microsoft.com/blog/2018/06/04/microsoft-github-empowering-developers/

But if open source has won, do we still need an open source movement? How can we, as a community, grapple with the challenges of sustainable development practices and ethical use of freely released software? In this talk, I'll ponder some of these questions, and propose a vision for the future of the open source software community.

Note: I am a Director on the Open Source Initiative's Board. However, this talk is proposed in a personal capacity, and I do not speak on behalf of the OSI.

**Name**: Elana Hashman

**Pronouns**: she/her

**Twitter Handle (optional)**: @ehashdn

**Website (optional):** https://hashman.ca

**Months Available to Speak:** May 2019

**Comment by paladique** [comment]
@ehashman your talk has been accepted! 🎉 We'll be reaching out soon with speaker details!
