### ISSUE TITLE
Learning from the Perspective of a Teacher and Engineer

### ISSUE THREAD

**Issue by maxcell** [brooklynjs/brooklynjs.github.io#558]
## BrooklynJS Talk Submission

**Talk Title:**
_Learning from the Perspective of a Teacher and Engineer_

**Talk Description:**
The saying, “Those who can, do; those who can't, teach”, is pretty off. Great developers are able to understand concepts well enough to share their knowledge with others effectively. The Web is an ever-expanding piece of technology, and we will have to adapt by learning more and more new tools that can enhance experiences for users. We will constantly be living between feeling like we know nothing and feeling like we know everything there is to know. However, every so often we will come across tools that we have been able to master. Along with a feeling of accomplishment, we may want to share that knowledge with others. This talk will explain the science around learning, tools for getting the most out of our learning, and how we can empower others to learn from and with us.

**Name**: Prince Wilson

**Pronouns**: He/Him

**Twitter Handle (optional)**: @maxcell

~**Website (optional):**~

**Months Available to Speak:** May

**Comment by paladique** [comment]
@maxcell Thanks so much for your submission, your talk has been accepted 🎉 Could you please email organizers@brooklynjs.com for more speaker details? Thanks!
