### ISSUE TITLE
Mentoring the way to a diverse and inclusive workplace

### ISSUE THREAD

**Issue by halfghaninne** [brooklynjs/brooklynjs.github.io#559]
## BrooklynJS Talk Submission

**Talk Title:**
Mentoring the way to a diverse and inclusive workplace

**Talk Description:**
Often, the endeavors of hiring and mentoring junior engineers and of bolstering diversity and inclusion efforts are seen as “nice to haves” at best and “extraneous” (or even “impossible”!) at worst. But in reality, building diversity and inclusivity and fostering the ability to incorporate junior engineers go hand-in-hand. Engineering teams should approach each of these efforts in service of the other.

Together, we'll articulate the value of investing in mentorship efforts in terms of their impact on the ability to attract and retain diversity. You will walk away with a clearer understanding of the connection between the two efforts, and ideas for incorporating mentorship and D&I processes at your place of work.

**Name**:
Alex Millatmal

**Pronouns**:
she/her

**Twitter Handle (optional)**:
[@halfghaninNE](https://twitter.com/halfghaninNE)

**Website (optional):**
[alexandramillatmal.com](https://www.alexandramillatmal.com/)

**Months Available to Speak:** May and July, '19 (May preferred).

**Comment by paladique** [comment]
@halfghaninne 👋  thanks for your submission! Your talk wasn't included in this month's lineup, but we have a ticket set aside for you. Please email organizers@brooklynjs.com for details.

**Comment by paladique** [comment]
@halfghaninne your talk has been accepted! We'll be emailing you details soon!
