### ISSUE TITLE
Networking: What you don't need to know as a developer, but probably should.

### ISSUE THREAD

**Issue by jhaff** [brooklynjs/brooklynjs.github.io#560]
## BrooklynJS Talk Submission

**Talk Title:** Networking: What you don't need to know as a developer, but probably should.

**Talk Description:** As frontend (and even backend) developers, we really only need to concern ourselves with the Application Layer (layer 7 of the OSI model and where HTTP resides). But what goes on at the lower layers, particularly those involved with routing and transport is fascinating and helps us have a greater understanding of how the web works. It's how we're able to serve a website to the world, hit an API, and even pair program with our boss.

**Major topics:**
- What's a network?
- Routing
- MAC addresses and IP addresses
- DNS
- TCP vs UDP
- Ping

**Minor, fun topics:**

- Duplexing

**Name**: Jacob Haff

**Pronouns**: He, Him, His

**Twitter Handle (optional)**:

**Website (optional):**

**Months Available to Speak:** May, June

**Comment by paladique** [comment]
@jhaff thanks for your submission! Your talk wasn't included in this month's lineup, but we have a ticket set aside for you. Please email organizers@brooklynjs.com for details.

**Comment by paladique** [comment]
@jhaff thanks for your submission! Your talk wasn't included in this month's lineup, but let us know if you'd like to reopen this for future months!

**Comment by jhaff** [comment]
Okay! I've been meaning to revise/resubmit anyway. I can't make it next
week but I'm going to plan to for August :)

Jacob Haff
