### ISSUE TITLE
Intuitive APIs with TypeScript

### ISSUE THREAD

**Issue by jakelazaroff** [brooklynjs/brooklynjs.github.io#561]
## BrooklynJS Talk Submission

**Talk Title:**
Intuitive APIs with TypeScript

**Talk Description:**
TypeScript is great for writing safe code, but honestly who wants to write a bunch of boilerplate type code in like every other file. There's gotta be a way to get nice autocomplete and type info WITHOUT totally changing how we write code, right?? (spoiler alert: yes) This talk will explore how we can use TypeScript features like [intersections](https://www.typescriptlang.org/docs/handbook/advanced-types.html#intersection-types) and [generics](https://www.typescriptlang.org/docs/handbook/generics.html) alongside more general programming patterns to make really nifty APIs ✨.

**Name**:
Jake Lazaroff

**Pronouns**:
he/him

**Twitter Handle (optional)**:
jlazaroff

**Website (optional):**
[jake.nyc](https://jake.nyc)

**Months Available to Speak:**
June/July/August

**Comment by paladique** [comment]
@jakelazaroff Thank you for your submission! Your talk wasn't included in this month's lineup but we have a ticket set aside for you! Please email organizers@brooklynjs.com for details!

**Comment by jakelazaroff** [comment]
Sorry, just realized I can't make it this month. August still works though!

**Comment by paladique** [comment]
@jakelazaroff your talk has been accepted! You'll be receiving an email with details soon.
