### ISSUE TITLE
Test Flakiness - Methods for identifying and dealing with flaky tests

### ISSUE THREAD

**Issue by palmerj3** [brooklynjs/brooklynjs.github.io#562]
## BrooklynJS Talk Submission

**Talk Title: Test Flakiness - Methods for identifying and dealing with flaky tests**

**Talk Description: Understand what test flakiness is, the impact it has, and how to overcome it.**

**Name**: Jason Palmer

**Pronouns**: He/him

**Twitter Handle (optional)**: palmerj3

**Website (optional):**

**Months Available to Speak:** June, July, August.

**Comment by paladique** [comment]
@palmerj3 Thank you for your submission! Your talk wasn't included in this month's lineup but we have a ticket set aside for you! Please email organizers@brooklynjs.com for details!

**Comment by paladique** [comment]
@palmerj3 your talk has been accepted! For details and your speaker ticket, please email  organizers@brooklynjs.com
