### ISSUE TITLE
blokdots – A New Hardware Prototyping Tool

### ISSUE THREAD

**Issue by olivierbrcknr** [brooklynjs/brooklynjs.github.io#563]
## BrooklynJS Talk Submission

**Talk Title:** blokdots – A New Hardware Prototyping Tool

**Talk Description:** Nowadays, products with electronic features are being used in every part of our lives. Like all products, these need to be tested as well. When designing them, this is where it comes to electrical engineering and programming – skills not all designers and product developers possess. However, especially in the early stages of product development, it is important to test if an idea works. 

[blokdots](http://blokdots.com) is solving this problem by providing a professional but at the same time easy-to-use tool for physical prototyping, that supports designers during all stages of development.

**Name**: Olivier Brückner

**Pronouns**: He / him / his

**Twitter Handle (optional)**: @olivierbrcknr

**Website (optional):** https://olivierbrueckner.de/ — https://blokdots.com/

**Months Available to Speak:** In NY from the 15th to the 21st of June, so only this would work for me

**Comment by paladique** [comment]
@olivierbrcknr thanks for your submission. Your talk has been accepted! I couldn't locate an email for you, so could you email organizers@brooklynjs.com so we may pass on more details? Thanks!!
