### ISSUE TITLE
Getting Out of The Tar Pit

### ISSUE THREAD

**Issue by WojciechMigda** [brooklynjs/brooklynjs.github.io#564]
## BrooklynJS Talk Submission

**Talk Title:**
Getting Out of The Tar Pit

**Talk Description:**
In this talk I will present brief overview of chapters 1-7 of a seminal paper by Moseley and Marks "Out of The Tar Pit" (2006).
Every day we, as software developers, deal with code which can he hard to maintain, prone to bugs, and difficult to reason about. As an embedded software developer I faced exactly those problems, maybe even more exagerrated by the specifics of firmware engineering.

For me reading "Out of The Tar Pit" proved to be an eye opening experience and allowed me to become a better developer, who is conscious about many faces of code complexities and effective maintenance of stateful code.
This paper gave names to things my gut feeling was telling me were wrong, classified them, explained why they are bad, and provided guidance on how to keep them in check.

**Name**:
Wojciech Migda

**Pronouns**:
He/him/his

**Twitter Handle (optional)**:

**Website (optional):**
www.linkedin.com/in/WojciechMigda
www.github.com/WojciechMigda

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
July, August
(slight preferrence towards August due to jetlag)

**Comment by paladique** [comment]
@WojciechMigda  thanks for your submission! Your talk wasn't included in this month's lineup, but we have a ticket set aside for you. Please email organizers@brooklynjs.com for details.

**Comment by paladique** [comment]
Thank you for your submission! Your talk wasn't included in this month's lineup but we have a ticket set aside for you! Please email organizers@brooklynjs.com for details!
