### ISSUE TITLE
Ezeerust: Assembly in WebAssembly in the Browser

### ISSUE THREAD

**Issue by stillinbeta** [brooklynjs/brooklynjs.github.io#565]
## BrooklynJS Talk Submission

**Talk Title:**

ezeerust: Assembly in WebAssembly in the browser

**Talk Description:**

[Zeerust] is an emulator for the [Z80] I wrote in Rust while at Recurse center. After I finished it, I realised that probably nobody was ever going to run it again, some random rust binary. But if I made it a webapp, maybe I could get people to play with it!

Rust can compile to WebAssembly, so I set out to make a frontend for it. I found a project called [yew], which let me write a React-style frontend entirely in Rust, making communication with my emulator easy! The finished emulator lives at [zeerust.stillinbeta.com][ezeerust].

In this talk, I'll discuss the trials of doing pure-web assembly development, how I went about deploying it, and what the development loop likes with in Rust. 

[zeerust]: https://github.com/stillinbeta/zeerust
[Z80]: https://en.wikipedia.org/wiki/Zilog_Z80
[yew]: https://docs.rs/yew/0.6.0/yew/index.html
[ezeerust]: https://zeerust.stillinbeta.com

**Name**: Liz Frost

**Pronouns**: she/her

**Twitter Handle (optional)**: [@stillinbeta](https://stillinbeta.com)

**Website (optional):** [stillinbeta.com](https://stillinbeta.com)

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
June, July, August

**Comment by paladique** [comment]
@stillinbeta Thank you for your submission! Your talk wasn't included in this month's lineup but we have a ticket set aside for you! Please email organizers@brooklynjs.com for details!

**Comment by paladique** [comment]
@stillinbeta your talk was accepted this month! We'll be emailing you soon with details!
