### ISSUE TITLE
Hot Reload... for your entire stack

### ISSUE THREAD

**Issue by dbentley** [brooklynjs/brooklynjs.github.io#566]
## BrooklynJS Talk Submission

**Hot Reload... for your entire stack**

**Talk Description**
One of js's key strengths is velocity. It's easy to hit save and see the page update. This is so important that new tools that make js more powerful and complicated also have to keep reload quick (webpack, typescript, babel).

But what if your backend isn't js? Or what if you update `package.json`, but forget to run `npm install`? Or what if you use containers and fast compiles are swamped by slow image builds?

You deserve Hot Reload for your entire stack. And it's possible.

I'll show Hot Reload in all the components of a demo app that includes js in the browser, a python frontend, and a go backend.

**Name**
Dan Bentley

**Pronouns**
He/Him

**Twitter Handle (optional)**:
@dbentley

**Months Available to Speak:**
June, July, August

**Comment by paladique** [comment]
@dbentley Thank you for your submission! Your talk wasn't included in this month's lineup but we have a ticket set aside for you! Please email organizers@brooklynjs.com for details!

**Comment by paladique** [comment]
@dbentley your talk has been accepted! Could you email organizers@brooklynjs.com for more details? Thanks!
