### ISSUE TITLE
p5.js: Creative coding with kids

### ISSUE THREAD

**Issue by saberkhaniscool** [brooklynjs/brooklynjs.github.io#567]
## BrooklynJS Talk Submission

**Talk Title**: p5.js - Creative coding with kids

**Talk Description**: I want to share with the collaboration between the NYC Dept of Ed and Processing Foundation has yielded in the #CSforAll program in Brooklyn and beyond.

**Name**: Saber Khan

**Pronouns**: he/him they/them

**Twitter Handle (optional)**: @ed_saber

**Website (optional):** edsaber.info

**Months Available to Speak:** June, July, August.

**Comment by paladique** [comment]
@saberkhaniscool Thank you for your submission! Your talk wasn't included in this month's lineup but we have a ticket set aside for you! Please email organizers@brooklynjs.com for details!

**Comment by paladique** [comment]
@saberkhaniscool your talk has been accepted for this month! We'll email you soon with details!

**Comment by paladique** [comment]
@saberkhaniscool your talk has been accepted for this month! We'll email you soon with details!
