### ISSUE TITLE
uSe THe PLaTfORm yOu cOWarDs

### ISSUE THREAD

**Issue by taravancil** [brooklynjs/brooklynjs.github.io#568]
## BrooklynJS Talk Submission

![spongebob](https://user-images.githubusercontent.com/7584833/59001913-765ff380-87de-11e9-8c51-4de46da16f53.jpg)

**Talk Title:** uSe THe PLaTfORm yOu cOWarDs

**Talk Description:** The Web is an imperfect and ever-evolving platform, and has been heavily influenced by frameworks like Dojo, MooTools, and jQuery. Frameworks can fill in the gaps where Web APIs fall short, and sometimes even point us toward the future of Web.

`document.querySelectorAll` was born out of jQuery, CSS Grid has a long lineage with roots in Microsoft Silverlight, and #smooshGate demonstrated how the advancement of Web APIs is inextricably linked to legacy frameworks deployed years ago.

Should we [build React into the browser?](https://twitter.com/seldo/status/1135150260425318400) Let’s explore the interplay between Web frameworks of today and Web APIs of tomorrow, and use the Web's history to make some predictions about how modern frameworks will make their way into the Web ~3.0~, ~4.0~, which version is this?

**Name**: Tara Vancil

**Pronouns**: she/her

**Twitter Handle (optional)**: [twitter.com/taravancil](https://twitter.com/taravancil)

**Website (optional):** [taravancil.com](https://taravancil.com)

**Months Available to Speak:** June, July, August

**Comment by taravancil** [comment]
I just realized that talks are ten minutes long and I definitely cannot do this talk in ten minutes. Whoops.

brb, submitting this abstract elsewhere 😭

**Comment by taravancil** [comment]
Reopening because @modernserf convinced me I can do this in 10 minutes

**Comment by paladique** [comment]
@taravancil your talk has been accepted for this month! 🎉 An email with details will be coming soon.
