### ISSUE TITLE
Double Your Salary With This One Simple Trick

### ISSUE THREAD

**Issue by matthew-gerstman** [brooklynjs/brooklynjs.github.io#571]
## BrooklynJS Talk Submission

**Talk Title:**
Double Your Salary With This One Simple Trick

**Talk Description:**
Five minutes, that’s how long the average salary negotiation lasts. This five minutes have an outsized impact on everything in your life from what you’re eating for dinner to where your kids go to college. In this talk, we’ll cover important tips and tricks for negotiating your salary at a new job. We’ll also cover some fundamentals about stock options and venture funding.

**Name**:
Matthew Gerstman

**Pronouns**:
he/him

**Twitter Handle (optional)**:
@MatthewGerstman

**Website (optional):**
matthewgerstman.com

**Months Available to Speak:** 
Jul, Aug, Sep

**Comment by paladique** [comment]
@matthew-gerstman thanks for your submission! Your talk wasn't included in this month's lineup, but we have a ticket set aside for you. Please email organizers@brooklynjs.com for details.

**Comment by matthew-gerstman** [comment]
Hi @paladique! Thanks so much. I won't be able to make it this week so feel free to give this ticket away. I'm hoping to make it aug/sep.

**Comment by paladique** [comment]
@matthew-gerstman 👋 Your talk wasn't included in this month's lineup but we have a ticket set aside for you! Please email organizers@brooklynjs.com for details!

**Comment by paladique** [comment]
Hi @matthew-gerstman your talk was accepted for this month! 🎉 We will email you soon with speaker details.
