### ISSUE TITLE
Applying the Unix Philosophy: How to Write Code That Lasts in 2019

### ISSUE THREAD

**Issue by marilyn** [brooklynjs/brooklynjs.github.io#572]
## BrooklynJS Talk Submission

**Talk Title:**
Applying the Unix Philosophy: How to Write Code That Lasts in 2019

**Talk Description:**
How can we continue to apply the Unix philosophy of writing programs that do one thing well when we make APIs and SPAs with dozens of features? We identify the most reusable and composable aspects of our tools. We'll look at code that stands the test of time and give you tips to write some too.

The Unix philosophy of writing programs that do one thing well and are composable has left a lasting mark on computer science. Most of us use the command line every day. We try to write code that is modular, reusable, and simple. We understand that simple does not equal easy. We know that foundational components of the machines we use every day were written decades ago.

And yet: web development in the last fifteen years or so may feel to some like a possessed carousel spinning so fast that before you get familiar with one JS framework, it's getting thrown off the side in favor of the next.

I'll argue understanding essential JS, your code in general, and some of its strongest and most useful components will also help you create small and light pieces that compose and customize to your needs. Understanding a bit of the history of the command line tools we use every day will cement the understanding of how valuable these tenets are, and will give you a stronger appreciation of the gurus from the days of punchcards and room-sized mainframes that held less data than your watch. Let's learn some of their lessons, adapted for our modern age.

**Name**:
Marilyn C. Cole

**Pronouns**:
she/her/y'all

**Twitter Handle (optional)**:
[mmmarilyn](https://twitter.com/mmmarilyn)

**Website (optional):**
[https://mmmarilyn.net/](https://mmmarilyn.net/)

**Months Available to Speak:** 
July, August, September

**Comment by paladique** [comment]
@marilyn thanks for your submission! Your talk wasn't included in this month's lineup, but we have a ticket set aside for you. Please email organizers@brooklynjs.com for details.

**Comment by paladique** [comment]
@marilyn your talk was accepted for this month's lineup 🎉 Speaker details coming soon via email!
