### ISSUE TITLE
Do search engines make good recommendations?

### ISSUE THREAD

**Issue by krapimimhannah** [brooklynjs/brooklynjs.github.io#573]
## BrooklynJS Talk Submission

**Talk Title:**
Do search engines make good recommendations? 

**Talk Description:**
90% of your day is searching for information: how to get home, how to get to work, what podcast to listen to, who to curate into your twitter feed. If you are building a product that offers content, and your users need to find specific content, then you need to build a search engine.

But building an effective search engine that meets your users’ needs is not easy. When we search for something, we have expectations that the engine will help us find things that we want easily or help us stumble upon things that we like and didn’t know existed. 

I want to change the narrative of content discovery. I will enumerate problems search engines solve - and don’t solve - based on your content and users. I will discuss my personal experiences with search engines being abused as databases and used in contexts where curation would have yielded better results for users with lower engineering costs. You will learn how to develop product hypotheses when you don’t have insights into your users just yet.

**Name**:
Hannah Mimi

**Pronouns**:
she/her

**Twitter Handle (optional)**:
@hannahmimipark

**Website (optional):**

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time! july, august, september

**Comment by paladique** [comment]
@krapimimhannah thanks for your submission! Your talk wasn't included in this month's lineup, but we have a ticket set aside for you. Please email organizers@brooklynjs.com for details.

**Comment by paladique** [comment]
@krapimimhannah your talk has been accepted for this month! Could you email organizers@brooklynjs.com for more details? Thanks!

**Comment by paladique** [comment]
@krapimimhannah 👋!  Just a gentle reminder that your talk was accepted and we're awaiting your email at organizers@brooklynjs.com to send you details.
