### ISSUE TITLE
Accessibility beyond aria-label

### ISSUE THREAD

**Issue by olarclara** [brooklynjs/brooklynjs.github.io#574]
## BrooklynJS Talk Submission

**Talk Title:**
Accessibility beyond aria-label

**Talk Description:**
It's common knowledge that accessibility matters but when looking for content on how to build accessible web apps, it often gets restricted to things such as adding `aria-label` and `aria-hidden` to elements when in reality, we are building interfaces that are much more complex. In this talk, I present a few common UI elements and how to make them more accessible with proper semantics and some less known aria attributes.

**Name**:
Maria Clara

**Pronouns**:
she/her

**Twitter Handle (optional)**:
@olarclara

**Website (optional):**

**Months Available to Speak:**
Jul

**Comment by paladique** [comment]
@olarclara your talk has been accepted, we'll email you soon with details!
