### ISSUE TITLE
BrooklynJS Talk Submission

### ISSUE THREAD

**Issue by jessiewuwu** [brooklynjs/brooklynjs.github.io#575]
## BrooklynJS Talk Submission

**Talk Title:**
Building HOTLINE BLING with AWS

**Talk Description:**
This Drake-themed talk will go over the three AWS services used to build my IVR (Interactive Voice Response), what I learned along the way, takeaways, and a few other AWS services used at New York Times. This talk was inspired by NYT's new automated phone system for customer service that my team and I built this year. Many people are familiar with S3 cloud storage, but AWS offers a lot of software and services that power things like Slack, Alexa, messenger bots, etc.

Following the same process of building 1-800-NYTIMES customer service phone line, I will go over how I built an IVR where you call a number and have to complete the lyrics to Drake's Hotline Bling song to continue to the next prompt in the call flow. If all goes right with audio setup, I can demo it by calling the number.

![image](https://user-images.githubusercontent.com/8339031/61486614-dca96b80-a971-11e9-909f-0af10775ba41.png)

**Name**:
Jessie Wu
**Pronouns**:
She/her
**Twitter Handle (optional)**:
@jessie__wu
**Website (optional):**

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
Sept, Oct, Feb

**Comment by paladique** [comment]
Thank you for your submission @jessiewuwu! Your talk wasn't included in this month's lineup but we have a ticket set aside for you! Please email organizers@brooklynjs.com for details!

**Comment by paladique** [comment]
@jessiewuwu thanks for your submission, your talk was included for this month's lineup! 🎉  We'll be sending you speaker details soon!

**Comment by paladique** [comment]
@jessiewuwu heard from Justin you're available for this month! Will send you speaker details soon!
