### ISSUE TITLE
Lesson learned from localizing Todoist app

### ISSUE THREAD

**Issue by stkao05** [brooklynjs/brooklynjs.github.io#576]
**Talk Title:**

Lesson learned from localizing Todoist

**Talk Description:**

At [Doist](https://doist.com/), making our product available to the global audiences has always been a core mission as a global remote company.

So we have been localizing our product, [Todoist](https://todoist.com), since very early on, and it is now available in 18 languages. In this talk, we will share with you some lessons we learned when working with localization.

**Name**:
Steven Kao

**Pronouns**:
He/Him

**Months Available to Speak:** 
August

**Comment by itamark** [comment]
Ah I was going to propose a very similar talk :-)

**Comment by stkao05** [comment]
Hi @paladique 
Sorry will close this issue now as I will not be able to attend the meetup  due to some personal matter 😢
