### ISSUE TITLE
Developing An Uncensorable Chat App/Intro to Blockchain

### ISSUE THREAD

**Issue by MistuhMok** [brooklynjs/brooklynjs.github.io#578]
## BrooklynJS Talk Submission

**Talk Title**: Developing An Uncensorable Chat App/Intro to Blockchain

**Talk Description**: I'd like to share my experiences developing on the Ethereum blockchain network featuring an app that provides a platform, for individuals with less freedom of speech than ours, to communicate anonymously and without restrictions by utilizing blockchain's immutable properties.

**Name**: Alex Mok

**Pronouns**: He/Him

**Twitter Handle (optional)**:

**Website (optional):**

**Months Available to Speak:** August, September

**Comment by paladique** [comment]
@MistuhMok 👋 Thank you for your submission! Your talk wasn't included in this month's lineup but we have a ticket set aside for you! Please email organizers@brooklynjs.com for details!

**Comment by MistuhMok** [comment]
@paladique Thank you! I was wondering if it was still possible to get this ticket. I emailed yesterday but haven't gotten a response and was hoping to attend tomorrow!

**Comment by paladique** [comment]
Thanks again for your submission @MistuhMok! Your talk wasn't included in this month's lineup, but we hope that you make another submission in the future!
