### ISSUE TITLE
Das I18n:  Performant, rich translation in React (to launch Lemonade 🇩🇪)

### ISSUE THREAD

**Issue by itamark** [brooklynjs/brooklynjs.github.io#579]
## BrooklynJS Talk Submission

**Talk Title:**
Das I18n:  Performant, rich translation in React (To launch [Lemonade  🍋](https://www.lemonade.com/)  in 🇩🇪)

**Talk Description:**
At Lemonade, we wanted our new German users to have a delightful experience - but more importantly, a German one. To achieve this, we needed to create a translation mechanism that allowed us to mix plaintext translations with richer content like links or any other `JSX` components. Additionally, creating these dynamic translations on the fly can be expensive, so we took some steps to reduce performance pitfalls, and avoid `dangerouslySetInnerHTML`.

**Name**:
Itamar Kestenbaum

**Pronouns**:
he/him

**Twitter Handle (optional)**:
[@itamarok](https://twitter.com/itamarok)

**Website (optional):**

**Months Available to Speak:** 
August

**Comment by paladique** [comment]
@itamark your talk has been accepted for this month! Could you email organizers@brooklynjs.com for more details? Thanks!
