### ISSUE TITLE
Server-sent Notifications using Stateful Serverless Functions

### ISSUE THREAD

**Issue by christiannwamba** [brooklynjs/brooklynjs.github.io#580]
## BrooklynJS Talk Submission

**Talk Title:**
Server-sent Notifications using Stateful Serverless Functions

**Talk Description:**
HTTP is stateless. This is by design and that is what makes serverless great for modern day HTTP APIs. There's always a grey area -- imagine setting up a timer on your server to send a calendar notification after x number of days. At that point you want your HTTP request to _remember_ what time the notification should be sent out. Durable Serverless Functions are a new type of serverless functions that gives you the tools you need to make your APIs stateful.

**Name**:
Christian Nwamba

**Pronouns**:
He/Him

**Twitter Handle (optional)**:
@codebeast

**Website (optional):**
https://codebeast.xyz

**Months Available to Speak:** 
September

**Comment by paladique** [comment]
@christiannwamba your talk has been accepted! We will be emailing you speaker details soon!
