### ISSUE TITLE
Burke Holland - Talk Submission

### ISSUE THREAD

**Issue by burkeholland** [brooklynjs/brooklynjs.github.io#581]
## BrooklynJS Talk Submission

**Talk Title:**
Please, everyone, put your entire development environment in Github

**Talk Description:**
I don't know about you, but I'm seriously tired of having to run through 15 README steps to setup a project only to find out that I have the wrong version of Python. Also, WHY DO I EVEN NEED PYTHON?!?

This is what it's like to setup a new project or framework. Developers have been stuck on this carousel of insanity for far too long. It's time to shut it off. Let's never configure another development environment ever again. Instead, lets put the entire thing in Github. I know that sounds like sarcasm, but it's actually for real. All you need is two text files. I'll show you how.

**Name**:
Burke Holland

**Twitter Handle (optional)**:
burkeholland

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!

October

**Comment by paladique** [comment]
@burkeholland your talk has been accepted! We'll be emailing you soon with details!
