### ISSUE TITLE
define: 2016 - 2019

### ISSUE THREAD

**Issue by sxywu** [brooklynjs/brooklynjs.github.io#583]
## BrooklynJS Talk Submission

**Talk Title:** define: 2016 - 2019.

**Talk Description:** this talk strays from my usual: instead of technical lessons and takeaways, I'll be talking about my personal journey as an independent creator of dataviz.  I'll be talking about past projects that have defined my data visualization styles, and future projects I'm excited about.

**Name**:  Shirley Wu

**Pronouns**: She/Her

**Twitter Handle (optional)**: @sxywu

**Website (optional):** sxywu.com

**Months Available to Speak:** September

**Comment by paladique** [comment]
@sxywu your talk has been accepted! Welcome back! We'll email you speaker details soon.
