### ISSUE TITLE
Ejecting create-react-app: "There is no undo", and Other Lies I've Been Told.

### ISSUE THREAD

**Issue by nickpalenchar** [brooklynjs/brooklynjs.github.io#584]
## BrooklynJS Talk Submission

**Talk Title:** Ejecting create-react-app: "There is no undo", and Other Lies I've Been Told.

**Talk Description:**  This investigative talk walks through the source code of react-scripts (the vehicle behind create-react-app's npm commands) in order to uncover the technical details of what exactly happens when you `npm run eject`. We'll conclude with a round-up of risks involved and possible failsafes of ejecting a CRA, and incidentally learn some advanced features of npm/node's architecture along the way.

After previously speaking at BrooklynJS in 2016, I'm excited to submit another talk for your consideration!

**Name**: Nick Palenchar

**Pronouns**: He/Him

**Twitter Handle (optional)** [palencharizard](https://twitter.com/palencharizard)

**Website (optional):** nickpalenchar.com

**Months Available to Speak:** September | October | November

**Comment by paladique** [comment]
Thank you for your submission @nickpalenchar! Your talk wasn't included in this month's lineup but we have a ticket set aside for you! Please email organizers@brooklynjs.com for details!

**Comment by paladique** [comment]
Thank you for your submission, @nickpalenchar! Your talk wasn't included for your selected months, s this issue will be closed. We hope to see another submission and in our lineup in the future!
