### ISSUE TITLE
Manipulating the DOM in Real Time using Audio Signal Data

### ISSUE THREAD

**Issue by daniel-mckemie** [brooklynjs/brooklynjs.github.io#585]
## BrooklynJS Talk Submission

**Talk Title:**
Manipulating the DOM in Real Time using Audio Signal Data

**Talk Description:**

Utilizing the Web Audio API, this project aims to generate real-time changes to the DOM based on the frequency analysis of an incoming audio signal.  Designed with the pairing of a  synthesizer or other direct input of an electronic device in mind, the Web Audio API (with assistance of the Wad.js library), analyzes the frequency (pitch) of an audio signal and returns the frequency (as a number) and note name (as a string).  These values are then assigned to different parameters of the DOM and styles, such as background color, image source retrieval, and others; and with these updates being done in very short time frames (<20 milliseconds), the effect is real-time rendering of visual elements synchronized to the music of the performer.

**Name**:
Daniel McKemie

**Pronouns**:
He/Him

**Twitter Handle (optional)**:
N/A

**Website (optional):**
https://www.danielmckemie.com
https://github.com/daniel-mckemie/audio-dom-manipulation (project discussed here)

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
September
November
January

**Comment by paladique** [comment]
Thank you for your submission @daniel-mckemie! Your talk wasn't included in this month's lineup but we have a ticket set aside for you! Please email organizers@brooklynjs.com for details!

**Comment by paladique** [comment]
Thanks for your submission! Your talk has been accepted! 🎉 We'll be sending you speaker details soon 😃
