### ISSUE TITLE
Building Crato, a centralized logging framework

### ISSUE THREAD

**Issue by jkurthoconnor** [brooklynjs/brooklynjs.github.io#586]
## BrooklynJS Talk Submission

**Talk Title:**  Building Crato, a centralized logging framework.

**Talk Description:** I recently co-created Crato, a framework to make setting up centralized log management for small applications easy. Crato is built with Node, bash, Apache Kafka, InfluxDB and AWS S3. It is deployed with Docker. In this talk I briefly introduce the notion of offsite centralized log management and then discuss some interesting problems (and our solutions) encountered in building this framework.

**Name**: Kurth O'Connor

**Pronouns**: he/him

**Twitter Handle (optional)**:

**Website (optional):** http://kurthoconnor.com

**Months Available to Speak:**  September, October, November

**Comment by paladique** [comment]
Thank you for your submission, @jkurthoconnor! Your talk wasn't included in this month's lineup but we have a ticket set aside for you! Please email organizers@brooklynjs.com for details!

**Comment by jkurthoconnor** [comment]
Thanks for the update @paladique, and for the ticket. I'll email 'organizers' today. I see the issue is still tagged 'october' and 'november'. Should I keep the issue / submission open for future consideration?

**Comment by paladique** [comment]
👋 Yes! Keep it open for future months, you can reply here if you need to make any changes to your availability and we'll update accordingly.

**Comment by jkurthoconnor** [comment]
Will do. Thank you.

**Comment by paladique** [comment]
@jkurthoconnor your talk has been accepted for October! We will email you with speaker details soon!
