### ISSUE TITLE
Map from First Principles: Adventures in Functional Programming, talk submission

### ISSUE THREAD

**Issue by thoughtbyte** [brooklynjs/brooklynjs.github.io#588]
## BrooklynJS Talk Submission

**Talk Title:** Map from First Principles: Adventures in Functional Programming

**Talk Description:** The best way to learn about and truly understand some of the built in JavaScript methods is to rewrite them. In this talk we'll do that with `map`. Then we'll do it again without using for loops. While it's impractical, rewriting map with recursion will let us explore some of the foundations of functional programming. We'll end with a brief discussion of the lambda calculus, and whether or not we can rewrite `map`, in principle, with nothing but anonymous functions.

**Name**: Vincent Abruzzo

**Pronouns**: he/him

**Months Available to Speak:** September, October, November

**Comment by paladique** [comment]
Thank you for your submission, @thoughtbyte! Your talk wasn't included in this month's lineup but we have a ticket set aside for you! Please email organizers@brooklynjs.com for details!

**Comment by paladique** [comment]
Thank you for your submission, @thoughtbyte! Your talk wasn't included for your selected months, s this issue will be closed. We hope to see another submission and in our lineup in the future!
