### ISSUE TITLE
Visualizing JS with Algo-viz

### ISSUE THREAD

**Issue by omarjuice** [brooklynjs/brooklynjs.github.io#589]
## BrooklynJS Talk Submission

**Talk Title:** Visualizing JS with AlgoViz

**Talk Description:** Visual learners need more robust tools for learning to code. I'll discuss how I built AlgoViz, a full featured and customizable algorithm visualizer. Designed with ease of use and visual aesthetics in mind, AlgoViz can show you the execution of your code, including its involved data structures and expressions. I'll go into detail about how I combined the concepts of meta-programming and reactive-programming to make transforming code into a visualization possible, as well as some of the major challenges I faced when writing the JS that does that.

**Name**: Omar Jameer

**Pronouns**: He/Him

**Twitter Handle (optional)**:

**Website (optional):**
deployed link: https://www.algoviz.io/
repo: https://github.com/omarjuice/algo-viz

**Months Available to Speak:** september, october

**Comment by paladique** [comment]
Thank you for your submission, @omarjuice! Your talk wasn't included in this month's lineup but we have a ticket set aside for you! Please email organizers@brooklynjs.com for details!

**Comment by omarjuice** [comment]
Thanks for the update @paladique! I'll be there anyway :)

**Comment by paladique** [comment]
@omarjuice thanks for your submission! Your talk has been accepted in this month's lineup. We will be sending you speaker details soon!
