### ISSUE TITLE
Generating 10 talks in 10 minutes.

### ISSUE THREAD

**Issue by zachkrall** [brooklynjs/brooklynjs.github.io#590]
## BrooklynJS Talk Submission

**Talk Title:** Generating 10 talks in 10 minutes.

**Talk Description:**

This is a talk about generating talks.

When we feed historical data to a machine learning process, can we actually generate new ideas?

What can we learn about ourselves by observing our mathematically warped reflections?

I scraped data from the Brooklyn.js GitHub repository containing 198 previous talk submissions. From that data, I generated a model using a LSTM (long short-term memory) recurrent neural network process with Tensorflow.js. In this talk, I will review the tools and steps taken for this project from start to finish. Lastly, I will demo the resulting talk submissions.

**Name**: Zach Krall

**Pronouns**: he/him

**Twitter Handle (optional)**: @zachkrall

**Website (optional):** zachkrall.com

**Months Available to Speak:** October November December

**Comment by paladique** [comment]
@zachkrall thanks for your submission! Your talk has been accepted this month 🎉 I couldn't find your email address on your profile/website so please email organizers@brooklynjs.com for your speaker details! 😄

**Comment by zachkrall** [comment]
Thank you! I sent an email :)
