### ISSUE TITLE
Devops survival guide for front ends

### ISSUE THREAD

**Issue by Ikana** [brooklynjs/brooklynjs.github.io#591]
## BrooklynJS Talk Submission

**Talk Title: Devops survival guide for front ends**

**Talk Description:** I'm a front end developer from Mexico City that ended up in NYC working doing DevOps stuff, having been the first or second engineering hire on the last 3 companies I worked at,I have some hard earned insight into bootstrapping a modern™ front end applications on nothing but s3, cloud front and lambda. In this talk I would explain the stack to deploy weekend-side-project applications that cost cents a month to maintain. Using only JS(and some terraform).

**Name**: Rodrigo Quezada

**Pronouns**: He/Him (but not attached to them that much)

**Twitter Handle (optional)**: rodikana

**Website (optional):** roderik.io

**Months Available to Speak:** October, November, December

**Comment by paladique** [comment]
@Ikana your talk has been accepted for this month! 🎉  You should have received an email with speaker details, reach out to organizers@brooklynjs.com if you haven't.
