### ISSUE TITLE
Creating quality sample code for Twitter Developer Labs

### ISSUE THREAD

**Issue by JessicaGarson** [brooklynjs/brooklynjs.github.io#592]
## BrooklynJS Talk Submission

**Talk Title:**
 Creating quality sample code for Twitter Developer Labs

**Talk Description:**
This talk will go through the processes we used to make sure we created quality sample code for the launch of Twitter Developer Labs. 

The outline of this talk will be as follows:
*What is Twitter Developer Labs?*
Twitter Developer Labs is a new program that allows developers to partner with us to create and shape the future of our API. These releases allow developers to test and share feedback on previews of new API products and features.

*Why create sample code?*
The main objective is helping us get to hello world faster and inspiring folks to build with the new APIs.

*Accessibility* 
Developers who use our API come from many different backgrounds and skill sets. 

*What does good sample code look like*
Good sample code focuses on the following:
- Readability 
- Easy to replicate without complicated set up
- Consistent 

*What we learned in this process*
Our key lessons were as follows:
- The importance of peer review
- Making Hello World as easy as possible 

I’ll conclude with next steps and how to reach out to me.

**Name**
Jessica Garson

**Pronouns**
She/They

**Twitter Handle**
JessicaGarson

**Email**
jgarson@twitter.com

**Months Available to Speak:**
November, December

**Comment by paladique** [comment]
Thanks for your submission! Your talk has been accepted! 🎉 We'll be sending you speaker details soon 😃

**Comment by paladique** [comment]
@JessicaGarson Your talk has been accepted! We'll be sending you speaker details soon!
