### ISSUE TITLE
The Math of Addiction: In Which I Make a Silly Game and Freak Myself Out

### ISSUE THREAD

**Issue by citurbe** [brooklynjs/brooklynjs.github.io#594]
## BrooklynJS Talk Submission

**Talk Title:** The Math of Addiction: In Which I Make a Silly Game and Freak Myself Out

**Talk Description:** A while back, I was looking for a side project to do, and decided to make a clone of [Cookie Clicker](https://orteil.dashnet.org/cookieclicker/). Digging into the math behind how that game works taught me some disturbing things about how easy it is for a piece of software to get its hooks into a user's brain. Now I'd like to spread that disturbed feeling to you!

**Name**: Craig Iturbe

**Pronouns**: He/Him

**Website (optional):** [craigiturbe.co](www.craigiturbe.co)

**Months Available to Speak:** October, November

**Comment by paladique** [comment]
@citurbe your talk was selected for this month's lineup 🎉! Email organizers@brooklynjs.com for your speaker details.
