### ISSUE TITLE
ES2019 features you'll love to use

### ISSUE THREAD

**Issue by erin-at-work** [brooklynjs/brooklynjs.github.io#595]
## BrooklynJS Talk Submission

**Talk Title:**
October: Here are the ES2019 features you'll love to use (can't think of a spooky theme title)
November: Here are the ES2019 features to be thankful for 🙏 
December: Here are the ES2019 features to know before 2020

**Talk Description:**
Abstract: With the release of ES10 aka ES2019, our lives as JavaScript developers just got a little bit easier. I'll go over some of the new features including `Object.fromEntries()`, `trimStart()`, `flatMap()`, optional catch binding, and more that we can start using in our code. I'll be using spoookkyy examples 👻 to stay on the Halloween theme.

**Name**: Erin Lee

**Pronouns**: she/her

**Twitter Handle (optional)**: @erinleelikes

**Website (optional):** erinleelikes.com

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
October, November, December

**Comment by paladique** [comment]
@erin-at-work your talk has been accepted for this month's lineup! Could you email organizers@brooklynjs.com so we can send you speaker details? Thanks!!
