### ISSUE TITLE
Talk Submission: Grappling with higher powers

### ISSUE THREAD

**Issue by fzembow** [brooklynjs/brooklynjs.github.io#597]
## BrooklynJS Talk Submission

**Talk Title:**
Grappling with higher powers (draft title)

**Talk Description:**
I'd to talk about some pitfalls of developing in a browser context, particularly when there are "higher powers" like the operating system or an embedding app affecting what events make their way down to the JS world. I'd like to mention a few examples, like browsers eating keyboard shortcuts, Safari placing the on-screen keyboard on top of the window, and apps like Instagram and Snapchat preventing gestures from reaching a webview, along with some workarounds and approaches to testing.

**Name**:
Fil Zembowicz

**Pronouns**:
he/him

**Twitter Handle (optional)**:
fzembow

**Website (optional):**
https://filosophy.org

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
November, January, February

**Comment by fzembow** [comment]
I can no longer do November (moving apartments, and it hasn't been confirmed). Looking forward to Jan or Feb :)

**Comment by paladique** [comment]
@fzembow thanks for your submission! Your talk has been accepted for this month 🎉  Speaker details are coming via email soon!
