### ISSUE TITLE
Third Dimensional Jank

### ISSUE THREAD

**Issue by FuzzyWobble** [brooklynjs/brooklynjs.github.io#598]
## BrooklynJS Talk Submission

** Talk Title: Third Dimensional Jank **

** Talk Description: scans, stickers, memes, cease+desists, and children with computers.  **

** Name: Fuzzy Wobble **

** Website (optional): [fuzzywobble.com](http://fuzzywobble.com) **

** Months Available to Speak: Nov,Dec **

**Comment by FuzzyWobble** [comment]
Dec would be better, thanks.      :  )

**Comment by paladique** [comment]
@FuzzyWobble Thanks for your submission, your talk has been accepted! 🎉 Speaker details coming soon!
