### ISSUE TITLE
Program Quantum Computers in JavaScript!

### ISSUE THREAD

**Issue by mapmeld** [brooklynjs/brooklynjs.github.io#599]
## BrooklynJS Talk Submission

**Talk Title:**
Program Quantum Computers in JavaScript!

**Talk Description:**
In a few labs around the world, the next generation of computers are being built out of "qubits". If a quantum computer is connected to the internet, we can program it in JavaScript! I'm not a physicist, so I'll do a high-level overview of what qubits might be useful for, then present [Quantum-Peep](https://github.com/mapmeld/quantum-peep), a TypeScript module which I've written to generate quantum assembly code for the four leading quantum computing services: IBM, Rigetti, Google, and Microsoft.

I submitted talk #550 earlier this year but had to leave town. Now that Quantum Supremacy is in the news, I'm bringing it back

**Name**:
Nick Doiron

**Pronouns**:
He/him

**Twitter Handle (optional)**:
@mapmeld

**Months Available to Speak:**
December / January are good

**Comment by paladique** [comment]
@mapmeld Thanks for your submission! Your talk has been accepted! Speaker details coming soon!
