### ISSUE TITLE
3 submissions in 1!

### ISSUE THREAD

**Issue by billyroh** [brooklynjs/brooklynjs.github.io#600]
## BrooklynJS Talk Submission

I've given all three talks before at some conferences. I'd be happy to do any of them! Let me know if it's be easier to read through them as separate issues and I can separate them.

## Talk #1: Reviving the Dream of the 90s with WebGL

If you’re like me, you’ve spent hours staring at Windows 98 screensavers when you were growing up. Sadly, screensavers are no more, but we’ve got the power to fix that. In this talk, I’ll walk you through how to harness modern technology to revive the dream of the 90s. Using A-Frame and other modern web technologies, I’ll show you how to recreate some iconic imagery, including 3D Pipes, The Maze, and The Matrix screensavers.

Demo: https://billyroh.com/screensavers/

## Talk #2: Learning through Art: An Introduction to VR

Virtual reality can be daunting—it’s unclear what you can do with it and it’s hard to know where to even start. I’ll introduce you to fundamental VR concepts by re-creating an interactive installation art piece by Yayoi Kusama in A-Frame, a VR web framework. So you can try it out at home, I’ll also walk you through the ecosystem of VR libraries and affordable hardware that’s currently out there.

Demo: https://billyroh.com/obliteration/

## Talk #3: Albers as a Millennial

What kind of art would Josef and Anni Albers have made if they were millennials? Come learn about how to make generative interactive art with the magic of JavaScript. The audience will learn about applying colour theory with HSL, composing and generating your own patterns with SVG, and creating a sense of depth with motion and interaction.

Demo: https://billyroh.com/albers/

## About me

**Name**: Billy Roh

**Pronouns**: he/him

**Twitter Handle (optional)**: @billyroh

**Website (optional):** https://billyroh.com/

**Months Available to Speak:** November, December, January

**Comment by paladique** [comment]
@billyroh your talk has been accepted! We'll go with the VR one! I don't see an email on your profile, so please email us at organizers@brooklynjs.com for details!
