### ISSUE TITLE
Building a Design System

### ISSUE THREAD

**Issue by morelme** [brooklynjs/brooklynjs.github.io#601]
## BrooklynJS Talk Submission

**Talk Title:** 
Building a Design System

**Talk Description:**
We love to throw around the phrase 'Design System', but what does is actually mean to build a useful one? If your codebase isn't standardized, where do you start? What tools are out there to help? This talk will cover how to successfully build a Design System that people like to use, and how to avoid some of the pitfalls along the way. 

Inspired by what I've learned while building a Design System at Nomad Health.

**Name**:
Melissa Morel

**Pronouns**:
She/Her

**Months Available to Speak:** November, January, February

**Comment by paladique** [comment]
@morelme Thanks for your submission! Your talk has been accepted! 🎉 I don't see an email in your profile, so email us at organizers@brooklynjs.com for speaker details!
