### ISSUE TITLE
Talk submission: Enhancing Your Animation Powers with GSAP 3

### ISSUE THREAD

**Issue by ZachSaucier** [brooklynjs/brooklynjs.github.io#602]
## BrooklynJS Talk Submission

**Talk Title:** Enhancing Your Animation Powers with GSAP 3

**Talk Description:** GSAP 3 is GreenSock's largest update yet, with over 50 new features and half the file size of the old TweenMax. This talk will cover some of the new features and how they can make your job of animating easier.
P.S. I work for GreenSock 💚And I have stickers!

**Name**: Zach Saucier

**Pronouns**: He/him

**Twitter Handle (optional)**: https://twitter.com/ZachSaucier

**Website (optional):** https://zachsaucier.com/

**Months Available to Speak:** November, January, February.

**Comment by ZachSaucier** [comment]
Just noting that I changed my availability for this talk because I found out that we get to stay in NYC!

**Comment by paladique** [comment]
@ZachSaucier  thanks for your submission! Your talk has been accepted for this month :tada: Speaker details are coming via email soon!

**Comment by ZachSaucier** [comment]
Hey Jasmine, thanks so much for the offer! I'm honored. Unfortunately I didn't know I would be a speaker until now so I already made plans to be out of town for this month's meeting. However, I'd love to speak in a future month (like February) if that's an option! 

Let me know so I can add it to my schedule ahead now.

**Comment by ZachSaucier** [comment]
Hey @paladique. As mentioned before, I'm open to talking at a future meeting if you guys are open to it!

**Comment by paladique** [comment]
@ZachSaucier your talk has been accepted this month! We'll email you speaker details soon!

**Comment by ZachSaucier** [comment]
@paladique Thanks again! Unfortunately I have already made plans for that evening as well. You all should consider planning a bit further in advance!

I will not be available for at least March and April's meetups unfortunately.

**Comment by ZachSaucier** [comment]
I take that back. I will actually be able to make it - I looked at the wrong evening in my calendar. So sorry about that! It would still be helpful to know a little further in advance.

I look forward to speaking and hanging out with you all!

**Comment by ZachSaucier** [comment]
When is the next BrooklynJS event? Are you all considering doing a web version instead?
