### ISSUE TITLE
Talk Submission: You Can Invent Javascript Scopes

### ISSUE THREAD

**Issue by nt591** [brooklynjs/brooklynjs.github.io#603]
## BrooklynJS Talk Submission

**Talk Title:**
You Can Invent Javascript Scopes

**Talk Description:**
Javascript scoping can be tricky for newcomers. Once a new developer learns about closures, it can be all the more confusing. How does a function capture a variable inside it's scope? This talk aims to demystify scoping by re-inventing lexical environments and scope chains in Javascript.

**Name**:
Nikhil Thomas

**Pronouns**:
He/Him

**Twitter Handle (optional)**:
[nikhilthomas90](https://twitter.com/nikhilthomas90)

**Website (optional):**
https://www.nthomas.org
(original post of this talk at https://nthomas.org/2019-11-11-you-can-invent-js-scope/)

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!

~December, January, February~ March, April, May

**Comment by paladique** [comment]
@nt591 thanks for your submission! Your talk wasn't accepted but we have a ticket set aside for you! Email organizers@brooklynjs.com for details!

**Comment by paladique** [comment]
@nt591 Thanks for your submission! We will be taking February off so we won't have any talks. Since this was the last month for your availability I will close this issue. Please reopen if you'd like to be considered for future months.

**Comment by nt591** [comment]
Thank you for considering me!

**Comment by nt591** [comment]
@paladique if I'd like to resubmit, do I re-open this ticket? Or file a new issue?

**Comment by paladique** [comment]
I’ll reopen for ya!

**Comment by paladique** [comment]
👋 @nt591 your talk has been accepted this month! Can you email organizers@brooklynjs.com so we can send you more details? Thanks and see you soon!
