### ISSUE TITLE
Talk Submission: Sustainable Funding for OSS

### ISSUE THREAD

**Issue by transitive-bullshit** [brooklynjs/brooklynjs.github.io#605]
## BrooklynJS Talk Submission

**Talk Title:** Sustainable Funding for OSS

**Talk Description:** What is OSS sustainability and how can we work together to build more supportive and rewarding open source communities?

**Name**: Travis Fischer

**Pronouns**: He / Him

**Twitter Handle (optional)**: transitive_bs

**Website (optional):** https://transitivebullsh.it and https://saasify.sh/

**Months Available to Speak:** December, January

I live nearby and would love to chat about OSS sustainability, different approaches to OSS funding, and the work we're doing with [Saasify](https://github.com/saasify-sh/saasify), a startup built with JS and TS.

We'd also be interested in sponsoring Brooklyn JS in the future. 😄

**Comment by paladique** [comment]
@transitive-bullshit thanks for your submission! Your talk wasn't accepted but we have a ticket set aside for you! Email organizers@brooklynjs.com for details!

**Comment by paladique** [comment]
@transitive-bullshit your talk wasn't selected for the months you picked, so we will be closing this issues. Thanks again for your submission and we hope to see this or another one soon! Also, if you're still interested in sponsoring please email sponsorships@brooklynjs.com
