### ISSUE TITLE
Talk Submission: bcoin, a complete Bitcoin library and full node for nodejs

### ISSUE THREAD

**Issue by pinheadmz** [brooklynjs/brooklynjs.github.io#606]
## BrooklynJS Talk Submission

**Talk Title:**

 bcoin, a complete Bitcoin library and full node for nodejs

**Talk Description:**

Bcoin is an alternative implementation of the Bitcoin protocol written in JavaScript. In my talk I will explain Bitcoin as simply as possible, describe what bcoin does and how it fits in to the overall Bitcoin ecosystem, enumerate its advanced features and use cases, and hopefully perform some live code demonstrations. Bcoin uses lots of interesting features of nodejs including EventEmitters and disk I/O, and the code employs lots of compelling optimizations for efficient JavaScript code.

I have actually given this presentation before at the SF NodeJS meetup: https://www.youtube.com/watch?v=nF5UewmZCzM

**Name**:

Matthew Zipkin

**Pronouns**:

He, Him, His

**Twitter Handle (optional)**:

@MatthewZipkin

**Website (optional):**

https://github.com/bcoin-org/bcoin
https://bcoin.io/

**Months Available to Speak:** 
2019: Jan / Feb / Mar

Thank you!

**Comment by paladique** [comment]
@pinheadmz thanks for your submission! Your talk wasn't selected this month but we have a ticket set aside for you, in case we are sold out. Email organizers@brooklynjs.com for details!

**Comment by pinheadmz** [comment]
Oh that's very sweet thank you!

**Comment by paladique** [comment]
@pinheadmz Thanks for your submission! We will be taking February off so we won't have any talks. See you next month!

**Comment by pinheadmz** [comment]
Cool see ya then! I'm still available through April / May as well if that works out better.

**Comment by paladique** [comment]
@pinheadmz your talk has been accepted this month! 🎉 We'll send an email with details soon!

**Comment by pinheadmz** [comment]
😊 😊 😊
