### ISSUE TITLE
Introduction to Prototypical Inheritance

### ISSUE THREAD

**Issue by shaunlawrencecarland** [brooklynjs/brooklynjs.github.io#607]
## BrooklynJS Talk Submission

**Talk Title:**
Introduction to Prototypical Inheritance

**Talk Description:**
Prototypical Inheritance is a hairy topic that is challenging to understand, but necessary to take your JavaScript knowledge to the next level.  In this talk, we will use Pokemon as an example to explain the prototype chain, differences between class based inheritance and protype inheritance, constructor functions, and static properties/methods.

**Name**:
Shaun Carland

**Pronouns**:
He/Him/His
**Twitter Handle (optional)**:

**Website (optional):**
shauncarland.com

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!

December, January, and Febuary

**Comment by paladique** [comment]
@shaunlawrencecarland thanks for your submission! Your talk has been accepted for this month 🎉 Speaker details are coming via email soon!
