### ISSUE TITLE
Speaker - SSSAG Stack

### ISSUE THREAD

**Issue by AlexMercedCoder** [brooklynjs/brooklynjs.github.io#608]
## BrooklynJS Talk Submission

**Talk Title:**

SSSAG Stack - Looking to the future

**Talk Description:**

Discussing how futures stacks will likely comprise of GraphQL/Svelte/Serverless

**Name**: Alex Merced

**Pronouns**: He/Him

**Twitter Handle (optional)**: AlexMercedCoder

**Website (optional):** AlexMercedCoder.com

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
January/February/March

**Comment by paladique** [comment]
@AlexMercedCoder thanks for your submission! Your talk has been accepted for this month 🎉 Speaker details coming via email soon!
