### ISSUE TITLE
Talk Submission: Building LightOS with React Native

### ISSUE THREAD

**Issue by hhff** [brooklynjs/brooklynjs.github.io#609]
## BrooklynJS Talk Submission

**Talk Title:**
Building LightOS with React Native

**Talk Description:**
A play-by-play of how [The Light Phone](https://www.thelightphone.com/)'s "LightOS" was built leveraging React Native as the primary view layer. High level detail is [here](https://medium.com/sanctuary-computer-inc/building-lightos-with-react-native-4b6e4ad1cd7f).

**Name**:
Hugh Francis

**Pronouns**:
He/him

**Twitter Handle (optional)**:
@_hhff

**Website (optional):**
[https://www.sanctuary.computer](https://www.sanctuary.computer)

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
February / March / April

**Comment by paladique** [comment]
@hhff Thanks for your submission! We will be taking February off so we won't have any talks. See you next month!

**Comment by paladique** [comment]
👋 @hhff your talk has been accepted this month We'll be sending you speaker details via email soon!
