### ISSUE TITLE
Talk Submission: Sustainable Mentorship

### ISSUE THREAD

**Issue by GabiOC** [brooklynjs/brooklynjs.github.io#611]
## BrooklynJS Talk Submission

**Talk Title:** I Mentored Strangers From the Internet for 6 Months and This Is What I Learned

**Talk Description:** 
Many of us get requests from strangers asking for career advice. What happens if we do something about it?

In this talk, I’ll go over what I learned from six months of mentorship roulette, including how tough it is to get your first job as an engineer and how much knowledge I had taken for granted until I started sharing it with others. The talk will also go into how building human relationship skills provides professional benefits for ICs and managers alike, strategies for how to sustainably give back to the tech community and the importance of not pulling up the ladder behind you.

**Name**: Gabi O'Connor

**Pronouns**: She/Her

**Twitter Handle (optional)**: `_gabioc_`

**Website (optional):**

**Months Available to Speak:** February, March, April

**Comment by paladique** [comment]
@GabiOC Thanks for your submission! We will be taking February off so we won't have any talks. See you next month!

**Comment by paladique** [comment]
👋 @GabiOC your talk has been accepted this month! Can you email organizers@brooklynjs.com so we can send you more details? Thanks and see you soon!
