### ISSUE TITLE
Talk Submission: Containers for Everyone

### ISSUE THREAD

**Issue by danielleadams** [brooklynjs/brooklynjs.github.io#613]
## BrooklynJS Talk Submission

**Talk Title:**
Containers for Everyone

**Talk Description:**
Cloud Native Buildpacks make it easy to build Docker images from JavaScript source code. I'd like to discuss how JS developers can learn how to create Docker images without Dockerfiles, perform application-level upgrades,  and run containerized applications with little configuration. (Docker experience not required.)

**Name**:
Danielle Adams

**Pronouns**:
she/her

**Twitter Handle (optional)**:
[@adamzdanielle](https://twitter.com/adamzdanielle)

**Website (optional):**

**Months Available to Speak:**
February, March, May

**Comment by paladique** [comment]
@danielleadams Thanks for your submission! We will be taking February off so we won't have any talks. See you next month!

**Comment by danielleadams** [comment]
@paladique No problem 😄 I realized I had my months backwards... I can't do March, but I can do April and May
